--------------------------------------------------------------------------------
# ***Mohamed Halith M K***
## **Title**  : ***Cross Market Analysis***
### ***GUVI Mini Project - 1***
--------------------------------------------------------------------------------

# **Data Collection**

##### **All Crypto Coins Data**

In [1]:
import requests
import time
import pandas as pd

In [2]:
data_crypto = []

for page_num in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
  response = requests.get(url)
  if response.status_code == 200:
    data_crypto.extend(response.json()) # Extend the list with data from current page
    print(f"Collected data from page {page_num}")
  else:
    print(f"Error collecting data from page {page_num}: {response.status_code}")
    page_num += 1
  time.sleep(5) # Increased wait time to 1 second to avoid rate limiting

print ("==========================================")
print(f"Total data collected: {len(data_crypto)}")

Collected data from page 1
Collected data from page 2
Collected data from page 3
Collected data from page 4
Collected data from page 5
==========================================
Total data collected: 1250

In [3]:
print(f"Total Data of Cryptocurrencies: {len(data_crypto)}")

Total Data of Cryptocurrencies: 1250

**Column Rename**

In [4]:
rename_columns = []

for i in data_crypto:
  rename_columns.append(dict(
      coin_id = i['id'],
      symbol = i['symbol'],
      coin_name = i['name'],
      current_price = i['current_price'],
      market_cap = i['market_cap'],
      market_cap_rank = i['market_cap_rank'],
      total_volume = i['total_volume'],
      circulating_supply = i['circulating_supply'],
      total_supply = i['total_supply'],
      ath = i['ath'],
      atl = i['atl'],
      last_updated = i['last_updated']
      ))

In [5]:
print(f"Total data for filtered columns: {len(rename_columns)}")

Total data for filtered columns: 1250

In [6]:
crypto_df = pd.DataFrame(rename_columns) #visualizing data in pandas
crypto_df.head()

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6906516.00,138429855767643,1,2.018402e+12,2.003664e+07,2.003664e+07,11187013.00,3993.420000,2026-06-01T08:10:21.670Z
1,ethereum,eth,Ethereum,187608.00,22647617493837,2,1.153910e+12,1.206852e+08,1.206852e+08,431946.00,28.130000,2026-06-01T08:10:21.446Z
2,tether,usdt,Tether,94.84,17852182065363,3,3.880867e+12,1.882392e+11,1.937062e+11,105.52,36.860000,2026-06-01T08:10:16.821Z
3,binancecoin,bnb,BNB,65237.00,8794692700692,4,2.014503e+11,1.347845e+08,1.347845e+08,121422.00,2.580000,2026-06-01T08:10:21.738Z
4,ripple,xrp,XRP,123.76,7667132462337,5,1.408457e+11,6.197784e+10,9.998566e+10,313.99,0.159343,2026-06-01T08:10:16.681Z

In [7]:
# date only extract from last_updated
crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df.head()

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6906516.00,138429855767643,1,2.018402e+12,2.003664e+07,2.003664e+07,11187013.00,3993.420000,2026-06-01
1,ethereum,eth,Ethereum,187608.00,22647617493837,2,1.153910e+12,1.206852e+08,1.206852e+08,431946.00,28.130000,2026-06-01
2,tether,usdt,Tether,94.84,17852182065363,3,3.880867e+12,1.882392e+11,1.937062e+11,105.52,36.860000,2026-06-01
3,binancecoin,bnb,BNB,65237.00,8794692700692,4,2.014503e+11,1.347845e+08,1.347845e+08,121422.00,2.580000,2026-06-01
4,ripple,xrp,XRP,123.76,7667132462337,5,1.408457e+11,6.197784e+10,9.998566e+10,313.99,0.159343,2026-06-01

In [8]:
coin_name_df = pd.DataFrame(crypto_df[["coin_id", "coin_name"]]).copy()# Extracting coin_name column into a separate DataFrame for merging with top_coins_df later

coin_name_df

             coin_id     coin_name
0            bitcoin       Bitcoin
1           ethereum      Ethereum
2             tether        Tether
3        binancecoin           BNB
4             ripple           XRP
...              ...           ...
1245  newton-project            AB
1246    flying-tulip  Flying Tulip
1247     wemix-token         WEMIX
1248    cheems-token  Cheems Token
1249           river         River

[1250 rows x 2 columns]

##### **Top Coins Historical Prices**

In [ ]:
# to run this code, you need to wait for few minutes as it is collecting data from API and processing it. Please be patient.

In [32]:
# getting data for top coins price history
all_coins = []

coin_ids = ['bitcoin','ethereum','tether','binancecoin','ripple']

for i in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
  response=requests.get(url)

  if response.status_code == 200:
    coins=response.json()
    prices = coins["prices"]#extracting data to table and converting ms to datestamp
    time.sleep(5)

    for ts, price in prices:
      all_coins.append({"coin_id": i,"date": pd.to_datetime(ts, unit="ms"),"price": price})

top_coins_df = pd.DataFrame(all_coins)

In [33]:
top_coins_df

      coin_id                date         price
0     bitcoin 2025-06-02 00:00:00  9.040802e+06
1     bitcoin 2025-06-03 00:00:00  9.038741e+06
2     bitcoin 2025-06-04 00:00:00  9.036689e+06
3     bitcoin 2025-06-05 00:00:00  9.003749e+06
4     bitcoin 2025-06-06 00:00:00  8.729537e+06
...       ...                 ...           ...
1825   ripple 2026-05-29 00:00:00  1.258277e+02
1826   ripple 2026-05-30 00:00:00  1.262013e+02
1827   ripple 2026-05-31 00:00:00  1.271950e+02
1828   ripple 2026-06-01 00:00:00  1.264488e+02
1829   ripple 2026-06-01 08:13:34  1.238521e+02

[1830 rows x 3 columns]

In [34]:
# date only extract from datestamp
top_coins_df["date"] = pd.to_datetime(top_coins_df["date"]).dt.date
top_coins_df.head()

   coin_id        date         price
0  bitcoin  2025-06-02  9.040802e+06
1  bitcoin  2025-06-03  9.038741e+06
2  bitcoin  2025-06-04  9.036689e+06
3  bitcoin  2025-06-05  9.003749e+06
4  bitcoin  2025-06-06  8.729537e+06

In [35]:
top_coins_df = pd.merge(top_coins_df, coin_name_df, on="coin_id", how="left") # Add coin_name column to top_coins_df
top_coins_df

      coin_id        date         price coin_name
0     bitcoin  2025-06-02  9.040802e+06   Bitcoin
1     bitcoin  2025-06-02  9.040802e+06   Bitcoin
2     bitcoin  2025-06-02  9.040802e+06   Bitcoin
3     bitcoin  2025-06-02  9.040802e+06   Bitcoin
4     bitcoin  2025-06-02  9.040802e+06   Bitcoin
...       ...         ...           ...       ...
9145   ripple  2026-06-01  1.238521e+02       XRP
9146   ripple  2026-06-01  1.238521e+02       XRP
9147   ripple  2026-06-01  1.238521e+02       XRP
9148   ripple  2026-06-01  1.238521e+02       XRP
9149   ripple  2026-06-01  1.238521e+02       XRP

[9150 rows x 4 columns]

In [36]:
top_coins_df.isnull().sum()

coin_id      0
date         0
price        0
coin_name    0
dtype: int64

##### **Oil Prices(WTI Crude)**

In [9]:
# data collection from csv file - github link
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df.head()

         Date  Price
0  1986-01-02  25.56
1  1986-01-03  26.00
2  1986-01-06  26.53
3  1986-01-07  25.85
4  1986-01-08  25.87

In [10]:
# extracting data from Jan 2020 - Feb 2026 ==> mentioned in project file
oil_df['Date'] = pd.to_datetime(oil_df['Date'])
start_date = pd.to_datetime('2020-01-01')
end_date   = pd.to_datetime('2026-02-23')

oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]

oil_df.head()

           Date  Price
8569 2020-01-02  61.17
8570 2020-01-03  63.00
8571 2020-01-06  63.27
8572 2020-01-07  62.70
8573 2020-01-08  59.65

In [11]:
oil_df = oil_df.reset_index(drop=True)
oil_df.head()

        Date  Price
0 2020-01-02  61.17
1 2020-01-03  63.00
2 2020-01-06  63.27
3 2020-01-07  62.70
4 2020-01-08  59.65

##### **Stock Prices (Yahoo Finance API)**

In [12]:
# collect following stocks data from Yahoo Finance API
import yfinance as YF

In [13]:
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

stk_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
stk_df.head()

[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [14]:
# colleting data separately for easy undersating
# "^NSEI"
stocks1_df = stk_df["^NSEI"].reset_index()
stocks1_df.head()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [15]:
# adding column ==> "tickers"
stocks1_df.insert(1, "Ticker", "^NSEI")
stocks1_df.head()

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [16]:
# finding nulls from collected data
print(stocks1_df.isnull().sum())

Price
Date       0
Ticker     0
Open      72
High      72
Low       72
Close     72
Volume    72
dtype: int64

In [17]:
# remove null for clear undersating
stocks1_df = stocks1_df.dropna()

In [18]:
stocks1_df.head()

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [19]:
print(stocks1_df.isnull().sum())

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [20]:
# "^IXIC"
stocks2_df = stk_df["^IXIC"].reset_index()

stocks2_df.insert(1, "Ticker", "^IXIC") # inserting column

stocks2_df = stocks2_df.dropna() # removing nulls

stocks2_df.head()

Price,Date,Ticker,Open,High,Low,Close,Volume
1,2020-01-02,^IXIC,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03,^IXIC,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06,^IXIC,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07,^IXIC,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09
5,2020-01-08,^IXIC,9068.030273,9168.889648,9059.379883,9129.240234,2.472620e+09

In [21]:
stocks2_df.isnull().sum() # checking null values are removed

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [22]:
# "^GSPC"
stocks3_df = stk_df["^GSPC"].reset_index()

stocks3_df.insert(1, "Ticker", "^GSPC") # inserting column

stocks3_df = stocks3_df.dropna() # removing nulls

stocks3_df.head()

Price,Date,Ticker,Open,High,Low,Close,Volume
1,2020-01-02,^GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,^GSPC,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,^GSPC,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,^GSPC,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09
5,2020-01-08,^GSPC,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09

In [23]:
stocks3_df.isnull().sum() # checking null values are removed

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [24]:
# merging all stocks after cleaning nulls and adding column for comparision
stks_df = pd.concat([stocks1_df, stocks2_df, stocks3_df])
stks_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
1587,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
1589,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
1590,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
1591,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
1592,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [25]:
stks_df.isnull().sum() # verify nulls after merging all three data

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [26]:
stks_df.head()

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

# **Saving data into csv**

In [37]:
crypto_df = crypto_df.to_csv("crypto_df.csv", index=False)

top_coins_df = top_coins_df.to_csv("top_coins_df.csv", index=False)

oil_df = oil_df.to_csv("oil_df.csv", index=False)

stks_df = stks_df.to_csv("stks_df.csv", index=False)

In [38]:
# reading collected csv data
crypto_df = pd.read_csv("crypto_df.csv")
crypto_df.head()

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6906516.00,138429855767643,1,2.018402e+12,2.003664e+07,2.003664e+07,11187013.00,3993.420000,2026-06-01
1,ethereum,eth,Ethereum,187608.00,22647617493837,2,1.153910e+12,1.206852e+08,1.206852e+08,431946.00,28.130000,2026-06-01
2,tether,usdt,Tether,94.84,17852182065363,3,3.880867e+12,1.882392e+11,1.937062e+11,105.52,36.860000,2026-06-01
3,binancecoin,bnb,BNB,65237.00,8794692700692,4,2.014503e+11,1.347845e+08,1.347845e+08,121422.00,2.580000,2026-06-01
4,ripple,xrp,XRP,123.76,7667132462337,5,1.408457e+11,6.197784e+10,9.998566e+10,313.99,0.159343,2026-06-01

In [39]:
top_coins_df = pd.read_csv("top_coins_df.csv")
top_coins_df

      coin_id        date         price coin_name
0     bitcoin  2025-06-02  9.040802e+06   Bitcoin
1     bitcoin  2025-06-02  9.040802e+06   Bitcoin
2     bitcoin  2025-06-02  9.040802e+06   Bitcoin
3     bitcoin  2025-06-02  9.040802e+06   Bitcoin
4     bitcoin  2025-06-02  9.040802e+06   Bitcoin
...       ...         ...           ...       ...
9145   ripple  2026-06-01  1.238521e+02       XRP
9146   ripple  2026-06-01  1.238521e+02       XRP
9147   ripple  2026-06-01  1.238521e+02       XRP
9148   ripple  2026-06-01  1.238521e+02       XRP
9149   ripple  2026-06-01  1.238521e+02       XRP

[9150 rows x 4 columns]

In [40]:
oil_df = pd.read_csv("oil_df.csv")
oil_df.head()

         Date  Price
0  2020-01-02  61.17
1  2020-01-03  63.00
2  2020-01-06  63.27
3  2020-01-07  62.70
4  2020-01-08  59.65

In [41]:
stks_df = pd.read_csv("stks_df.csv")
stks_df.head()

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

# **SQL connection Table Creation**

In [42]:
import mysql.connector

In [43]:
conn = mysql.connector.connect(
    host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
    user = "3fXqCw6nxxduoS8.root",
    password = "u2dctQHUVuOXcZhS",
    port = 4000
)

In [44]:
cma = conn.cursor()

In [45]:
cma.execute("DROP DATABASE IF EXISTS Cross_Market_Analysis")
conn.commit()

In [46]:
cma.execute("CREATE DATABASE Cross_Market_Analysis")
conn.commit()

In [47]:
cma.execute("show databases")
cma.fetchall()

[('INFORMATION_SCHEMA',),
 ('Cross_Market_Analysis',),
 ('Global_Literacy',),
 ('PERFORMANCE_SCHEMA',),
 ('mysql',)]

In [48]:
cma.execute("use Cross_Market_Analysis")

In [49]:
# creating tables for cryptocurrencies

cma.execute("""CREATE TABLE cryptocurrencies
                 (id VARCHAR(50) PRIMARY KEY,
                 symbol VARCHAR(10),
                 name VARCHAR(100),
                 current_price DECIMAL(18, 6),
                 market_cap BIGINT,
                 market_cap_rank INT,
                 total_volume BIGINT,
                 circulating_supply DECIMAL(20, 6),
                 total_supply DECIMAL(20, 6),
                 ath DECIMAL(18, 6),
                 atl DECIMAL(18, 6),
                 date DATE
                 );

                 """)
conn.commit() # apply the changes to the sqlite3

In [50]:
#creating table for Crypto_prices

cma.execute("""CREATE TABLE top_coins
                 (coin_id VARCHAR(50),
                 date DATE,
                 coin_name VARCHAR(100),
                 price DECIMAL(18, 6)
                 );

                 """)
conn.commit()

In [51]:
#creating table for Oil_prices

cma.execute("""CREATE TABLE oil_prices
                 (date DATE PRIMARY KEY,
                 price_INR DECIMAL(18, 6)
                 );

                 """)
conn.commit()

In [52]:
#creating table for Stock_prices
cma.execute("""CREATE TABLE stk_prices
                 (date DATE,
                 open DECIMAL(18, 6),
                 high DECIMAL(18, 6),
                 low DECIMAL(18, 6),
                 close DECIMAL(18, 6),
                 volume BIGINT,
                 ticker VARCHAR(20)
                 );

                 """)
conn.commit()

In [53]:
cma.execute("show tables")
cma.fetchall()

[('cryptocurrencies',), ('oil_prices',), ('stk_prices',), ('top_coins',)]

# **Pushing data frames in to SQL and create sql engine**

In [54]:
from sqlalchemy import create_engine

In [55]:
engine = create_engine("mysql+mysqlconnector://3fXqCw6nxxduoS8.root:u2dctQHUVuOXcZhS@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/Cross_Market_Analysis")

In [56]:
crypto_df.to_sql ("cryptocurrencies", con = engine, if_exists = "replace", index = False) # push crypto_df to sqlite

1250

In [60]:
top_coins_df.to_sql ("top_coins", con = engine, if_exists = "replace", index = False)

9150

In [58]:
oil_df.to_sql ("oil_prices", con = engine, if_exists = "replace", index = False)

1535

In [59]:
stks_df.to_sql ("stks_prices", con = engine, if_exists = "replace", index = False)

4605

# **Querries where mentioned in project file**

### **Cryptocurrencies**

In [61]:
# show/read cryptocurrencies table
df = pd.read_sql("SELECT * FROM  cryptocurrencies;", engine)
df.head()

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6906516.00,138429855767643,1,2.018402e+12,2.003664e+07,2.003664e+07,11187013.00,3993.420000,2026-06-01
1,ethereum,eth,Ethereum,187608.00,22647617493837,2,1.153910e+12,1.206852e+08,1.206852e+08,431946.00,28.130000,2026-06-01
2,tether,usdt,Tether,94.84,17852182065363,3,3.880867e+12,1.882392e+11,1.937062e+11,105.52,36.860000,2026-06-01
3,binancecoin,bnb,BNB,65237.00,8794692700692,4,2.014503e+11,1.347845e+08,1.347845e+08,121422.00,2.580000,2026-06-01
4,ripple,xrp,XRP,123.76,7667132462337,5,1.408457e+11,6.197784e+10,9.998566e+10,313.99,0.159343,2026-06-01

In [62]:
# 1. Find the top 5 cryptocurrencies by market cap.
top_cryp = pd.read_sql (
    """SELECT coin_name, MAX(market_cap) AS market_cap FROM cryptocurrencies WHERE market_cap IS NOT NULL GROUP BY coin_name ORDER BY market_cap DESC LIMIT 5;""", engine)

top_cryp

  coin_name       market_cap
0   Bitcoin  138429855767643
1  Ethereum   22647617493837
2    Tether   17852182065363
3       BNB    8794692700692
4       XRP    7667132462337

In [63]:
# 2. List all coins where circulating supply exceeds 90% of total supply.

cir_sup = pd.read_sql (
    """SELECT * FROM cryptocurrencies WHERE total_supply IS NOT NULL AND total_supply > 0 AND circulating_supply >= 0.9 * total_supply AND circulating_supply IS NOT NULL;""", engine)

cir_sup

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6.906516e+06,138429855767643,1,2.018402e+12,2.003664e+07,2.003664e+07,1.118701e+07,3.993420e+03,2026-06-01
1,ethereum,eth,Ethereum,1.876080e+05,22647617493837,2,1.153910e+12,1.206852e+08,1.206852e+08,4.319460e+05,2.813000e+01,2026-06-01
2,tether,usdt,Tether,9.484000e+01,17852182065363,3,3.880867e+12,1.882392e+11,1.937062e+11,1.055200e+02,3.686000e+01,2026-06-01
3,binancecoin,bnb,BNB,6.523700e+04,8794692700692,4,2.014503e+11,1.347845e+08,1.347845e+08,1.214220e+05,2.580000e+00,2026-06-01
4,usd-coin,usdc,USDC,9.493000e+01,7202383175934,6,7.847426e+11,7.587217e+10,7.587945e+10,9.698000e+01,6.531000e+01,2026-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...
715,frax-usd,frxusd,Frax USD,9.491000e+01,12508745119,241,1.291401e+08,1.317817e+08,1.318830e+08,9.699000e+01,8.377000e+01,2026-06-01
716,agora-dollar,ausd,AUSD,9.493000e+01,12502501953,242,5.502046e+08,1.316842e+08,1.316842e+08,9.699000e+01,8.049000e+01,2026-06-01
717,golem,glm,Golem,1.244000e+01,12448617855,243,5.861124e+08,1.000000e+09,1.000000e+09,8.640000e+01,6.132050e-01,2026-06-01
718,newton-project,ab,AB,1.240920e-01,12264428765,246,2.500841e+08,9.882366e+10,9.882366e+10,1.490000e+00,3.137300e-04,2026-06-01
719,cheems-token,cheems,Cheems Token,5.872000e-05,11971589926,249,8.850849e+07,2.036730e+14,2.036730e+14,1.851700e-04,4.736520e-07,2026-06-01

In [64]:
# 3. Get coins that are within 10% of their all-time-high (ATH).

ath = pd.read_sql(""" SELECT * FROM cryptocurrencies WHERE current_price >= 0.9 * ath
AND current_price IS NOT NULL ORDER BY current_price DESC;
""", engine)

ath

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,ousg,ousg,OUSG,10962.43,51233862693,101,0.000000e+00,4.673956e+06,4.673956e+06,11182.59,7844.420000,2026-06-01
1,ousg,ousg,OUSG,10962.43,51233862693,101,0.000000e+00,4.673956e+06,4.673956e+06,11182.59,7844.420000,2026-06-01
2,ousg,ousg,OUSG,10962.43,51233862693,101,0.000000e+00,4.673956e+06,4.673956e+06,11182.59,7844.420000,2026-06-01
3,ousg,ousg,OUSG,10962.43,51233862693,101,0.000000e+00,4.673956e+06,4.673956e+06,11182.59,7844.420000,2026-06-01
4,ousg,ousg,OUSG,10962.43,51233862693,101,0.000000e+00,4.673956e+06,4.673956e+06,11182.59,7844.420000,2026-06-01
...,...,...,...,...,...,...,...,...,...,...,...,...
295,rain,rain,Rain,1.34,836815304270,15,4.845000e+09,6.226383e+11,1.149867e+12,1.42,0.196087,2026-06-01
296,rain,rain,Rain,1.34,836815304270,15,4.845000e+09,6.226383e+11,1.149867e+12,1.42,0.196087,2026-06-01
297,rain,rain,Rain,1.34,836815304270,15,4.845000e+09,6.226383e+11,1.149867e+12,1.42,0.196087,2026-06-01
298,rain,rain,Rain,1.34,836815304270,15,4.845000e+09,6.226383e+11,1.149867e+12,1.42,0.196087,2026-06-01
299,rain,rain,Rain,1.34,836660274974,15,4.843766e+09,6.226383e+11,1.149867e+12,1.42,0.196087,2026-06-01

In [65]:
# 4. Find the average market cap rank of coins with volume above $1B.

df = pd.read_sql ("""SELECT coin_id, AVG(market_cap_rank) FROM cryptocurrencies 
WHERE total_volume > 1000000000 AND total_volume IS NOT NULL GROUP BY coin_id;""", engine)

df

                     coin_id  AVG(market_cap_rank)
0                  chainlink                  19.0
1    world-liberty-financial                  48.0
2                 pi-network                  55.0
3               decentraland                 205.0
4                     solana                   7.0
..                       ...                   ...
134               eigenlayer                 212.0
135                     just                  83.0
136                  aster-2                  49.0
137               paypal-usd                  34.0
138              sei-network                 117.0

[139 rows x 2 columns]

In [66]:
# 5. Get the most recently updated coin.

df = pd.read_sql ("SELECT * FROM cryptocurrencies ORDER BY last_updated DESC LIMIT 1;", engine)

df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,6906516.0,138429855767643,1,2.018402e+12,20036643.0,20036643.0,11187013.0,3993.42,2026-06-01

### **Crypto_Prices (Daily Prices of Top Coins)**

In [67]:
df = pd.read_sql("SELECT * FROM  top_coins;", engine)
df

      coin_id        date         price coin_name
0     bitcoin  2025-06-02  9.040802e+06   Bitcoin
1     bitcoin  2025-06-02  9.040802e+06   Bitcoin
2     bitcoin  2025-06-02  9.040802e+06   Bitcoin
3     bitcoin  2025-06-02  9.040802e+06   Bitcoin
4     bitcoin  2025-06-02  9.040802e+06   Bitcoin
...       ...         ...           ...       ...
9145   ripple  2026-06-01  1.238521e+02       XRP
9146   ripple  2026-06-01  1.238521e+02       XRP
9147   ripple  2026-06-01  1.238521e+02       XRP
9148   ripple  2026-06-01  1.238521e+02       XRP
9149   ripple  2026-06-01  1.238521e+02       XRP

[9150 rows x 4 columns]

In [68]:
# 1. Find the highest daily price of Bitcoin in the last 365 days.

df = pd.read_sql(
    """SELECT coin_id, MAX(price) AS highest_daily_price FROM top_coins WHERE coin_id = 'bitcoin' AND DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);""", engine
)

df

   coin_id  highest_daily_price
0  bitcoin         1.107047e+07

In [69]:
# 2. Calculate the average daily price of Ethereum in the past 1 year.

df = pd.read_sql ("SELECT coin_id, AVG(price) as Avg_price FROM top_coins WHERE coin_id = 'ethereum' AND DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);", engine)

df

    coin_id      Avg_price
0  ethereum  270879.788089

In [70]:
# 3. Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)

df = pd.read_sql(
    """SELECT coin_id, price AS daily_price, date FROM top_coins WHERE coin_id = 'bitcoin' AND Date BETWEEN '2025-01-01' AND '2026-02-28' ORDER BY Date;""", engine)

df

      coin_id   daily_price        date
0     bitcoin  9.040802e+06  2025-06-02
1     bitcoin  9.040802e+06  2025-06-02
2     bitcoin  9.040802e+06  2025-06-02
3     bitcoin  9.040802e+06  2025-06-02
4     bitcoin  9.040802e+06  2025-06-02
...       ...           ...         ...
1355  bitcoin  6.000770e+06  2026-02-28
1356  bitcoin  6.000770e+06  2026-02-28
1357  bitcoin  6.000770e+06  2026-02-28
1358  bitcoin  6.000770e+06  2026-02-28
1359  bitcoin  6.000770e+06  2026-02-28

[1360 rows x 3 columns]

In [71]:
# 4. Find the coin with the highest average price over 1 year.

df = pd.read_sql (
    """SELECT coin_id, AVG(price) AS avg_price FROM top_coins WHERE DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY)
    GROUP BY coin_id ORDER BY avg_price DESC LIMIT 1;""",
    engine)

df

   coin_id     avg_price
0  bitcoin  8.425307e+06

In [72]:
# 5. Get the % change in Bitcoin’s price between Feb 2025 and Feb 2026.

df = pd.read_sql(
    """ SELECT coin_id,
        (
            (MAX(CASE WHEN DATE(date) BETWEEN '2026-02-01' AND '2026-02-28' THEN price END)
                -
                MAX(CASE WHEN DATE(date) BETWEEN '2025-02-01' AND '2025-02-28' THEN price END)
            )
            /
            MAX(CASE WHEN DATE(date) BETWEEN '2025-02-01' AND '2025-02-28' THEN price END)
        ) * 100 AS percentage_change
    FROM top_coins WHERE coin_id = 'bitcoin';""",
    engine
)

df

   coin_id percentage_change
0  bitcoin              None

### **Oil_Price**

In [73]:
df = pd.read_sql ("SELECT * FROM  oil_prices;", engine)
df.head()

         Date  Price
0  2020-01-02  61.17
1  2020-01-03  63.00
2  2020-01-06  63.27
3  2020-01-07  62.70
4  2020-01-08  59.65

In [74]:
# 1. Find the highest oil price in the last 5 years.

df = pd.read_sql(""" SELECT MAX(price) AS highest_price FROM oil_prices WHERE date >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);
""", engine)

df

   highest_price
0         123.64

In [75]:
# 2. Get the average oil price per year.

df = pd.read_sql("""SELECT YEAR(date) AS year, AVG(price) AS avg_price
FROM oil_prices GROUP BY YEAR(date) ORDER BY YEAR(date);""", engine)

df

   year  avg_price
0  2020  39.160437
1  2021  68.135100
2  2022  94.902869
3  2023  77.576532
4  2024  76.632240
5  2025  65.388105
6  2026  61.812000

In [76]:
# 3. Show oil prices during COVID crash (March–April 2020).

df = pd.read_sql("""SELECT date, price FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date;
""", engine)

df

          date  price
0   2020-03-02  46.78
1   2020-03-03  47.27
2   2020-03-04  46.78
3   2020-03-05  45.90
4   2020-03-06  41.14
5   2020-03-09  31.05
6   2020-03-10  34.47
7   2020-03-11  33.13
8   2020-03-12  31.56
9   2020-03-13  31.72
10  2020-03-16  28.96
11  2020-03-17  26.96
12  2020-03-18  20.48
13  2020-03-19  25.09
14  2020-03-20  19.48
15  2020-03-23  23.33
16  2020-03-24  21.03
17  2020-03-25  20.75
18  2020-03-26  16.60
19  2020-03-27  15.48
20  2020-03-30  14.10
21  2020-03-31  20.51
22  2020-04-01  20.28
23  2020-04-02  25.18
24  2020-04-03  28.36
25  2020-04-06  26.21
26  2020-04-07  23.54
27  2020-04-08  24.97
28  2020-04-09  22.90
29  2020-04-13  22.36
30  2020-04-14  20.15
31  2020-04-15  19.96
32  2020-04-16  19.82
33  2020-04-17  18.31
34  2020-04-20 -36.98
35  2020-04-21   8.91
36  2020-04-22  13.64
37  2020-04-23  15.06
38  2020-04-24  15.99
39  2020-04-27  12.17
40  2020-04-28  12.40
41  2020-04-29  15.04
42  2020-04-30  19.23

In [77]:
# 4. Find the lowest price of oil in the last 10 years.

df = pd.read_sql("""SELECT date, price FROM oil_prices
WHERE price = (SELECT MIN(price) FROM oil_prices WHERE date >= DATE_SUB(CURDATE(), INTERVAL 10 YEAR));
""", engine)

df

         date  price
0  2020-04-20 -36.98

In [78]:
# 5. Calculate the volatility of oil prices (max-min difference per year).

df = pd.read_sql("""SELECT YEAR(date) AS year, MAX(price) AS highest_price, MIN(price) AS lowest_price, MAX(price) - MIN(price) AS volatility
FROM oil_prices GROUP BY YEAR(date) ORDER BY YEAR(date);
""", engine)

df

   year  highest_price  lowest_price  volatility
0  2020          63.27        -36.98      100.25
1  2021          85.64         47.47       38.17
2  2022         123.64         71.05       52.59
3  2023          93.67         66.61       27.06
4  2024          87.69         66.73       20.96
5  2025          80.73         55.44       25.29
6  2026          66.69         56.01       10.68

### **Stock_Prices**

In [79]:
df = pd.read_sql("SELECT * FROM stks_prices;", engine)
df.head()

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [80]:
# 1. Get all stock prices for a given ticker

df = pd.read_sql(""" SELECT * FROM stks_prices WHERE Ticker IN ('^IXIC', '^NSEI', '^GSPC')
AND Open IS NOT NULL AND High IS NOT NULL
AND Low IS NOT NULL AND Close IS NOT NULL
AND Volume IS NOT NULL ORDER BY Date;
""", engine)

df

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-02,^GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
3,2020-01-02,^IXIC,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
4,2020-01-03,^IXIC,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
...,...,...,...,...,...,...,...
4600,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
4601,2026-02-19,^NSEI,25873.349609,25885.300781,25388.750000,25454.349609,2.982000e+05
4602,2026-02-20,^NSEI,25406.550781,25663.550781,25379.750000,25571.250000,2.966000e+05
4603,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09
4604,2026-02-20,^IXIC,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09

In [81]:
# 2. Find the highest closing price for NASDAQ (^IXIC)

df = pd.read_sql ("SELECT Ticker, MAX(close) AS highest_closing_price FROM stks_prices WHERE Ticker = '^IXIC';", engine)

df

  Ticker  highest_closing_price
0  ^IXIC           23958.470703

In [82]:
# 3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

df = pd.read_sql ("""SELECT Ticker, Date, high - low AS price_difference FROM stks_prices
WHERE Ticker = '^GSPC' ORDER BY price_difference DESC LIMIT 5
;""", engine)

df

  Ticker        Date  price_difference
0  ^GSPC  2025-04-09        532.909668
1  ^GSPC  2025-04-07        411.529785
2  ^GSPC  2025-04-08        357.050293
3  ^GSPC  2025-04-10        237.879883
4  ^GSPC  2025-11-20        236.300293

In [83]:
# 4. Get monthly average closing price for each ticker

df = pd.read_sql("""
SELECT Ticker,
       DATE_FORMAT(Date, '%Y-%m') AS month,
       AVG(Close) AS avg_closing_price
FROM stks_prices
WHERE Close IS NOT NULL AND Date IS NOT NULL
GROUP BY Ticker, month ORDER BY Ticker, month;
""", engine)

df

    Ticker    month  avg_closing_price
0    ^GSPC  2020-01        3278.202858
1    ^GSPC  2020-02        3277.314183
2    ^GSPC  2020-03        2652.393632
3    ^GSPC  2020-04        2761.975226
4    ^GSPC  2020-05        2919.608484
..     ...      ...                ...
217  ^NSEI  2025-10       25494.083519
218  ^NSEI  2025-11       25894.834396
219  ^NSEI  2025-12       25997.738725
220  ^NSEI  2026-01       25652.962695
221  ^NSEI  2026-02       25681.076693

[222 rows x 3 columns]

In [84]:
# 5. Get average trading volume of NSEI in 2024
df = pd.read_sql("""SELECT ticker, AVG(Volume) AS avg_trading_volume FROM stks_prices
WHERE Ticker = '^NSEI' AND YEAR(Date) = 2024;""", engine)

df

  ticker  avg_trading_volume
0  ^NSEI       313560.162602

### **Joint Querries**

In [85]:
# 1. Compare Bitcoin vs Oil average price in 2025.

df = pd.read_sql("""
SELECT
    DATE(c.date) AS date,
    c.price AS btc_close,
    o.price AS oil_close
FROM top_coins c
LEFT JOIN oil_prices o
    ON DATE(c.date) = DATE(o.date)
WHERE c.coin_id = 'bitcoin'
AND c.price IS NOT NULL
AND o.price IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_close  oil_close
0    2025-06-02  9.040802e+06      63.27
1    2025-06-02  9.040802e+06      63.27
2    2025-06-02  9.040802e+06      63.27
3    2025-06-02  9.040802e+06      63.27
4    2025-06-02  9.040802e+06      63.27
..          ...           ...        ...
900  2026-02-23  6.132044e+06      66.36
901  2026-02-23  6.132044e+06      66.36
902  2026-02-23  6.132044e+06      66.36
903  2026-02-23  6.132044e+06      66.36
904  2026-02-23  6.132044e+06      66.36

[905 rows x 3 columns]

In [86]:
# 2. Check if Bitcoin moves with S&P 500 (correlation idea).

df = pd.read_sql("""
SELECT
    DATE(t.date) AS date,
    t.price AS btc_close,
    s.Close AS stks_close
FROM top_coins t
LEFT JOIN stks_prices s
    ON DATE(t.date) = DATE(s.Date)
   AND s.Ticker = '^GSPC'
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_close   stks_close
0    2025-06-02  9.040802e+06  5935.939941
1    2025-06-02  9.040802e+06  5935.939941
2    2025-06-02  9.040802e+06  5935.939941
3    2025-06-02  9.040802e+06  5935.939941
4    2025-06-02  9.040802e+06  5935.939941
..          ...           ...          ...
905  2026-02-20  6.092367e+06  6909.509766
906  2026-02-20  6.092367e+06  6909.509766
907  2026-02-20  6.092367e+06  6909.509766
908  2026-02-20  6.092367e+06  6909.509766
909  2026-02-20  6.092367e+06  6909.509766

[910 rows x 3 columns]

In [87]:
# 3. Compare Ethereum and NASDAQ daily prices for 2025.

df = pd.read_sql("""
SELECT
    DATE(t.date) AS date,
    t.price AS eth_close,
    s.Close AS nasdaq_close
FROM top_coins t
JOIN stks_prices s
    ON DATE(t.date) = DATE(s.Date)
WHERE t.coin_id = 'ethereum'
AND s.Ticker = '^IXIC'
AND YEAR(t.date) = 2025
AND t.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date;
""", engine)


df

           date      eth_close  nasdaq_close
0    2025-06-02  217089.574074  19242.609375
1    2025-06-02  217089.574074  19242.609375
2    2025-06-02  217089.574074  19242.609375
3    2025-06-02  217089.574074  19242.609375
4    2025-06-02  217089.574074  19242.609375
..          ...            ...           ...
735  2025-12-31  266620.867155  23241.990234
736  2025-12-31  266620.867155  23241.990234
737  2025-12-31  266620.867155  23241.990234
738  2025-12-31  266620.867155  23241.990234
739  2025-12-31  266620.867155  23241.990234

[740 rows x 3 columns]

In [88]:
# 4. Find days when oil price spiked and compare with Bitcoin price change.

df = pd.read_sql ("""SELECT date(o.Date) AS date,
    o.Price AS oil_price,
    t.price AS btc_price
FROM oil_prices o
JOIN top_coins t
    ON date(o.Date) = date(t.Date)
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND o.price IS NOT NULL
ORDER BY date;
""", engine)

df

           date  oil_price     btc_price
0    2025-06-02      63.27  9.040802e+06
1    2025-06-02      63.27  9.040802e+06
2    2025-06-02      63.27  9.040802e+06
3    2025-06-02      63.27  9.040802e+06
4    2025-06-02      63.27  9.040802e+06
..          ...        ...           ...
900  2026-02-23      66.36  6.132044e+06
901  2026-02-23      66.36  6.132044e+06
902  2026-02-23      66.36  6.132044e+06
903  2026-02-23      66.36  6.132044e+06
904  2026-02-23      66.36  6.132044e+06

[905 rows x 3 columns]

In [89]:
# 5. Compare top 3 coins daily price trend vs Nifty (^NSEI).

df = pd.read_sql ("""
SELECT
    date(c.Date) AS date,
    c.coin_id AS coins,
    c.price AS coin_prices,
    s.Close AS nifty_close
FROM top_coins c
JOIN stks_prices s
    ON date(c.Date) = date(s.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND s.Ticker = '^NSEI'
  AND c.price IS NOT NULL
  AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

            date        coins   coin_prices   nifty_close
0     2025-06-02  binancecoin  56561.262781  24716.599609
1     2025-06-02  binancecoin  56561.262781  24716.599609
2     2025-06-02  binancecoin  56561.262781  24716.599609
3     2025-06-02  binancecoin  56561.262781  24716.599609
4     2025-06-02  binancecoin  56561.262781  24716.599609
...          ...          ...           ...           ...
2725  2026-02-20  binancecoin  55275.307622  25571.250000
2726  2026-02-20  binancecoin  55275.307622  25571.250000
2727  2026-02-20  binancecoin  55275.307622  25571.250000
2728  2026-02-20  binancecoin  55275.307622  25571.250000
2729  2026-02-20  binancecoin  55275.307622  25571.250000

[2730 rows x 4 columns]

In [90]:
# 6. Compare stock prices (^GSPC) with crude oil prices on the same dates


df = pd.read_sql("""
SELECT
    date(s.Date) AS date,
    s.Close AS nifty_close,
    o.Price AS oil_price
FROM stks_prices s
JOIN oil_prices o
    ON date(s.Date) = date(o.Date)
WHERE s.Ticker = '^GSPC'
AND s.Close IS NOT NULL
AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

            date  nifty_close  oil_price
0     2020-01-02  3257.850098      61.17
1     2020-01-03  3234.850098      63.00
2     2020-01-06  3246.280029      63.27
3     2020-01-07  3237.179932      62.70
4     2020-01-08  3253.050049      59.65
...          ...          ...        ...
1529  2026-02-13  6836.169922      63.05
1530  2026-02-17  6843.220215      62.53
1531  2026-02-18  6881.310059      65.33
1532  2026-02-19  6861.890137      66.66
1533  2026-02-20  6909.509766      66.69

[1534 rows x 3 columns]

In [91]:
# 7. Correlate Bitcoin closing price with crude oil closing price (same date)

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    o.Price AS oil_price
FROM top_coins t
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_price  oil_price
0    2025-06-02  9.040802e+06      63.27
1    2025-06-02  9.040802e+06      63.27
2    2025-06-02  9.040802e+06      63.27
3    2025-06-02  9.040802e+06      63.27
4    2025-06-02  9.040802e+06      63.27
..          ...           ...        ...
900  2026-02-23  6.132044e+06      66.36
901  2026-02-23  6.132044e+06      66.36
902  2026-02-23  6.132044e+06      66.36
903  2026-02-23  6.132044e+06      66.36
904  2026-02-23  6.132044e+06      66.36

[905 rows x 3 columns]

In [92]:
# 8. Compare NASDAQ (^IXIC) with Ethereum price trends

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS eth_price,
    s.Close AS ixic_close
FROM top_coins t
JOIN stks_prices s
    ON date(t.Date) = date(s.Date)
WHERE t.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
  AND t.price IS NOT NULL
  AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

           date      eth_price    ixic_close
0    2025-06-02  217089.574074  19242.609375
1    2025-06-02  217089.574074  19242.609375
2    2025-06-02  217089.574074  19242.609375
3    2025-06-02  217089.574074  19242.609375
4    2025-06-02  217089.574074  19242.609375
..          ...            ...           ...
905  2026-02-20  177249.247482  22886.070312
906  2026-02-20  177249.247482  22886.070312
907  2026-02-20  177249.247482  22886.070312
908  2026-02-20  177249.247482  22886.070312
909  2026-02-20  177249.247482  22886.070312

[910 rows x 3 columns]

In [93]:
# 9. Join top 3 crypto coins with stock indices for 2025
df = pd.read_sql("""
SELECT
    DATE(c.Date) AS date,
    c.coin_id AS crypto_coin,
    c.price AS crypto_price,
    s.Ticker AS stock_index,
    s.Close AS stock_close
FROM top_coins c
JOIN stks_prices s
    ON DATE(c.Date) = DATE(s.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
AND YEAR(c.Date) = 2025
AND c.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date, crypto_coin;
""", engine)

df

            date  crypto_coin   crypto_price stock_index   stock_close
0     2025-06-02  binancecoin   56561.262781       ^GSPC   5935.939941
1     2025-06-02  binancecoin   56561.262781       ^IXIC  19242.609375
2     2025-06-02  binancecoin   56561.262781       ^NSEI  24716.599609
3     2025-06-02  binancecoin   56561.262781       ^GSPC   5935.939941
4     2025-06-02  binancecoin   56561.262781       ^IXIC  19242.609375
...          ...          ...            ...         ...           ...
6640  2025-12-31     ethereum  266620.867155       ^GSPC   6845.500000
6641  2025-12-31     ethereum  266620.867155       ^IXIC  23241.990234
6642  2025-12-31     ethereum  266620.867155       ^NSEI  26129.599609
6643  2025-12-31     ethereum  266620.867155       ^GSPC   6845.500000
6644  2025-12-31     ethereum  266620.867155       ^IXIC  23241.990234

[6645 rows x 5 columns]

In [94]:
# 10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    s.Close AS stk_close,
    o.Price AS oil_price
FROM top_coins t
JOIN stks_prices s
    ON date(t.Date) = date(s.Date)
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
  AND t.price IS NOT NULL
  AND s.Close IS NOT NULL
  AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_price    stk_close  oil_price
0    2025-06-02  9.040802e+06  5935.939941      63.27
1    2025-06-02  9.040802e+06  5935.939941      63.27
2    2025-06-02  9.040802e+06  5935.939941      63.27
3    2025-06-02  9.040802e+06  5935.939941      63.27
4    2025-06-02  9.040802e+06  5935.939941      63.27
..          ...           ...          ...        ...
895  2026-02-20  6.092367e+06  6909.509766      66.69
896  2026-02-20  6.092367e+06  6909.509766      66.69
897  2026-02-20  6.092367e+06  6909.509766      66.69
898  2026-02-20  6.092367e+06  6909.509766      66.69
899  2026-02-20  6.092367e+06  6909.509766      66.69

[900 rows x 4 columns]

In [5]:
import pandas as pd
df = pd.read_csv("top_coins_df.csv")
df

      coin_id        date         price coin_name
0     bitcoin  2025-06-02  9.040802e+06   Bitcoin
1     bitcoin  2025-06-02  9.040802e+06   Bitcoin
2     bitcoin  2025-06-02  9.040802e+06   Bitcoin
3     bitcoin  2025-06-02  9.040802e+06   Bitcoin
4     bitcoin  2025-06-02  9.040802e+06   Bitcoin
...       ...         ...           ...       ...
9145   ripple  2026-06-01  1.238521e+02       XRP
9146   ripple  2026-06-01  1.238521e+02       XRP
9147   ripple  2026-06-01  1.238521e+02       XRP
9148   ripple  2026-06-01  1.238521e+02       XRP
9149   ripple  2026-06-01  1.238521e+02       XRP

[9150 rows x 4 columns]

In [6]:
df["date"] = pd.to_datetime(df["date"])
df

      coin_id       date         price coin_name
0     bitcoin 2025-06-02  9.040802e+06   Bitcoin
1     bitcoin 2025-06-02  9.040802e+06   Bitcoin
2     bitcoin 2025-06-02  9.040802e+06   Bitcoin
3     bitcoin 2025-06-02  9.040802e+06   Bitcoin
4     bitcoin 2025-06-02  9.040802e+06   Bitcoin
...       ...        ...           ...       ...
9145   ripple 2026-06-01  1.238521e+02       XRP
9146   ripple 2026-06-01  1.238521e+02       XRP
9147   ripple 2026-06-01  1.238521e+02       XRP
9148   ripple 2026-06-01  1.238521e+02       XRP
9149   ripple 2026-06-01  1.238521e+02       XRP

[9150 rows x 4 columns]

In [9]:
filtered_df = df[
    (df["date"] >= "2025-06-01") &
    (df["date"] <= "2025-06-30")
]

filtered_df

      coin_id       date         price coin_name
0     bitcoin 2025-06-02  9.040802e+06   Bitcoin
1     bitcoin 2025-06-02  9.040802e+06   Bitcoin
2     bitcoin 2025-06-02  9.040802e+06   Bitcoin
3     bitcoin 2025-06-02  9.040802e+06   Bitcoin
4     bitcoin 2025-06-02  9.040802e+06   Bitcoin
...       ...        ...           ...       ...
7460   ripple 2025-06-30  1.886925e+02       XRP
7461   ripple 2025-06-30  1.886925e+02       XRP
7462   ripple 2025-06-30  1.886925e+02       XRP
7463   ripple 2025-06-30  1.886925e+02       XRP
7464   ripple 2025-06-30  1.886925e+02       XRP

[725 rows x 4 columns]