# **Cryptocurrency (CoinGecko API)**
## **Data Collection**

In [1]:
# Data collection from url
data_crypto = []

import requests
import time # avoiding limiting

for page_num in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
  response = requests.get(url)
  if response.status_code == 200:
    data_crypto.extend(response.json()) # Extend the list with data from current page
    print(f"Collected data from page {page_num}")
  else:
    print(f"Error collecting data from page {page_num}: {response.status_code}")
    page_num += 1
  time.sleep(5) # Increased wait time to 1 second to avoid rate limiting

print ("==========================================")
print(f"Total data collected: {len(data_crypto)}")

Collected data from page 1
Collected data from page 2
Collected data from page 3
Error collecting data from page 4: 429
Error collecting data from page 5: 429
==========================================
Total data collected: 750

In [2]:
data_crypto

[{'id': 'bitcoin',
  'symbol': 'btc',
  'name': 'Bitcoin',
  'image': 'https://coin-images.coingecko.com/coins/images/1/large/bitcoin.png?1696501400',
  'current_price': 5834975,
  'market_cap': 116669385858811,
  'market_cap_rank': 1,
  'fully_diluted_valuation': 116669531737257,
  'total_volume': 4013569758743,
  'high_24h': 5910149,
  'low_24h': 5711311,
  'price_change_24h': -66161.32160911616,
  'price_change_percentage_24h': -1.12116,
  'market_cap_change_24h': -1303470832658.1875,
  'market_cap_change_percentage_24h': -1.10489,
  'circulating_supply': 19994281.0,
  'total_supply': 19994306.0,
  'max_supply': 21000000.0,
  'ath': 11187013,
  'ath_change_percentage': -47.84153,
  'ath_date': '2025-10-06T18:57:42.558Z',
  'atl': 3993.42,
  'atl_change_percentage': 146014.76698,
  'atl_date': '2013-07-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:32.395Z'},
 {'id': 'ethereum',
  'symbol': 'eth',
  'name': 'Ethereum',
  'image': 'https://coin-images.coingecko.com/coins/images/279/large/ethereum.png?1696501628',
  'current_price': 168908,
  'market_cap': 20384091282971,
  'market_cap_rank': 2,
  'fully_diluted_valuation': 20384091282971,
  'total_volume': 1726953738156,
  'high_24h': 169899,
  'low_24h': 164372,
  'price_change_24h': -483.76316355221206,
  'price_change_percentage_24h': -0.28559,
  'market_cap_change_24h': -52773979042.72266,
  'market_cap_change_percentage_24h': -0.25823,
  'circulating_supply': 120692340.095627,
  'total_supply': 120692340.095627,
  'max_supply': None,
  'ath': 431946,
  'ath_change_percentage': -60.89605,
  'ath_date': '2025-08-24T19:21:03.333Z',
  'atl': 28.13,
  'atl_change_percentage': 600327.86894,
  'atl_date': '2015-10-20T00:00:00.000Z',
  'roi': {'times': 37.69627952582063,
   'currency': 'btc',
   'percentage': 3769.627952582063},
  'last_updated': '2026-02-24T23:31:32.498Z'},
 {'id': 'tether',
  'symbol': 'usdt',
  'name': 'Tether',
  'image': 'https://coin-images.coingecko.com/coins/images/325/large/Tether.png?1696501661',
  'current_price': 90.92,
  'market_cap': 16695272786059,
  'market_cap_rank': 3,
  'fully_diluted_valuation': 17192331399773,
  'total_volume': 6351256229938,
  'high_24h': 91.01,
  'low_24h': 90.85,
  'price_change_24h': -0.08670490301294365,
  'price_change_percentage_24h': -0.09527,
  'market_cap_change_24h': -15630714733.882812,
  'market_cap_change_percentage_24h': -0.09354,
  'circulating_supply': 183624238441.843,
  'total_supply': 189091175734.4462,
  'max_supply': None,
  'ath': 105.52,
  'ath_change_percentage': -13.82697,
  'ath_date': '2025-01-25T16:51:57.989Z',
  'atl': 36.86,
  'atl_change_percentage': 146.68938,
  'atl_date': '2015-03-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.884Z'},
 {'id': 'ripple',
  'symbol': 'xrp',
  'name': 'XRP',
  'image': 'https://coin-images.coingecko.com/coins/images/44/large/xrp-symbol-white-128.png?1696501442',
  'current_price': 122.68,
  'market_cap': 7482710244321,
  'market_cap_rank': 4,
  'fully_diluted_valuation': 12261250082237,
  'total_volume': 249245774223,
  'high_24h': 123.85,
  'low_24h': 120.06,
  'price_change_24h': -0.7380744550885368,
  'price_change_percentage_24h': -0.59804,
  'market_cap_change_24h': -48851393324.4707,
  'market_cap_change_percentage_24h': -0.64862,
  'circulating_supply': 61018583977.0,
  'total_supply': 99985712847.0,
  'max_supply': 100000000000.0,
  'ath': 313.99,
  'ath_change_percentage': -60.9294,
  'ath_date': '2025-07-21T15:02:00.541Z',
  'atl': 0.159343,
  'atl_change_percentage': 76889.06223,
  'atl_date': '2013-08-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.706Z'},
 {'id': 'binancecoin',
  'symbol': 'bnb',
  'name': 'BNB',
  'image': 'https://coin-images.coingecko.com/coins/images/825/large/bnb-icon2_2x.png?1696501970',
  'current_price': 53191,
  'market_cap': 7251751308346,
  'market_cap_rank': 5,
  'fully_diluted_valuation': 7251751308346,
  'total_volume': 112841387164,
  'high_24h': 54800,
  'low_24h': 52547,
  'price_change_24h': -1224.5664480716805,
  'price_change_percentage_24h': -2.25039,
  'market_cap_change_24h': -166927182146.15527,
  'market_cap_change_percentage_24h': -2.25009,
  'circulating_supply': 136358948.75,
  'total_supply': 136358948.75,
  'max_supply': 200000000.0,
  'ath': 121422,
  'ath_change_percentage': -56.1931,
  'ath_date': '2025-10-13T08:41:24.131Z',
  'atl': 2.58,
  'atl_change_percentage': 2057796.05043,
  'atl_date': '2017-10-19T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:32.262Z'},
 {'id': 'usd-coin',
  'symbol': 'usdc',
  'name': 'USDC',
  'image': 'https://coin-images.coingecko.com/coins/images/6319/large/USDC.png?1769615602',
  'current_price': 90.92,
  'market_cap': 6812774704845,
  'market_cap_rank': 6,
  'fully_diluted_valuation': 6813160836678,
  'total_volume': 1060126342980,
  'high_24h': 91.02,
  'low_24h': 90.85,
  'price_change_24h': -0.09547833002910977,
  'price_change_percentage_24h': -0.1049,
  'market_cap_change_24h': 6639574675,
  'market_cap_change_percentage_24h': 0.09755,
  'circulating_supply': 74933243473.90916,
  'total_supply': 74937490511.55618,
  'max_supply': None,
  'ath': 1327.87,
  'ath_change_percentage': -93.15309,
  'ath_date': '2025-01-23T04:45:51.184Z',
  'atl': 65.31,
  'atl_change_percentage': 39.21477,
  'atl_date': '2021-05-19T13:14:05.611Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.893Z'},
 {'id': 'solana',
  'symbol': 'sol',
  'name': 'Solana',
  'image': 'https://coin-images.coingecko.com/coins/images/4128/large/solana.png?1718769756',
  'current_price': 7209.99,
  'market_cap': 4096262117067,
  'market_cap_rank': 7,
  'fully_diluted_valuation': 4473687784805,
  'total_volume': 353584884953,
  'high_24h': 7207.71,
  'low_24h': 6919.99,
  'price_change_24h': 95.74,
  'price_change_percentage_24h': 1.34568,
  'market_cap_change_24h': 47496271864,
  'market_cap_change_percentage_24h': 1.1731,
  'circulating_supply': 568666665.5179197,
  'total_supply': 621063067.3641098,
  'max_supply': None,
  'ath': 25396,
  'ath_change_percentage': -71.6101,
  'ath_date': '2025-01-19T11:15:27.957Z',
  'atl': 38.03,
  'atl_change_percentage': 18860.83508,
  'atl_date': '2020-05-11T19:35:23.449Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.730Z'},
 {'id': 'tron',
  'symbol': 'trx',
  'name': 'TRON',
  'image': 'https://coin-images.coingecko.com/coins/images/1094/large/tron-logo.png?1696502193',
  'current_price': 25.75,
  'market_cap': 2439935100873,
  'market_cap_rank': 8,
  'fully_diluted_valuation': 2439942739899,
  'total_volume': 46393745868,
  'high_24h': 25.78,
  'low_24h': 25.47,
  'price_change_24h': 0.147894,
  'price_change_percentage_24h': 0.57755,
  'market_cap_change_24h': 13577001162,
  'market_cap_change_percentage_24h': 0.55956,
  'circulating_supply': 94736335071.3254,
  'total_supply': 94736631674.8172,
  'max_supply': None,
  'ath': 36.53,
  'ath_change_percentage': -29.48773,
  'ath_date': '2024-12-04T00:10:40.323Z',
  'atl': 0.117589,
  'atl_change_percentage': 21802.45321,
  'atl_date': '2017-11-12T00:00:00.000Z',
  'roi': {'times': 148.0927698302959,
   'currency': 'usd',
   'percentage': 14809.27698302959},
  'last_updated': '2026-02-24T23:31:41.750Z'},
 {'id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'name': 'Figure Heloc',
  'image': 'https://coin-images.coingecko.com/coins/images/68480/large/figure.png?1755863954',
  'current_price': 94.0,
  'market_cap': 1445413957343,
  'market_cap_rank': 9,
  'fully_diluted_valuation': 1445413957343,
  'total_volume': 2806432457,
  'high_24h': 94.14,
  'low_24h': 93.51,
  'price_change_24h': 0.122303,
  'price_change_percentage_24h': 0.13028,
  'market_cap_change_24h': 16253946784,
  'market_cap_change_percentage_24h': 1.13731,
  'circulating_supply': 15376945530.577,
  'total_supply': 15376945530.577,
  'max_supply': None,
  'ath': 120.96,
  'ath_change_percentage': -22.29161,
  'ath_date': '2025-10-28T06:00:43.161Z',
  'atl': 13.78,
  'atl_change_percentage': 581.89799,
  'atl_date': '2025-10-31T14:57:19.271Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.418Z'},
 {'id': 'dogecoin',
  'symbol': 'doge',
  'name': 'Dogecoin',
  'image': 'https://coin-images.coingecko.com/coins/images/5/large/dogecoin.png?1696501409',
  'current_price': 8.33,
  'market_cap': 1405507433047,
  'market_cap_rank': 10,
  'fully_diluted_valuation': 1405901702895,
  'total_volume': 77382886538,
  'high_24h': 8.49,
  'low_24h': 8.22,
  'price_change_24h': -0.13828421752453401,
  'price_change_percentage_24h': -1.6334,
  'market_cap_change_24h': -25755371457.62915,
  'market_cap_change_percentage_24h': -1.79949,
  'circulating_supply': 168830643126.5791,
  'total_supply': 168878003126.5791,
  'max_supply': None,
  'ath': 53.62,
  'ath_change_percentage': -84.46832,
  'ath_date': '2021-05-08T05:08:23.458Z',
  'atl': 0.00552883,
  'atl_change_percentage': 150523.70749,
  'atl_date': '2015-05-06T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.713Z'},
 {'id': 'whitebit',
  'symbol': 'wbt',
  'name': 'WhiteBIT Coin',
  'image': 'https://coin-images.coingecko.com/coins/images/27045/large/wbt_token.png?1696526096',
  'current_price': 4375.48,
  'market_cap': 934359837977,
  'market_cap_rank': 11,
  'fully_diluted_valuation': 1400348098095,
  'total_volume': 6842771891,
  'high_24h': 4415.02,
  'low_24h': 4285.83,
  'price_change_24h': -32.61975873697429,
  'price_change_percentage_24h': -0.74,
  'market_cap_change_24h': -7017131679.901978,
  'market_cap_change_percentage_24h': -0.74541,
  'circulating_supply': 213544699.0,
  'total_supply': 320044699.0,
  'max_supply': 400000000.0,
  'ath': 5758.63,
  'ath_change_percentage': -24.15772,
  'ath_date': '2025-12-10T20:16:13.582Z',
  'atl': 245.71,
  'atl_change_percentage': 1677.50988,
  'atl_date': '2022-09-21T23:38:03.675Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.902Z'},
 {'id': 'usds',
  'symbol': 'usds',
  'name': 'USDS',
  'image': 'https://coin-images.coingecko.com/coins/images/39926/large/usds.webp?1726666683',
  'current_price': 90.92,
  'market_cap': 900593150847,
  'market_cap_rank': 12,
  'fully_diluted_valuation': 900593150847,
  'total_volume': 1515917426,
  'high_24h': 91.02,
  'low_24h': 90.85,
  'price_change_24h': -0.09994065294684162,
  'price_change_percentage_24h': -0.10981,
  'market_cap_change_24h': 1002781025,
  'market_cap_change_percentage_24h': 0.11147,
  'circulating_supply': 9905926780.82061,
  'total_supply': 9905926780.82061,
  'max_supply': None,
  'ath': 92.23,
  'ath_change_percentage': -1.41999,
  'ath_date': '2026-01-29T16:30:24.390Z',
  'atl': 79.67,
  'atl_change_percentage': 14.1205,
  'atl_date': '2024-10-03T13:19:28.826Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.821Z'},
 {'id': 'bitcoin-cash',
  'symbol': 'bch',
  'name': 'Bitcoin Cash',
  'image': 'https://coin-images.coingecko.com/coins/images/780/large/bitcoin-cash-circle.png?1696501932',
  'current_price': 44074,
  'market_cap': 881118363568,
  'market_cap_rank': 13,
  'fully_diluted_valuation': 881130341524,
  'total_volume': 39994011477,
  'high_24h': 45542,
  'low_24h': 42890,
  'price_change_24h': -1457.4871421086718,
  'price_change_percentage_24h': -3.20108,
  'market_cap_change_24h': -30436790236.4635,
  'market_cap_change_percentage_24h': -3.339,
  'circulating_supply': 19999578.02165078,
  'total_supply': 19999849.89665078,
  'max_supply': 21000000.0,
  'ath': 242198,
  'ath_change_percentage': -81.80264,
  'ath_date': '2017-12-20T00:00:00.000Z',
  'atl': 5536.54,
  'atl_change_percentage': 696.05043,
  'atl_date': '2018-12-16T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.722Z'},
 {'id': 'cardano',
  'symbol': 'ada',
  'name': 'Cardano',
  'image': 'https://coin-images.coingecko.com/coins/images/975/large/cardano.png?1696502090',
  'current_price': 23.56,
  'market_cap': 866663543763,
  'market_cap_rank': 14,
  'fully_diluted_valuation': 1059393781248,
  'total_volume': 33643333347,
  'high_24h': 24.04,
  'low_24h': 23.16,
  'price_change_24h': -0.4216215418478235,
  'price_change_percentage_24h': -1.75828,
  'market_cap_change_24h': -16256303264.16919,
  'market_cap_change_percentage_24h': -1.8412,
  'circulating_supply': 36813373987.7429,
  'total_supply': 45000000000.0,
  'max_supply': 45000000000.0,
  'ath': 225.26,
  'ath_change_percentage': -89.54209,
  'ath_date': '2021-09-02T06:00:10.474Z',
  'atl': 1.38,
  'atl_change_percentage': 1612.76958,
  'atl_date': '2017-11-02T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.894Z'},
 {'id': 'leo-token',
  'symbol': 'leo',
  'name': 'LEO Token',
  'image': 'https://coin-images.coingecko.com/coins/images/8418/large/leo-token.png?1696508607',
  'current_price': 775.22,
  'market_cap': 713292779632,
  'market_cap_rank': 15,
  'fully_diluted_valuation': 762792995817,
  'total_volume': 697823421,
  'high_24h': 777.96,
  'low_24h': 702.75,
  'price_change_24h': 41.37,
  'price_change_percentage_24h': 5.63679,
  'market_cap_change_24h': 37189255687,
  'market_cap_change_percentage_24h': 5.50053,
  'circulating_supply': 921303981.9,
  'total_supply': 985239504.0,
  'max_supply': None,
  'ath': 888.26,
  'ath_change_percentage': -12.93288,
  'ath_date': '2025-12-01T06:16:28.002Z',
  'atl': 56.97,
  'atl_change_percentage': 1257.43694,
  'atl_date': '2019-12-24T15:14:35.376Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.469Z'},
 {'id': 'hyperliquid',
  'symbol': 'hype',
  'name': 'Hyperliquid',
  'image': 'https://coin-images.coingecko.com/coins/images/50882/large/hyperliquid.jpg?1729431300',
  'current_price': 2488.23,
  'market_cap': 591945934971,
  'market_cap_rank': 16,
  'fully_diluted_valuation': 2389468485035,
  'total_volume': 18607619772,
  'high_24h': 2483.14,
  'low_24h': 2345.83,
  'price_change_24h': 89.41,
  'price_change_percentage_24h': 3.72712,
  'market_cap_change_24h': 20202558210,
  'market_cap_change_percentage_24h': 3.5335,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'max_supply': 1000000000.0,
  'ath': 5213.52,
  'ath_change_percentage': -52.27354,
  'ath_date': '2025-09-18T03:30:30.650Z',
  'atl': 321.88,
  'atl_change_percentage': 673.03206,
  'atl_date': '2024-11-29T09:30:30.871Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.561Z'},
 {'id': 'ethena-usde',
  'symbol': 'usde',
  'name': 'Ethena USDe',
  'image': 'https://coin-images.coingecko.com/coins/images/33613/large/usde.png?1733810059',
  'current_price': 90.85,
  'market_cap': 552962794184,
  'market_cap_rank': 17,
  'fully_diluted_valuation': 552962794184,
  'total_volume': 9155268263,
  'high_24h': 90.98,
  'low_24h': 90.74,
  'price_change_24h': -0.08989969566070499,
  'price_change_percentage_24h': -0.09885,
  'market_cap_change_24h': -3253873039.519409,
  'market_cap_change_percentage_24h': -0.585,
  'circulating_supply': 6086729545.055552,
  'total_supply': 6086729545.055552,
  'max_supply': None,
  'ath': 92.91,
  'ath_change_percentage': -2.26948,
  'ath_date': '2025-12-09T17:10:12.652Z',
  'atl': 78.05,
  'atl_change_percentage': 16.34877,
  'atl_date': '2024-10-04T07:57:15.809Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.602Z'},
 {'id': 'canton-network',
  'symbol': 'cc',
  'name': 'Canton',
  'image': 'https://coin-images.coingecko.com/coins/images/70468/large/Canton-Ticker_%281%29.png?1762826299',
  'current_price': 14.57,
  'market_cap': 550752282884,
  'market_cap_rank': 18,
  'fully_diluted_valuation': 550752282884,
  'total_volume': 688733752,
  'high_24h': 14.82,
  'low_24h': 14.45,
  'price_change_24h': -0.16414401883607432,
  'price_change_percentage_24h': -1.11412,
  'market_cap_change_24h': -6401100013.745117,
  'market_cap_change_percentage_24h': -1.14889,
  'circulating_supply': 37823997066.04275,
  'total_supply': 37823997066.04275,
  'max_supply': None,
  'ath': 17.72,
  'ath_change_percentage': -17.99765,
  'ath_date': '2026-01-31T16:41:41.560Z',
  'atl': 5.31,
  'atl_change_percentage': 173.75899,
  'atl_date': '2025-12-06T10:32:09.784Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.772Z'},
 {'id': 'monero',
  'symbol': 'xmr',
  'name': 'Monero',
  'image': 'https://coin-images.coingecko.com/coins/images/69/large/monero_logo.png?1696501460',
  'current_price': 29399,
  'market_cap': 542502634043,
  'market_cap_rank': 19,
  'fully_diluted_valuation': 542502634043,
  'total_volume': 8439859566,
  'high_24h': 29883,
  'low_24h': 27658,
  'price_change_24h': 1474.28,
  'price_change_percentage_24h': 5.27956,
  'market_cap_change_24h': 26772133670,
  'market_cap_change_percentage_24h': 5.19111,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'max_supply': None,
  'ath': 72026,
  'ath_change_percentage': -59.18316,
  'ath_date': '2026-01-14T19:34:07.049Z',
  'atl': 13.57,
  'atl_change_percentage': 216530.7128,
  'atl_date': '2015-01-14T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.578Z'},
 {'id': 'chainlink',
  'symbol': 'link',
  'name': 'Chainlink',
  'image': 'https://coin-images.coingecko.com/coins/images/877/large/Chainlink_Logo_500.png?1760023405',
  'current_price': 746.83,
  'market_cap': 528614773491,
  'market_cap_rank': 20,
  'fully_diluted_valuation': 746525625686,
  'total_volume': 26846196265,
  'high_24h': 757.55,
  'low_24h': 735.01,
  'price_change_24h': -9.14326227901006,
  'price_change_percentage_24h': -1.20948,
  'market_cap_change_24h': -6927829889.00116,
  'market_cap_change_percentage_24h': -1.29361,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'max_supply': 1000000000.0,
  'ath': 3862.15,
  'ath_change_percentage': -80.66296,
  'ath_date': '2021-05-10T00:13:57.214Z',
  'atl': 9.55,
  'atl_change_percentage': 7722.90003,
  'atl_date': '2017-11-29T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:41.931Z'},
 {'id': 'stellar',
  'symbol': 'xlm',
  'name': 'Stellar',
  'image': 'https://coin-images.coingecko.com/coins/images/100/large/fmpFRHHQ_400x400.jpg?1735231350',
  'current_price': 13.66,
  'market_cap': 448652924490,
  'market_cap_rank': 21,
  'fully_diluted_valuation': 682742604068,
  'total_volume': 7643255894,
  'high_24h': 13.85,
  'low_24h': 13.49,
  'price_change_24h': -0.15381524020190973,
  'price_change_percentage_24h': -1.11383,
  'market_cap_change_24h': -5248908560.549438,
  'market_cap_change_percentage_24h': -1.1564,
  'circulating_supply': 32857840980.49057,
  'total_supply': 50001786883.65895,
  'max_supply': None,
  'ath': 58.01,
  'ath_change_percentage': -76.50623,
  'ath_date': '2021-05-16T09:48:45.220Z',
  'atl': 0.02966141,
  'atl_change_percentage': 45845.43323,
  'atl_date': '2015-03-05T00:00:00.000Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:42.319Z'},
 {'id': 'usd1-wlfi',
  'symbol': 'usd1',
  'name': 'USD1',
  'image': 'https://coin-images.coingecko.com/coins/images/54977/large/USD1_1000x1000_transparent.png?1749297002',
  'current_price': 90.92,
  'market_cap': 424958517133,
  'market_cap_rank': 22,
  'fully_diluted_valuation': 424958517133,
  'total_volume': 184224417172,
  'high_24h': 91.01,
  'low_24h': 90.78,
  'price_change_24h': -0.011037067286508773,
  'price_change_percentage_24h': -0.01214,
  'market_cap_change_24h': -8888783977.910217,
  'market_cap_change_percentage_24h': -2.04883,
  'circulating_supply': 4674772575.644544,
  'total_supply': 4674772575.644544,
  'max_supply': None,
  'ath': 92.17,
  'ath_change_percentage': -1.36298,
  'ath_date': '2026-01-28T15:56:38.616Z',
  'atl': 83.75,
  'atl_change_percentage': 8.55189,
  'atl_date': '2025-05-02T03:46:49.689Z',
  'roi': None,
  'last_updated': '2026-02-24T23:31:42.391Z'},
 {'id': 'rain',
  'symbol': 'rain',
  'name': 'Rain',
  'image': 'https://coin-images.coingecko.com/coins/images/69134/large/Rain_logo_1_.png?1762952191',
  'current_price': 0.854032,
  'market_cap': 408003926879,
  'market_cap_rank': 23,

In [3]:
print(f"Total Data of Cryptocurrencies: {len(data_crypto)}")

Total Data of Cryptocurrencies: 750

In [4]:
# following columns for ectracting from collected data
# id, symbol, name, current_price, market_cap, market_cap_rank, total_volume, circulating_supply, total_supply, ath, atl, last_updated(just extract date).

filtered_columns = []

for i in data_crypto:
  filtered_columns.append(dict(
      coin_id = i['id'],
      symbol = i['symbol'],
      coin_name = i['name'],
      current_price = i['current_price'],
      market_cap = i['market_cap'],
      market_cap_rank = i['market_cap_rank'],
      total_volume = i['total_volume'],
      circulating_supply = i['circulating_supply'],
      total_supply = i['total_supply'],
      ath = i['ath'],
      atl = i['atl'],
      last_updated = i['last_updated']
      ))

In [5]:
filtered_columns

[{'coin_id': 'bitcoin',
  'symbol': 'btc',
  'coin_name': 'Bitcoin',
  'current_price': 5834975,
  'market_cap': 116669385858811,
  'market_cap_rank': 1,
  'total_volume': 4013569758743,
  'circulating_supply': 19994281.0,
  'total_supply': 19994306.0,
  'ath': 11187013,
  'atl': 3993.42,
  'last_updated': '2026-02-24T23:31:32.395Z'},
 {'coin_id': 'ethereum',
  'symbol': 'eth',
  'coin_name': 'Ethereum',
  'current_price': 168908,
  'market_cap': 20384091282971,
  'market_cap_rank': 2,
  'total_volume': 1726953738156,
  'circulating_supply': 120692340.095627,
  'total_supply': 120692340.095627,
  'ath': 431946,
  'atl': 28.13,
  'last_updated': '2026-02-24T23:31:32.498Z'},
 {'coin_id': 'tether',
  'symbol': 'usdt',
  'coin_name': 'Tether',
  'current_price': 90.92,
  'market_cap': 16695272786059,
  'market_cap_rank': 3,
  'total_volume': 6351256229938,
  'circulating_supply': 183624238441.843,
  'total_supply': 189091175734.4462,
  'ath': 105.52,
  'atl': 36.86,
  'last_updated': '2026-02-24T23:31:41.884Z'},
 {'coin_id': 'ripple',
  'symbol': 'xrp',
  'coin_name': 'XRP',
  'current_price': 122.68,
  'market_cap': 7482710244321,
  'market_cap_rank': 4,
  'total_volume': 249245774223,
  'circulating_supply': 61018583977.0,
  'total_supply': 99985712847.0,
  'ath': 313.99,
  'atl': 0.159343,
  'last_updated': '2026-02-24T23:31:41.706Z'},
 {'coin_id': 'binancecoin',
  'symbol': 'bnb',
  'coin_name': 'BNB',
  'current_price': 53191,
  'market_cap': 7251751308346,
  'market_cap_rank': 5,
  'total_volume': 112841387164,
  'circulating_supply': 136358948.75,
  'total_supply': 136358948.75,
  'ath': 121422,
  'atl': 2.58,
  'last_updated': '2026-02-24T23:31:32.262Z'},
 {'coin_id': 'usd-coin',
  'symbol': 'usdc',
  'coin_name': 'USDC',
  'current_price': 90.92,
  'market_cap': 6812774704845,
  'market_cap_rank': 6,
  'total_volume': 1060126342980,
  'circulating_supply': 74933243473.90916,
  'total_supply': 74937490511.55618,
  'ath': 1327.87,
  'atl': 65.31,
  'last_updated': '2026-02-24T23:31:41.893Z'},
 {'coin_id': 'solana',
  'symbol': 'sol',
  'coin_name': 'Solana',
  'current_price': 7209.99,
  'market_cap': 4096262117067,
  'market_cap_rank': 7,
  'total_volume': 353584884953,
  'circulating_supply': 568666665.5179197,
  'total_supply': 621063067.3641098,
  'ath': 25396,
  'atl': 38.03,
  'last_updated': '2026-02-24T23:31:41.730Z'},
 {'coin_id': 'tron',
  'symbol': 'trx',
  'coin_name': 'TRON',
  'current_price': 25.75,
  'market_cap': 2439935100873,
  'market_cap_rank': 8,
  'total_volume': 46393745868,
  'circulating_supply': 94736335071.3254,
  'total_supply': 94736631674.8172,
  'ath': 36.53,
  'atl': 0.117589,
  'last_updated': '2026-02-24T23:31:41.750Z'},
 {'coin_id': 'figure-heloc',
  'symbol': 'figr_heloc',
  'coin_name': 'Figure Heloc',
  'current_price': 94.0,
  'market_cap': 1445413957343,
  'market_cap_rank': 9,
  'total_volume': 2806432457,
  'circulating_supply': 15376945530.577,
  'total_supply': 15376945530.577,
  'ath': 120.96,
  'atl': 13.78,
  'last_updated': '2026-02-24T23:31:41.418Z'},
 {'coin_id': 'dogecoin',
  'symbol': 'doge',
  'coin_name': 'Dogecoin',
  'current_price': 8.33,
  'market_cap': 1405507433047,
  'market_cap_rank': 10,
  'total_volume': 77382886538,
  'circulating_supply': 168830643126.5791,
  'total_supply': 168878003126.5791,
  'ath': 53.62,
  'atl': 0.00552883,
  'last_updated': '2026-02-24T23:31:41.713Z'},
 {'coin_id': 'whitebit',
  'symbol': 'wbt',
  'coin_name': 'WhiteBIT Coin',
  'current_price': 4375.48,
  'market_cap': 934359837977,
  'market_cap_rank': 11,
  'total_volume': 6842771891,
  'circulating_supply': 213544699.0,
  'total_supply': 320044699.0,
  'ath': 5758.63,
  'atl': 245.71,
  'last_updated': '2026-02-24T23:31:41.902Z'},
 {'coin_id': 'usds',
  'symbol': 'usds',
  'coin_name': 'USDS',
  'current_price': 90.92,
  'market_cap': 900593150847,
  'market_cap_rank': 12,
  'total_volume': 1515917426,
  'circulating_supply': 9905926780.82061,
  'total_supply': 9905926780.82061,
  'ath': 92.23,
  'atl': 79.67,
  'last_updated': '2026-02-24T23:31:41.821Z'},
 {'coin_id': 'bitcoin-cash',
  'symbol': 'bch',
  'coin_name': 'Bitcoin Cash',
  'current_price': 44074,
  'market_cap': 881118363568,
  'market_cap_rank': 13,
  'total_volume': 39994011477,
  'circulating_supply': 19999578.02165078,
  'total_supply': 19999849.89665078,
  'ath': 242198,
  'atl': 5536.54,
  'last_updated': '2026-02-24T23:31:41.722Z'},
 {'coin_id': 'cardano',
  'symbol': 'ada',
  'coin_name': 'Cardano',
  'current_price': 23.56,
  'market_cap': 866663543763,
  'market_cap_rank': 14,
  'total_volume': 33643333347,
  'circulating_supply': 36813373987.7429,
  'total_supply': 45000000000.0,
  'ath': 225.26,
  'atl': 1.38,
  'last_updated': '2026-02-24T23:31:41.894Z'},
 {'coin_id': 'leo-token',
  'symbol': 'leo',
  'coin_name': 'LEO Token',
  'current_price': 775.22,
  'market_cap': 713292779632,
  'market_cap_rank': 15,
  'total_volume': 697823421,
  'circulating_supply': 921303981.9,
  'total_supply': 985239504.0,
  'ath': 888.26,
  'atl': 56.97,
  'last_updated': '2026-02-24T23:31:41.469Z'},
 {'coin_id': 'hyperliquid',
  'symbol': 'hype',
  'coin_name': 'Hyperliquid',
  'current_price': 2488.23,
  'market_cap': 591945934971,
  'market_cap_rank': 16,
  'total_volume': 18607619772,
  'circulating_supply': 238385315.9541414,
  'total_supply': 962274028.9541414,
  'ath': 5213.52,
  'atl': 321.88,
  'last_updated': '2026-02-24T23:31:41.561Z'},
 {'coin_id': 'ethena-usde',
  'symbol': 'usde',
  'coin_name': 'Ethena USDe',
  'current_price': 90.85,
  'market_cap': 552962794184,
  'market_cap_rank': 17,
  'total_volume': 9155268263,
  'circulating_supply': 6086729545.055552,
  'total_supply': 6086729545.055552,
  'ath': 92.91,
  'atl': 78.05,
  'last_updated': '2026-02-24T23:31:41.602Z'},
 {'coin_id': 'canton-network',
  'symbol': 'cc',
  'coin_name': 'Canton',
  'current_price': 14.57,
  'market_cap': 550752282884,
  'market_cap_rank': 18,
  'total_volume': 688733752,
  'circulating_supply': 37823997066.04275,
  'total_supply': 37823997066.04275,
  'ath': 17.72,
  'atl': 5.31,
  'last_updated': '2026-02-24T23:31:41.772Z'},
 {'coin_id': 'monero',
  'symbol': 'xmr',
  'coin_name': 'Monero',
  'current_price': 29399,
  'market_cap': 542502634043,
  'market_cap_rank': 19,
  'total_volume': 8439859566,
  'circulating_supply': 18446744.07370955,
  'total_supply': 18446744.07370955,
  'ath': 72026,
  'atl': 13.57,
  'last_updated': '2026-02-24T23:31:41.578Z'},
 {'coin_id': 'chainlink',
  'symbol': 'link',
  'coin_name': 'Chainlink',
  'current_price': 746.83,
  'market_cap': 528614773491,
  'market_cap_rank': 20,
  'total_volume': 26846196265,
  'circulating_supply': 708099970.4525867,
  'total_supply': 1000000000.0,
  'ath': 3862.15,
  'atl': 9.55,
  'last_updated': '2026-02-24T23:31:41.931Z'},
 {'coin_id': 'stellar',
  'symbol': 'xlm',
  'coin_name': 'Stellar',
  'current_price': 13.66,
  'market_cap': 448652924490,
  'market_cap_rank': 21,
  'total_volume': 7643255894,
  'circulating_supply': 32857840980.49057,
  'total_supply': 50001786883.65895,
  'ath': 58.01,
  'atl': 0.02966141,
  'last_updated': '2026-02-24T23:31:42.319Z'},
 {'coin_id': 'usd1-wlfi',
  'symbol': 'usd1',
  'coin_name': 'USD1',
  'current_price': 90.92,
  'market_cap': 424958517133,
  'market_cap_rank': 22,
  'total_volume': 184224417172,
  'circulating_supply': 4674772575.644544,
  'total_supply': 4674772575.644544,
  'ath': 92.17,
  'atl': 83.75,
  'last_updated': '2026-02-24T23:31:42.391Z'},
 {'coin_id': 'rain',
  'symbol': 'rain',
  'coin_name': 'Rain',
  'current_price': 0.854032,
  'market_cap': 408003926879,
  'market_cap_rank': 23,
  'total_volume': 2934586863,
  'circulating_supply': 477919985116.97076,
  'total_supply': 1149928998706.746,
  'ath': 0.989197,
  'atl': 0.196087,
  'last_updated': '2026-02-24T23:31:41.955Z'},
 {'coin_id': 'dai',
  'symbol': 'dai',
  'coin_name': 'Dai',
  'current_price': 90.84,
  'market_cap': 380464682545,
  'market_cap_rank': 24,
  'total_volume': 9318179373,
  'circulating_supply': 4188367502.096358,
  'total_supply': 4188367502.096358,
  'ath': 92.29,
  'atl': 64.85,
  'last_updated': '2026-02-24T23:31:41.732Z'},
 {'coin_id': 'paypal-usd',
  'symbol': 'pyusd',
  'coin_name': 'PayPal USD',
  'current_price': 90.92,
  'market_cap': 373936268968,
  'market_cap_rank': 25,
  'total_volume': 12282370374,
  'circulating_supply': 4113526331.726424,
  'total_supply': 4113526331.726424,
  'ath': 92.2,
  'atl': 80.95,
  'last_updated': '2026-02-24T23:31:42.133Z'},
 {'coin_id': 'hedera-hashgraph',
  'symbol': 'hbar',
  'coin_name': 'Hedera',
  'current_price': 8.66,
  'market_cap': 372020493814,
  'market_cap_rank': 26,
  'total_volume': 6635877287,
  'circulating_supply': 43003421569.28274,
  'total_supply': 50000000000.0,
  'ath': 41.81,
  'atl': 0.703644,
  'last_updated': '2026-02-24T23:31:41.765Z'},
 {'coin_id': 'zcash',
  'symbol': 'zec',
  'coin_name': 'Zcash',
  'current_price': 22193,
  'market_cap': 367349723443,
  'market_cap_rank': 27,
  'total_volume': 28321869665,
  'circulating_supply': 16570357.9780448,
  'total_supply': 16570870.4780448,
  'ath': 211171,
  'atl': 1342.38,
  'last_updated': '2026-02-24T23:31:41.786Z'},
 {'coin_id': 'litecoin',
  'symbol': 'ltc',
  'coin_name': 'Litecoin',
  'current_price': 4659.99,
  'market_cap': 358095225107,
  'market_cap_rank': 28,
  'total_volume': 26965342144,
  'circulating_supply': 76885045.73347135,
  'total_supply': 76886101.98347135,
  'ath': 30082,
  'atl': 72.12,
  'last_updated': '2026-02-24T23:31:41.989Z'},
 {'coin_id': 'avalanche-2',
  'symbol': 'avax',
  'coin_name': 'Avalanche',
  'current_price': 754.53,
  'market_cap': 325768673996,
  'market_cap_rank': 29,
  'total_volume': 21147070082,
  'circulating_supply': 431771961.1772119,
  'total_supply': 463441061.1772119,
  'ath': 10772.35,
  'atl': 204.63,
  'last_updated': '2026-02-24T23:31:42.239Z'},
 {'coin_id': 'shiba-inu',
  'symbol': 'shib',
  'coin_name': 'Shiba Inu',
  'current_price': 0.00053693,
  'market_cap': 316373338717,
  'market_cap_rank': 30,
  'total_volume': 8420201924,
  'circulating_supply': 589243857567583.2,
  'total_supply': 589500399334711.4,
  'ath': 0.00645756,
  'atl': 4.169e-09,
  'last_updated': '2026-02-24T23:31:41.875Z'},
 {'coin_id': 'sui',
  'symbol': 'sui',
  'coin_name': 'Sui',
  'current_price': 78.43,
  'market_cap': 301658831354,
  'market_cap_rank': 31,
  'total_volume': 39537252785,
  'circulating_supply': 3846172527.429665,
  'total_supply': 10000000000.0,
  'ath': 458.6,
  'atl': 30.36,
  'last_updated': '2026-02-24T23:31:41.968Z'},
 {'coin_id': 'the-open-network',
  'symbol': 'ton',
  'coin_name': 'Toncoin',
  'current_price': 117.9,
  'market_cap': 289091340723,
  'market_cap_rank': 32,
  'total_volume': 8085529754,
  'circulating_supply': 2452181510.35275,
  'total_supply': 5155084129.966719,
  'ath': 689.6,
  'atl': 38.25,
  'last_updated': '2026-02-24T23:31:42.020Z'},
 {'coin_id': 'world-liberty-financial',
  'symbol': 'wlfi',
  'coin_name': 'World Liberty Financial',
  'current_price': 10.14,
  'market_cap': 280518081655,
  'market_cap_rank': 33,
  'total_volume': 8019001353,
  'circulating_supply': 27660794172.0,
  'total_supply': 100000000000.0,
  'ath': 29.22,
  'atl': 8.91,
  'last_updated': '2026-02-24T23:31:41.955Z'},
 {'coin_id': 'crypto-com-chain',
  'symbol': 'cro',
  'coin_name': 'Cronos',
  'current_price': 6.74,
  'market_cap': 276634776858,
  'market_cap_rank': 34,
  'total_volume': 1107846999,
  'circulating_supply': 41056479089.72999,
  'total_supply': 98423056710.34172,
  'ath': 72.06,
  'atl': 0.864137,
  'last_updated': '2026-02-24T23:31:41.771Z'},
 {'coin_id': 'tether-gold',
  'symbol': 'xaut',
  'coin_name': 'Tether Gold',
  'current_price': 465394,
  'market_cap': 242357159463,
  'market_cap_rank': 35,
  'total_volume': 44666561691,
  'circulating_supply': 520825.641697,
  'total_supply': 712747.089,
  'ath': 514631,
  'atl': 108167,
  'last_updated': '2026-02-24T23:31:42.033Z'},
 {'coin_id': 'memecore',
  'symbol': 'm',
  'coin_name': 'MemeCore',
  'current_price': 129.18,
  'market_cap': 224734716037,
  'market_cap_rank': 36,
  'total_volume': 661953507,
  'circulating_supply': 1739453396.87,
  'total_supply': 5339453396.429275,
  'ath': 260.79,
  'atl': 4.05,
  'last_updated': '2026-02-24T23:31:41.856Z'},
 {'coin_id': 'pax-gold',
  'symbol': 'paxg',
  'coin_name': 'PAX Gold',
  'current_price': 468357,
  'market_cap': 217818063393,
  'market_cap_rank': 37,
  'total_volume': 53324100725,
  'circulating_supply': 465073.822,
  'total_supply': 465073.822,
  'ath': 516779,
  'atl': 100361,
  'last_updated': '2026-02-24T23:31:42.451Z'},
 {'coin_id': 'uniswap',
  'symbol': 'uni',
  'coin_name': 'Uniswap',
  'current_price': 304.08,
  'market_cap': 192661972491,
  'market_cap_rank': 38,
  'total_volume': 16986805140,
  'circulating_supply': 633660762.0380214,
  'total_supply': 898630420.0366304,
  'ath': 3333.06,
  'atl': 75.81,
  'last_updated': '2026-02-24T23:31:42.038Z'},
 {'coin_id': 'polkadot',
  'symbol': 'dot',
  'coin_name': 'Polkadot',
  'current_price': 112.72,
  'market_cap': 188083263878,
  'market_cap_rank': 39,
  'total_volume': 11521084615,
  'circulating_supply': 1668661680.685334,
  'total_supply': 1668661680.685334,
  'ath': 4095.22,
  'atl': 103.91,
  'last_updated': '2026-02-24T23:31:42.216Z'},
 {'coin_id': 'blackrock-usd-institutional-digital-liquidity-fund',
  'symbol': 'buidl',
  'coin_name': 'BlackRock USD Institutional Digital Liquidity Fund',
  'current_price': 90.92,
  'market_cap': 176338219727,
  'market_cap_rank': 40,
  'total_volume': None,
  'circulating_supply': 1939526801.790448,
  'total_supply': 1939526801.790448,
  'ath': 92.2,
  'atl': 83.81,
  'last_updated': '2026-02-24T23:25:03.308Z'},
 {'coin_id': 'mantle',
  'symbol': 'mnt',
  'coin_name': 'Mantle',
  'current_price': 53.78,
  'market_cap': 174877402337,
  'market_cap_rank': 41,
  'total_volume': 2762322857,
  'circulating_supply': 3252944055.63684,
  'total_supply': 6219316794.889999,
  'ath': 253.43,
  'atl': 25.64,
  'last_updated': '2026-02-24T23:31:42.002Z'},
 {'coin_id': 'falcon-finance',
  'symbol': 'usdf',
  'coin_name': 'Falcon USD',
  'current_price': 90.71,
  'market_cap': 159259416929,
  'market_cap_rank': 42,
  'total_volume': 49451723,
  'circulating_supply': 1755765219.178374,
  'total_supply': 1755765219.178374,
  'ath': 92.45,
  'atl': 80.47,
  'last_updated': '2026-02-24T23:31:41.818Z'},
 {'coin_id': 'aave',
  'symbol': 'aave',
  'coin_name': 'Aave',
  'current_price': 10417.79,
  'market_cap': 158222500974,
  'market_cap_rank': 43,
  'total_volume': 26351563562,
  'circulating_supply': 15190741.134471694,
  'total_supply': 16000000.0,
  'ath': 48387,
  'atl': 1933.39,
  'last_updated': '2026-02-24T23:31:42.156Z'},
 {'coin_id': 'aster-2',
  'symbol': 'aster',
  'coin_name': 'Aster',
  'current_price': 63.42,
  'market_cap': 155707185497,
  'market_cap_rank': 44,
  'total_volume': 14629866245,
  'circulating_supply': 2454947754.91,
  'total_supply': 7822985112.446448,
  'ath': 213.7,
  'atl': 8.76,
  'last_updated': '2026-02-24T23:31:42.244Z'},
 {'coin_id': 'pepe',
  'symbol': 'pepe',
  'coin_name': 'Pepe',
  'current_price': 0.0003591,
  'market_cap': 150973203096,
  'market_cap_rank': 45,
  'total_volume': 25636929105,
  'circulating_supply': 420690000000000.0,
  'total_supply': 420690000000000.0,
  'ath': 0.00237833,
  'atl': 4.52e-06,
  'last_updated': '2026-02-24T23:31:42.076Z'},
 {'coin_id': 'global-dollar',
  'symbol': 'usdg',
  'coin_name': 'Global Dollar',
  'current_price': 90.93,
  'market_cap': 147608854255,
  'market_cap_rank': 46,
  'total_volume': 2445932560,
  'circulating_supply': 1623447249.943427,
  'total_supply': 1623447249.943427,
  'ath': 143.35,
  'atl': 76.61,
  'last_updated': '2026-02-24T23:31:42.038Z'},
 {'coin_id': 'bittensor',
  'symbol': 'tao',
  'coin_name': 'Bittensor',
  'current_price': 15261.3,
  'market_cap': 146470203347,
  'market_cap_rank': 47,
  'total_volume': 6911744100,
  'circulating_supply': 9597491.0,
  'total_supply': 21000000.0,
  'ath': 62722,
  'atl': 2535.93,
  'last_updated': '2026-02-24T23:31:42.090Z'},
 {'coin_id': 'hashnote-usyc',
  'symbol': 'usyc',
  'coin_name': 'Circle USYC',
  'current_price': 101.11,
  'market_cap': 144003304098,
  'market_cap_rank': 48,
  'total_volume': 4044.32,
  'circulating_supply': 1553620528.721001,
  'total_supply': 1553620528.721001,
  'ath': 102.4,
  'atl': 86.89,
  'last_updated': '2026-02-10T05:42:11.457Z'},
 {'coin_id': 'ripple-usd',
  'symbol': 'rlusd',
  'coin_name': 'Ripple USD',
  'current_price': 90.89,
  'market_cap': 141660624954,
  'market_cap_rank': 49,
  'total_volume': 7911269940,
  'circulating_supply': 1558420615.127497,
  'total_supply': 1558420615.127497,
  'ath': 92.15,
  'atl': 81.72,
  'last_updated': '2026-02-24T23:31:42.250Z'},
 {'coin_id': 'okb',
  'symbol': 'okb',
  'coin_name': 'OKB',
  'current_price': 6725.0,
  'market_cap': 141205652660,
  'market_cap_rank': 50,
  'total_volume': 1226294588,
  'circulating_supply': 21000000.0,
  'total_supply': 21000000.0,
  'ath': 22313,
  'atl': 40.86,
  'last_updated': '2026-02-24T23:31:42.121Z'},
 {'coin_id': 'bitget-token',
  'symbol': 'bgb',
  'coin_name': 'Bitget Token',
  'current_price': 200.2,
  'market_cap': 140195841564,
  'market_cap_rank': 51,
  'total_volume': 1841414339,
  'circulating_supply': 699992035.9787906,
  'total_supply': 916931610.9787906,
  'ath': 722.65,
  'atl': 1.081,
  'last_updated': '2026-02-24T23:31:41.999Z'},
 {'coin_id': 'sky',
  'symbol': 'sky',
  'coin_name': 'Sky',
  'current_price': 6.0,
  'market_cap': 138277593745,
  'market_cap_rank': 52,
  'total_volume': 887413714,
  'circulating_supply': 23035661192.73247,
  'total_supply': 23462665147.36596,
  'ath': 8.62,
  'atl': 3.12,
  'last_updated': '2026-02-24T23:31:41.985Z'},
 {'coin_id': 'htx-dao',
  'symbol': 'htx',
  'coin_name': 'HTX DAO',
  'current_price': 0.00014954,
  'market_cap': 137056928027,
  'market_cap_rank': 53,
  'total_volume': 2681444183,
  'circulating_supply': 916533066327098.8,
  'total_supply': 916533066327098.8,
  'ath': 0.00031771,
  'atl': 6.739e-05,
  'last_updated': '2026-02-24T23:31:41.895Z'},
 {'coin_id': 'pi-network',
  'symbol': 'pi',
  'coin_name': 'Pi Network',
  'current_price': 14.75,
  'market_cap': 135917111210,
  'market_cap_rank': 54,
  'total_volume': 1488641074,
  'circulating_supply': 9215230841.540285,
  'total_supply': 14173114075.1072,
  'ath': 260.4,
  'atl': 11.91,
  'last_updated': '2026-02-24T23:31:42.291Z'},
 {'coin_id': 'bfusd',
  'symbol': 'bfusd',
  'coin_name': 'BFUSD',
  'current_price': 90.91,
  'market_cap': 119997929440,
  'market_cap_rank': 55,
  'total_volume': 1390843984,
  'circulating_supply': 1320000000.0,
  'total_supply': 1320000000.0,
  'ath': 92.02,
  'atl': 86.85,
  'last_updated': '2026-02-24T23:31:41.913Z'},
 {'coin_id': 'ethereum-classic',
  'symbol': 'etc',
  'coin_name': 'Ethereum Classic',
  'current_price': 756.87,
  'market_cap': 117780588539,
  'market_cap_rank': 56,
  'total_volume': 4431686125,
  'circulating_supply': 155664565.1249432,
  'total_supply': 155664565.1249432,
  'ath': 12296.58,
  'atl': 41.44,
  'last_updated': '2026-02-24T23:31:42.157Z'},
 {'coin_id': 'near',
  'symbol': 'near',
  'coin_name': 'NEAR Protocol',
  'current_price': 88.07,
  'market_cap': 113456957460,
  'market_cap_rank': 57,
  'total_volume': 8325426343,
  'circulating_supply': 1288650842.0,
  'total_supply': 1288650810.0,
  'ath': 1518.16,
  'atl': 39.17,
  'last_updated': '2026-02-24T23:31:42.171Z'},
 {'coin_id': 'ondo-finance',
  'symbol': 'ondo',
  'coin_name': 'Ondo',
  'current_price': 22.47,
  'market_cap': 109413576861,
  'market_cap_rank': 58,
  'total_volume': 5036292497,
  'circulating_supply': 4869330647.0,
  'total_supply': 10000000000.0,
  'ath': 181.52,
  'atl': 6.83,
  'last_updated': '2026-02-24T23:31:42.117Z'},
 {'coin_id': 'polygon-ecosystem-token',
  'symbol': 'pol',
  'coin_name': 'POL (ex-MATIC)',

In [6]:
print(f"Total data for filtered columns: {len(filtered_columns)}")

Total data for filtered columns: 750

In [7]:
import pandas as pd

crypto_df = pd.DataFrame(filtered_columns) #visualizing data in pandas
crypto_df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5834975.00,116669385858811,1,4.013570e+12,1.999428e+07,1.999431e+07,11187013.00,3993.420000,2026-02-24T23:31:32.395Z
1,ethereum,eth,Ethereum,168908.00,20384091282971,2,1.726954e+12,1.206923e+08,1.206923e+08,431946.00,28.130000,2026-02-24T23:31:32.498Z
2,tether,usdt,Tether,90.92,16695272786059,3,6.351256e+12,1.836242e+11,1.890912e+11,105.52,36.860000,2026-02-24T23:31:41.884Z
3,ripple,xrp,XRP,122.68,7482710244321,4,2.492458e+11,6.101858e+10,9.998571e+10,313.99,0.159343,2026-02-24T23:31:41.706Z
4,binancecoin,bnb,BNB,53191.00,7251751308346,5,1.128414e+11,1.363589e+08,1.363589e+08,121422.00,2.580000,2026-02-24T23:31:32.262Z
...,...,...,...,...,...,...,...,...,...,...,...,...
745,quantum-resistant-ledger,qrl,Quantum Resistant Ledger,129.80,10175020244,246,5.175805e+06,7.839296e+07,7.839296e+07,315.35,3.080000,2026-02-24T23:31:34.247Z
746,bitmart-token,bmx,BitMart,29.95,10163613645,247,5.419740e+08,3.394120e+08,6.394120e+08,52.71,0.501523,2026-02-24T23:31:34.211Z
747,re-protocol-reusd,reusd,Re Protocol reUSD,96.58,10150969722,248,5.934978e+06,1.051242e+08,1.051242e+08,98.49,75.070000,2026-02-24T23:31:34.202Z
748,livepeer,lpt,Livepeer,204.37,10147118709,250,2.842680e+09,4.968895e+07,4.968895e+07,7340.08,25.080000,2026-02-24T23:31:34.287Z
749,frax-usd,frxusd,Frax USD,90.92,10147021129,249,3.120335e+08,1.116141e+08,1.116141e+08,92.17,83.770000,2026-02-24T23:31:34.283Z

In [8]:
# date only extract from last_updated
crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5834975.00,116669385858811,1,4.013570e+12,1.999428e+07,1.999431e+07,11187013.00,3993.420000,2026-02-24
1,ethereum,eth,Ethereum,168908.00,20384091282971,2,1.726954e+12,1.206923e+08,1.206923e+08,431946.00,28.130000,2026-02-24
2,tether,usdt,Tether,90.92,16695272786059,3,6.351256e+12,1.836242e+11,1.890912e+11,105.52,36.860000,2026-02-24
3,ripple,xrp,XRP,122.68,7482710244321,4,2.492458e+11,6.101858e+10,9.998571e+10,313.99,0.159343,2026-02-24
4,binancecoin,bnb,BNB,53191.00,7251751308346,5,1.128414e+11,1.363589e+08,1.363589e+08,121422.00,2.580000,2026-02-24
...,...,...,...,...,...,...,...,...,...,...,...,...
745,quantum-resistant-ledger,qrl,Quantum Resistant Ledger,129.80,10175020244,246,5.175805e+06,7.839296e+07,7.839296e+07,315.35,3.080000,2026-02-24
746,bitmart-token,bmx,BitMart,29.95,10163613645,247,5.419740e+08,3.394120e+08,6.394120e+08,52.71,0.501523,2026-02-24
747,re-protocol-reusd,reusd,Re Protocol reUSD,96.58,10150969722,248,5.934978e+06,1.051242e+08,1.051242e+08,98.49,75.070000,2026-02-24
748,livepeer,lpt,Livepeer,204.37,10147118709,250,2.842680e+09,4.968895e+07,4.968895e+07,7340.08,25.080000,2026-02-24
749,frax-usd,frxusd,Frax USD,90.92,10147021129,249,3.120335e+08,1.116141e+08,1.116141e+08,92.17,83.770000,2026-02-24

# **Top Coins Historical Prices**

In [9]:
# getting data for top coins
#scrolling through the data from the URL And exracting the coins history for last 365 days from the day of running the code.
import requests
import pandas as pd
import time

all_coins = []

coin_ids = ['bitcoin','ethereum','tether','binancecoin','ripple']

for i in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
  response=requests.get(url)

  if response.status_code == 200:
    time.sleep(5)
    coins=response.json()
    prices = coins["prices"]#extracting data to table and converting ms to datestamp

    for ts, price in prices:
      all_coins.append({"coin_id": i,"date": pd.to_datetime(ts, unit="ms"),"price": price})

top_coins_df = pd.DataFrame(all_coins)

top_coins_df

      coin_id                date         price
0     bitcoin 2025-02-25 00:00:00  7.922798e+06
1     bitcoin 2025-02-26 00:00:00  7.729282e+06
2     bitcoin 2025-02-27 00:00:00  7.314307e+06
3     bitcoin 2025-02-28 00:00:00  7.397417e+06
4     bitcoin 2025-03-01 00:00:00  7.386260e+06
...       ...                 ...           ...
1093   tether 2026-02-21 00:00:00  9.069154e+01
1094   tether 2026-02-22 00:00:00  9.070614e+01
1095   tether 2026-02-23 00:00:00  9.069543e+01
1096   tether 2026-02-24 00:00:00  9.099528e+01
1097   tether 2026-02-24 23:32:59  9.092660e+01

[1098 rows x 3 columns]

In [10]:
# date only extract from datestamp
top_coins_df["date"] = pd.to_datetime(top_coins_df["date"]).dt.date
top_coins_df

      coin_id        date         price
0     bitcoin  2025-02-25  7.922798e+06
1     bitcoin  2025-02-26  7.729282e+06
2     bitcoin  2025-02-27  7.314307e+06
3     bitcoin  2025-02-28  7.397417e+06
4     bitcoin  2025-03-01  7.386260e+06
...       ...         ...           ...
1093   tether  2026-02-21  9.069154e+01
1094   tether  2026-02-22  9.070614e+01
1095   tether  2026-02-23  9.069543e+01
1096   tether  2026-02-24  9.099528e+01
1097   tether  2026-02-24  9.092660e+01

[1098 rows x 3 columns]

# **Oil Prices(WTI Crude)**

In [11]:
# data collection from github link
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

             Date  Price
0      1986-01-02  25.56
1      1986-01-03  26.00
2      1986-01-06  26.53
3      1986-01-07  25.85
4      1986-01-08  25.87
...           ...    ...
10095  2026-02-10  64.20
10096  2026-02-11  64.80
10097  2026-02-12  63.08
10098  2026-02-13  63.05
10099  2026-02-17  62.53

[10100 rows x 2 columns]

In [12]:
# extracting data from Jan 2020 - Feb 2026 ==> mentioned in project file

oil_df['Date'] = pd.to_datetime(oil_df['Date'])
start_date = pd.to_datetime('2020-01-01')
end_date   = pd.to_datetime('2026-02-23')

oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]

oil_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10095 2026-02-10  64.20
10096 2026-02-11  64.80
10097 2026-02-12  63.08
10098 2026-02-13  63.05
10099 2026-02-17  62.53

[1531 rows x 2 columns]

In [13]:
# saving file as csv file
oil_df.to_csv("oil_prices.csv",index = False)
oil_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10095 2026-02-10  64.20
10096 2026-02-11  64.80
10097 2026-02-12  63.08
10098 2026-02-13  63.05
10099 2026-02-17  62.53

[1531 rows x 2 columns]

In [14]:
# Jan 2020 - Feb 2026 extracted from all prices and read file
oil_df = pd.read_csv("/content/oil_prices.csv")
oil_df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1526  2026-02-10  64.20
1527  2026-02-11  64.80
1528  2026-02-12  63.08
1529  2026-02-13  63.05
1530  2026-02-17  62.53

[1531 rows x 2 columns]

# **Stock Prices (Yahoo Finance API)**

In [15]:
# collect following stocks data from Yahoo Finance API

In [16]:
import yfinance as YF
import pandas as pd

tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

stocks_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
stocks_df.head()

/tmp/ipython-input-1748226739.py:8: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stocks_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [17]:
# colleting data separately for easy undersating
# "^NSEI"
stocks1_df = stocks_df["^NSEI"].reset_index()
stocks1_df

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...
1588,2026-02-16,25423.599609,25697.000000,25372.699219,25682.750000,275800.0
1589,2026-02-17,25637.949219,25764.400391,25570.300781,25725.400391,344100.0
1590,2026-02-18,25752.650391,25828.050781,25645.150391,25819.349609,310200.0
1591,2026-02-19,25873.349609,25885.300781,25388.750000,25454.349609,298200.0
1592,2026-02-20,25406.550781,25663.550781,25379.750000,25571.250000,296600.0

In [18]:
# adding column ==> "tickers"
stocks1_df.insert(1, "Ticker", "^NSEI")
stocks1_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...,...
1588,2026-02-16,^NSEI,25423.599609,25697.000000,25372.699219,25682.750000,275800.0
1589,2026-02-17,^NSEI,25637.949219,25764.400391,25570.300781,25725.400391,344100.0
1590,2026-02-18,^NSEI,25752.650391,25828.050781,25645.150391,25819.349609,310200.0
1591,2026-02-19,^NSEI,25873.349609,25885.300781,25388.750000,25454.349609,298200.0
1592,2026-02-20,^NSEI,25406.550781,25663.550781,25379.750000,25571.250000,296600.0

In [19]:
# finding nulls from collected data
stocks1_df.isnull().sum()

Price
Date       0
Ticker     0
Open      72
High      72
Low       72
Close     72
Volume    72
dtype: int64

In [20]:
# remove null for clear undersating
stocks1_df = stocks1_df.dropna()
stocks1_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...,...
1588,2026-02-16,^NSEI,25423.599609,25697.000000,25372.699219,25682.750000,275800.0
1589,2026-02-17,^NSEI,25637.949219,25764.400391,25570.300781,25725.400391,344100.0
1590,2026-02-18,^NSEI,25752.650391,25828.050781,25645.150391,25819.349609,310200.0
1591,2026-02-19,^NSEI,25873.349609,25885.300781,25388.750000,25454.349609,298200.0
1592,2026-02-20,^NSEI,25406.550781,25663.550781,25379.750000,25571.250000,296600.0

In [21]:
stocks1_df.isnull().sum()

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [22]:
# data collected  for IXIC and GSPC similarly ====> codes where written in same line

In [23]:
# "^IXIC"
stocks2_df = stocks_df["^IXIC"].reset_index()

stocks2_df.insert(1, "Ticker", "^IXIC") # inserting column

stocks2_df = stocks2_df.dropna() # removing nulls

stocks2_df

Price,Date,Ticker,Open,High,Low,Close,Volume
1,2020-01-02,^IXIC,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03,^IXIC,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06,^IXIC,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07,^IXIC,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09
5,2020-01-08,^IXIC,9068.030273,9168.889648,9059.379883,9129.240234,2.472620e+09
...,...,...,...,...,...,...,...
1587,2026-02-13,^IXIC,22561.460938,22742.060547,22402.380859,22546.669922,7.964830e+09
1589,2026-02-17,^IXIC,22394.759766,22690.830078,22256.759766,22578.380859,7.654300e+09
1590,2026-02-18,^IXIC,22629.849609,22895.960938,22597.769531,22753.630859,7.705590e+09
1591,2026-02-19,^IXIC,22639.880859,22768.830078,22583.609375,22682.730469,6.984780e+09
1592,2026-02-20,^IXIC,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09

In [24]:
stocks2_df.isnull().sum() # checking null values are removed

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [25]:
# "^GSPC"
stocks3_df = stocks_df["^GSPC"].reset_index()

stocks3_df.insert(1, "Ticker", "^GSPC") # inserting column

stocks3_df = stocks3_df.dropna() # removing nulls

stocks3_df

Price,Date,Ticker,Open,High,Low,Close,Volume
1,2020-01-02,^GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,^GSPC,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,^GSPC,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,^GSPC,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09
5,2020-01-08,^GSPC,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09
...,...,...,...,...,...,...,...
1587,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
1589,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
1590,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
1591,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
1592,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [26]:
stocks3_df.isnull().sum() # checking null values are removed

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [27]:
# merging all stocks after cleaning nulls and adding column for comparision
stk_df = pd.concat([stocks1_df, stocks2_df, stocks3_df])
stk_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
1587,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
1589,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
1590,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
1591,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
1592,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [28]:
stk_df.isnull().sum() # verify nulls after merging all three data

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

# **SQL connection**

In [29]:
# import and creating database
import sqlite3

conn = sqlite3.connect("cross_mtk.db")
cursor = conn.cursor()

In [30]:
# creating tables for cryptocurrencies

conn.execute("""CREATE TABLE cryptocurrencies
                 (id VARCHAR(50) PRIMARY KEY,
                 symbol VARCHAR(10),
                 name VARCHAR(100),
                 current_price DECIMAL(18, 6),
                 market_cap BIGINT,
                 market_cap_rank INT,
                 total_volume BIGINT,
                 circulating_supply DECIMAL(20, 6),
                 total_supply DECIMAL(20, 6),
                 ath DECIMAL(18, 6),
                 atl DECIMAL(18, 6),
                 date DATE
                 );

                 """)
conn.commit() # apply the changes to the sqlite3

In [31]:
#creating table for Crypto_prices

conn.execute("""CREATE TABLE top_coins
                 (coin_id VARCHAR(50),
                 date DATE,
                 price DECIMAL(18, 6)
                 );

                 """)
conn.commit()

In [32]:
#creating table for Oil_prices

conn.execute("""CREATE TABLE oil_prices
                 (date DATE PRIMARY KEY,
                 price_INR DECIMAL(18, 6)
                 );

                 """)
conn.commit()

In [33]:
#creating table for Stock_prices
conn.execute("""CREATE TABLE stk_prices
                 (date DATE,
                 open DECIMAL(18, 6),
                 high DECIMAL(18, 6),
                 low DECIMAL(18, 6),
                 close DECIMAL(18, 6),
                 volume BIGINT,
                 ticker VARCHAR(20)
                 );

                 """)
conn.commit()

In [34]:
# to know the tables where created or not
import sqlite3

conn = sqlite3.connect("cross_mtk.db")
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

print("Tables in database:")
for table in tables:
    print(table[0])

Tables in database:
cryptocurrencies
top_coins
oil_prices
stk_prices

# **Pushing data frames in to sqlite3**

In [35]:
import sqlite3

conn = sqlite3.connect ("cross_mtk.db")

crypto_df.to_sql ("cryptocurrencies", conn,if_exists = "replace", index = False) # push crypto_df to sqlite
top_coins_df.to_sql ("top_coins", conn,if_exists = "replace", index = False)
oil_df.to_sql ("oil_prices", conn,if_exists = "replace", index = False)
stk_df.to_sql ("stk_prices", conn,if_exists = "replace", index = False)

conn.commit()

# **Querries where mentioned in project file**

## **Cryptocurrencies**

In [36]:
# show/read cryptocurrencies table
df = pd.read_sql("SELECT * FROM  cryptocurrencies;", conn)
df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5834975.00,116669385858811,1,4.013570e+12,1.999428e+07,1.999431e+07,11187013.00,3993.420000,2026-02-24
1,ethereum,eth,Ethereum,168908.00,20384091282971,2,1.726954e+12,1.206923e+08,1.206923e+08,431946.00,28.130000,2026-02-24
2,tether,usdt,Tether,90.92,16695272786059,3,6.351256e+12,1.836242e+11,1.890912e+11,105.52,36.860000,2026-02-24
3,ripple,xrp,XRP,122.68,7482710244321,4,2.492458e+11,6.101858e+10,9.998571e+10,313.99,0.159343,2026-02-24
4,binancecoin,bnb,BNB,53191.00,7251751308346,5,1.128414e+11,1.363589e+08,1.363589e+08,121422.00,2.580000,2026-02-24
...,...,...,...,...,...,...,...,...,...,...,...,...
745,quantum-resistant-ledger,qrl,Quantum Resistant Ledger,129.80,10175020244,246,5.175805e+06,7.839296e+07,7.839296e+07,315.35,3.080000,2026-02-24
746,bitmart-token,bmx,BitMart,29.95,10163613645,247,5.419740e+08,3.394120e+08,6.394120e+08,52.71,0.501523,2026-02-24
747,re-protocol-reusd,reusd,Re Protocol reUSD,96.58,10150969722,248,5.934978e+06,1.051242e+08,1.051242e+08,98.49,75.070000,2026-02-24
748,livepeer,lpt,Livepeer,204.37,10147118709,250,2.842680e+09,4.968895e+07,4.968895e+07,7340.08,25.080000,2026-02-24
749,frax-usd,frxusd,Frax USD,90.92,10147021129,249,3.120335e+08,1.116141e+08,1.116141e+08,92.17,83.770000,2026-02-24

In [37]:
# 1. Find the top 3 cryptocurrencies by market cap.
import sqlite3
import pandas as pd

conn = sqlite3.connect ("cross_mtk.db")

df = pd.read_sql ("""
SELECT coin_name, MAX(market_cap) AS market_cap
FROM cryptocurrencies
WHERE market_cap IS NOT NULL
GROUP BY coin_name
ORDER BY market_cap DESC
LIMIT 3;""", conn)

df

  coin_name       market_cap
0   Bitcoin  116669385858811
1  Ethereum   20384091282971
2    Tether   16695272786059

In [38]:
# 2. List all coins where circulating supply exceeds 90% of total supply.

df = pd.read_sql ("SELECT * FROM cryptocurrencies WHERE total_supply IS NOT NULL AND total_supply > 0 AND circulating_supply >= 0.9 * total_supply;", conn)

df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5834975.00,116669385858811,1,4.013570e+12,1.999428e+07,1.999431e+07,11187013.00,3993.42,2026-02-24
1,ethereum,eth,Ethereum,168908.00,20384091282971,2,1.726954e+12,1.206923e+08,1.206923e+08,431946.00,28.13,2026-02-24
2,tether,usdt,Tether,90.92,16695272786059,3,6.351256e+12,1.836242e+11,1.890912e+11,105.52,36.86,2026-02-24
3,binancecoin,bnb,BNB,53191.00,7251751308346,5,1.128414e+11,1.363589e+08,1.363589e+08,121422.00,2.58,2026-02-24
4,usd-coin,usdc,USDC,90.92,6812774704845,6,1.060126e+12,7.493324e+10,7.493749e+10,1327.87,65.31,2026-02-24
...,...,...,...,...,...,...,...,...,...,...,...,...
418,cash-4,cash,CASH,90.91,10652013813,244,9.741356e+08,1.171717e+08,1.171717e+08,93.86,86.47,2026-02-24
419,quantum-resistant-ledger,qrl,Quantum Resistant Ledger,129.80,10175020244,246,5.175805e+06,7.839296e+07,7.839296e+07,315.35,3.08,2026-02-24
420,re-protocol-reusd,reusd,Re Protocol reUSD,96.58,10150969722,248,5.934978e+06,1.051242e+08,1.051242e+08,98.49,75.07,2026-02-24
421,livepeer,lpt,Livepeer,204.37,10147118709,250,2.842680e+09,4.968895e+07,4.968895e+07,7340.08,25.08,2026-02-24
422,frax-usd,frxusd,Frax USD,90.92,10147021129,249,3.120335e+08,1.116141e+08,1.116141e+08,92.17,83.77,2026-02-24

In [39]:
# 3. Get coins that are within 10% of their all-time-high (ATH).

df = pd.read_sql ("SELECT * FROM cryptocurrencies WHERE current_price >= 0.9 * ath;", conn)

df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,usds,usds,USDS,90.92,900593150847,12,1.515917e+09,9.905927e+09,9.905927e+09,92.23,79.67,2026-02-24
1,ethena-usde,usde,Ethena USDe,90.85,552962794184,17,9.155268e+09,6.086730e+09,6.086730e+09,92.91,78.05,2026-02-24
2,usd1-wlfi,usd1,USD1,90.92,424958517133,22,1.842244e+11,4.674773e+09,4.674773e+09,92.17,83.75,2026-02-24
3,dai,dai,Dai,90.84,380464682545,24,9.318179e+09,4.188368e+09,4.188368e+09,92.29,64.85,2026-02-24
4,paypal-usd,pyusd,PayPal USD,90.92,373936268968,25,1.228237e+10,4.113526e+09,4.113526e+09,92.20,80.95,2026-02-24
...,...,...,...,...,...,...,...,...,...,...,...,...
133,apollo-diversified-credit-securitize-fund,acred,Apollo Diversified Credit Securitize Fund,99811.00,11912855236,219,NaN,1.193536e+05,1.193536e+05,101170.00,85668.00,2026-02-24
134,pleasing-usd,pusd,Pleasing USD,91.02,10922742302,240,0.000000e+00,1.200000e+08,1.200000e+08,95.47,87.56,2026-02-24
135,cash-4,cash,CASH,90.91,10652013813,244,9.741356e+08,1.171717e+08,1.171717e+08,93.86,86.47,2026-02-24
136,re-protocol-reusd,reusd,Re Protocol reUSD,96.58,10150969722,248,5.934978e+06,1.051242e+08,1.051242e+08,98.49,75.07,2026-02-24
137,frax-usd,frxusd,Frax USD,90.92,10147021129,249,3.120335e+08,1.116141e+08,1.116141e+08,92.17,83.77,2026-02-24

In [40]:
# 4. Find the average market cap rank of coins with volume above $1B.

df = pd.read_sql ("SELECT AVG(market_cap_rank) FROM cryptocurrencies WHERE total_volume > 1000000000;", conn)

df

   AVG(market_cap_rank)
0            102.479452

In [41]:
# 5. Get the most recently updated coin.

df = pd.read_sql ("SELECT * FROM cryptocurrencies ORDER BY last_updated DESC LIMIT 1;", conn)

df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,5834975.0,116669385858811,1,4.013570e+12,19994281.0,19994306.0,11187013.0,3993.42,2026-02-24

## **Crypto_Prices (Daily Prices of Top Coins)**

In [42]:
df = pd.read_sql("SELECT * FROM  top_coins;", conn)
df

      coin_id        date         price
0     bitcoin  2025-02-25  7.922798e+06
1     bitcoin  2025-02-26  7.729282e+06
2     bitcoin  2025-02-27  7.314307e+06
3     bitcoin  2025-02-28  7.397417e+06
4     bitcoin  2025-03-01  7.386260e+06
...       ...         ...           ...
1093   tether  2026-02-21  9.069154e+01
1094   tether  2026-02-22  9.070614e+01
1095   tether  2026-02-23  9.069543e+01
1096   tether  2026-02-24  9.099528e+01
1097   tether  2026-02-24  9.092660e+01

[1098 rows x 3 columns]

In [43]:
# 1. Find the highest daily price of Bitcoin in the last 365 days.

df = pd.read_sql ("SELECT * FROM top_coins WHERE coin_id = 'bitcoin' AND date >= date('now', '-365 days') ORDER BY date DESC LIMIT 1;", conn)

df

   coin_id        date         price
0  bitcoin  2026-02-24  5.877905e+06

In [44]:
# 2. Calculate the average daily price of Ethereum in the past 1 year.

df = pd.read_sql ("SELECT AVG(price) FROM top_coins WHERE coin_id = 'ethereum' AND date >= date('now', '-1 year');", conn)

df

      AVG(price)
0  263575.382057

In [45]:
# 3. Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)

df = pd.read_sql("SELECT * FROM top_coins WHERE coin_id = 'bitcoin' AND Date BETWEEN '2025-02-01' AND '2026-02-28' ORDER BY Date;", conn)

df

     coin_id        date         price
0    bitcoin  2025-02-25  7.922798e+06
1    bitcoin  2025-02-26  7.729282e+06
2    bitcoin  2025-02-27  7.314307e+06
3    bitcoin  2025-02-28  7.397417e+06
4    bitcoin  2025-03-01  7.386260e+06
..       ...         ...           ...
361  bitcoin  2026-02-21  6.166731e+06
362  bitcoin  2026-02-22  6.167422e+06
363  bitcoin  2026-02-23  6.132044e+06
364  bitcoin  2026-02-24  5.877905e+06
365  bitcoin  2026-02-24  5.834359e+06

[366 rows x 3 columns]

In [46]:
# 4. Find the coin with the highest average price over 1 year.

df = pd.read_sql ("SELECT coin_id, AVG(price) AS avg_price FROM top_coins GROUP BY coin_id ORDER BY avg_price DESC LIMIT 1;", conn)

df

   coin_id     avg_price
0  bitcoin  8.678823e+06

In [47]:
# 5. Get the % change in Bitcoin’s price between Feb 2025 and Feb 2026.

df = pd.read_sql ("""SELECT
    (
        (price_feb_2026 - price_feb_2025) * 100.0 / price_feb_2025
    ) AS percent_change
FROM
( SELECT
        MAX(CASE WHEN strftime('%Y-%m', date) = '2025-02' THEN price END) AS price_feb_2025,
        MAX(CASE WHEN strftime('%Y-%m', date) = '2026-02' THEN price END) AS price_feb_2026
    FROM top_coins
    WHERE coin_id = 'bitcoin'
);""", conn)

df

   percent_change
0       -8.898502

## **Oil_Price**

In [49]:
df = pd.read_sql ("SELECT * FROM  oil_prices;", conn)
df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1526  2026-02-10  64.20
1527  2026-02-11  64.80
1528  2026-02-12  63.08
1529  2026-02-13  63.05
1530  2026-02-17  62.53

[1531 rows x 2 columns]

In [50]:
# 1. Find the highest oil price in the last 5 years.

df = pd.read_sql("""SELECT MAX(price) AS highest_price
FROM oil_prices
WHERE date >= DATE('now', '-5 years');""", conn)

df

   highest_price
0         123.64

In [51]:
# 2. Get the average oil price per year.

df = pd.read_sql ("SELECT date AS year, AVG(price) AS avg_price FROM oil_prices GROUP BY strftime('%Y', Date);", conn)

df

         year  avg_price
0  2020-01-02  39.160437
1  2021-01-04  68.135100
2  2022-01-03  94.902869
3  2023-01-03  77.576532
4  2024-01-02  76.632240
5  2025-01-02  65.388105
6  2026-01-02  61.238065

In [52]:
# 3. Show oil prices during COVID crash (March–April 2020).

df = pd.read_sql ("SELECT * FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-31' ORDER BY date;", conn)

df

          Date  Price
0   2020-03-02  46.78
1   2020-03-03  47.27
2   2020-03-04  46.78
3   2020-03-05  45.90
4   2020-03-06  41.14
5   2020-03-09  31.05
6   2020-03-10  34.47
7   2020-03-11  33.13
8   2020-03-12  31.56
9   2020-03-13  31.72
10  2020-03-16  28.96
11  2020-03-17  26.96
12  2020-03-18  20.48
13  2020-03-19  25.09
14  2020-03-20  19.48
15  2020-03-23  23.33
16  2020-03-24  21.03
17  2020-03-25  20.75
18  2020-03-26  16.60
19  2020-03-27  15.48
20  2020-03-30  14.10
21  2020-03-31  20.51
22  2020-04-01  20.28
23  2020-04-02  25.18
24  2020-04-03  28.36
25  2020-04-06  26.21
26  2020-04-07  23.54
27  2020-04-08  24.97
28  2020-04-09  22.90
29  2020-04-13  22.36
30  2020-04-14  20.15
31  2020-04-15  19.96
32  2020-04-16  19.82
33  2020-04-17  18.31
34  2020-04-20 -36.98
35  2020-04-21   8.91
36  2020-04-22  13.64
37  2020-04-23  15.06
38  2020-04-24  15.99
39  2020-04-27  12.17
40  2020-04-28  12.40
41  2020-04-29  15.04
42  2020-04-30  19.23

In [53]:
# 4. Find the lowest price of oil in the last 10 years.

df = pd.read_sql ("SELECT MIN(price) AS lowest_price FROM oil_prices WHERE date >= (SELECT date('now', '-10 years'));", conn)

df

   lowest_price
0        -36.98

In [54]:
# 5. Calculate the volatility of oil prices (max-min difference per year).

df = pd.read_sql("""SELECT strftime('%Y', date) AS year,
MAX(price) AS max_price,
MIN(price) AS min_price,
(MAX(price) - MIN(price)) AS volatility
FROM oil_prices
GROUP BY year
ORDER BY year;
""", conn)

df

   year  max_price  min_price  volatility
0  2020      63.27     -36.98      100.25
1  2021      85.64      47.47       38.17
2  2022     123.64      71.05       52.59
3  2023      93.67      66.61       27.06
4  2024      87.69      66.73       20.96
5  2025      80.73      55.44       25.29
6  2026      64.80      56.01        8.79

## **Stock_Prices**

In [55]:
df = pd.read_sql("SELECT * FROM  stk_prices;", conn)
df

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01 00:00:00,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02 00:00:00,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03 00:00:00,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06 00:00:00,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07 00:00:00,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
4600,2026-02-13 00:00:00,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
4601,2026-02-17 00:00:00,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
4602,2026-02-18 00:00:00,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
4603,2026-02-19 00:00:00,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
4604,2026-02-20 00:00:00,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [56]:
# 1. Get all stock prices for a given ticker

df = pd.read_sql ("SELECT * FROM stk_prices WHERE Ticker = '^IXIC' or Ticker = '^NSEI' or Ticker = '^GSPC' GROUP by Ticker ORDER BY Date;", conn)

df

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01 00:00:00,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02 00:00:00,^GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-02 00:00:00,^IXIC,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09

In [57]:
# 2. Find the highest closing price for NASDAQ (^IXIC)

df = pd.read_sql ("SELECT MAX(close) AS highest_closing_price FROM stk_prices WHERE ticker = '^IXIC';", conn)

df

   highest_closing_price
0           23958.470703

In [58]:
# 3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

df = pd.read_sql ("""SELECT date, high - low AS price_difference
FROM stk_prices
WHERE ticker = '^GSPC'
ORDER BY price_difference
DESC LIMIT 5
;""", conn)

df

                  Date  price_difference
0  2025-04-09 00:00:00        532.909668
1  2025-04-07 00:00:00        411.529785
2  2025-04-08 00:00:00        357.050293
3  2025-04-10 00:00:00        237.879883
4  2025-11-20 00:00:00        236.300293

In [59]:
# 4. Get monthly average closing price for each ticker

df = pd.read_sql ("SELECT ticker, strftime('%Y-%m', date) AS month, AVG(close) AS avg_closing_price FROM stk_prices GROUP BY ticker, month;", conn)

df

    Ticker    month  avg_closing_price
0    ^GSPC  2020-01        3278.202858
1    ^GSPC  2020-02        3277.314183
2    ^GSPC  2020-03        2652.393632
3    ^GSPC  2020-04        2761.975226
4    ^GSPC  2020-05        2919.608484
..     ...      ...                ...
217  ^NSEI  2025-10       25494.083519
218  ^NSEI  2025-11       25894.834396
219  ^NSEI  2025-12       25997.738725
220  ^NSEI  2026-01       25652.962695
221  ^NSEI  2026-02       25681.076693

[222 rows x 3 columns]

# **Joint Querries**

In [60]:
# 1. Compare Bitcoin vs Oil average price in 2025.

df = pd.read_sql ("""SELECT 'bitcoin' AS asset,
AVG(price) AS avg_price
FROM top_coins
WHERE coin_id = 'bitcoin'
AND strftime('%Y', date) = '2025'

UNION ALL

SELECT 'OIL' AS asset,
AVG(price) AS avg_price
FROM oil_prices
WHERE strftime('%Y', date) = '2025';

""",conn)

df

     asset     avg_price
0  bitcoin  8.914519e+06
1      OIL  6.538810e+01

In [61]:
# 2. Check if Bitcoin moves with S&P 500 (correlation idea).

df=pd.read_sql("""SELECT
    date(t.date) AS date,
    t.price AS btc_close,
    s.close AS stk_close
FROM top_coins t
LEFT JOIN stk_prices s
    ON date(t.date) = date(s.date)
   AND s.ticker = '^GSPC'
WHERE t.coin_id = 'bitcoin'
ORDER BY date;
""",conn)
df

           date     btc_close    stk_close
0    2025-02-25  7.922798e+06  5955.250000
1    2025-02-26  7.729282e+06  5956.060059
2    2025-02-27  7.314307e+06  5861.569824
3    2025-02-28  7.397417e+06  5954.500000
4    2025-03-01  7.386260e+06          NaN
..          ...           ...          ...
361  2026-02-21  6.166731e+06          NaN
362  2026-02-22  6.167422e+06          NaN
363  2026-02-23  6.132044e+06          NaN
364  2026-02-24  5.877905e+06          NaN
365  2026-02-24  5.834359e+06          NaN

[366 rows x 3 columns]

In [62]:
# 3. Compare Ethereum and NASDAQ daily prices for 2025.

df = pd.read_sql("""
SELECT
    date(t.date) AS date,
    t.price AS eth_price,
    s.close AS nasdaq_close
FROM top_coins t
JOIN stk_prices s
    ON date(t.date) = date(s.date)
WHERE t.coin_id = 'ethereum'
  AND s.ticker = '^IXIC'
  AND strftime('%Y', t.date) = '2025'
ORDER BY date;
""", conn)

df

           date      eth_price  nasdaq_close
0    2025-02-25  216983.409814  19026.390625
1    2025-02-26  217304.159337  19075.259766
2    2025-02-27  202765.038710  18544.419922
3    2025-02-28  201317.512520  18847.279297
4    2025-03-03  220175.988421  18350.189453
..          ...            ...           ...
210  2025-12-24  265308.330577  23613.310547
211  2025-12-26  261698.838882  23593.099609
212  2025-12-29  264760.550466  23474.349609
213  2025-12-30  263786.422730  23419.080078
214  2025-12-31  266620.867155  23241.990234

[215 rows x 3 columns]

In [63]:
# 4. Find days when oil price spiked and compare with Bitcoin price change.

df = pd.read_sql ("""
SELECT
    date(o.Date) AS date,
    o.Price AS oil_price,
    t.price AS btc_price
FROM oil_prices o
JOIN top_coins t
    ON date(o.Date) = date(t.Date)
WHERE t.coin_id = 'bitcoin'
ORDER BY date;
""", conn)

df

           date  oil_price     btc_price
0    2025-02-25      69.15  7.922798e+06
1    2025-02-26      68.87  7.729282e+06
2    2025-02-27      70.62  7.314307e+06
3    2025-02-28      69.97  7.397417e+06
4    2025-03-03      68.63  8.244473e+06
..          ...        ...           ...
239  2026-02-10      64.20  6.363124e+06
240  2026-02-11      64.80  6.230645e+06
241  2026-02-12      63.08  6.073657e+06
242  2026-02-13      63.05  5.993963e+06
243  2026-02-17      62.53  6.255750e+06

[244 rows x 3 columns]

In [64]:
# 5. Compare top 3 coins daily price trend vs Nifty (^NSEI).

df = pd.read_sql ("""
SELECT
    date(c.Date) AS date,
    c.coin_id AS coins,
    c.price AS coin_prices,
    n.Close AS nifty_close
FROM top_coins c
JOIN stk_prices n
    ON date(c.Date) = date(n.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND n.Ticker = '^NSEI'
ORDER BY date;
""", conn)

df

           date     coins   coin_prices   nifty_close
0    2025-02-25   bitcoin  7.922798e+06  22547.550781
1    2025-02-25  ethereum  2.169834e+05  22547.550781
2    2025-02-27   bitcoin  7.314307e+06  22545.050781
3    2025-02-27  ethereum  2.027650e+05  22545.050781
4    2025-02-28   bitcoin  7.397417e+06  22124.699219
..          ...       ...           ...           ...
483  2026-02-18  ethereum  1.805283e+05  25819.349609
484  2026-02-19   bitcoin  6.033802e+06  25454.349609
485  2026-02-19  ethereum  1.774785e+05  25454.349609
486  2026-02-20   bitcoin  6.092367e+06  25571.250000
487  2026-02-20  ethereum  1.772492e+05  25571.250000

[488 rows x 4 columns]

In [65]:
# 6. Compare stock prices (^GSPC) with crude oil prices on the same dates


df = pd.read_sql("""
SELECT
    date(s.Date) AS date,
    s.Close AS nifty_close,
    o.Price AS oil_price
FROM stk_prices s
JOIN oil_prices o
    ON date(s.Date) = date(o.Date)
WHERE s.Ticker = '^GSPC'
ORDER BY date;
""", conn)

df

            date  nifty_close  oil_price
0     2020-01-02  3257.850098      61.17
1     2020-01-03  3234.850098      63.00
2     2020-01-06  3246.280029      63.27
3     2020-01-07  3237.179932      62.70
4     2020-01-08  3253.050049      59.65
...          ...          ...        ...
1526  2026-02-10  6941.810059      64.20
1527  2026-02-11  6941.470215      64.80
1528  2026-02-12  6832.759766      63.08
1529  2026-02-13  6836.169922      63.05
1530  2026-02-17  6843.220215      62.53

[1531 rows x 3 columns]

In [66]:
# 7. Correlate Bitcoin closing price with crude oil closing price (same date)

df = pd.read_sql("""
SELECT
    date(b.Date) AS date,
    b.price AS btc_price,
    o.Price AS oil_price
FROM top_coins b
JOIN oil_prices o
    ON date(b.Date) = date(o.Date)
WHERE b.coin_id = 'bitcoin'
ORDER BY date;
""", conn)

df

           date     btc_price  oil_price
0    2025-02-25  7.922798e+06      69.15
1    2025-02-26  7.729282e+06      68.87
2    2025-02-27  7.314307e+06      70.62
3    2025-02-28  7.397417e+06      69.97
4    2025-03-03  8.244473e+06      68.63
..          ...           ...        ...
239  2026-02-10  6.363124e+06      64.20
240  2026-02-11  6.230645e+06      64.80
241  2026-02-12  6.073657e+06      63.08
242  2026-02-13  5.993963e+06      63.05
243  2026-02-17  6.255750e+06      62.53

[244 rows x 3 columns]

In [67]:
# 8. Compare NASDAQ (^IXIC) with Ethereum price trends

df = pd.read_sql("""
SELECT
    date(e.Date) AS date,
    e.price AS eth_price,
    i.Close AS ixic_close
FROM top_coins e
JOIN stk_prices i
    ON date(e.Date) = date(i.Date)
WHERE e.coin_id = 'ethereum'
  AND i.Ticker = '^IXIC'
ORDER BY date;
""", conn)

df

           date      eth_price    ixic_close
0    2025-02-25  216983.409814  19026.390625
1    2025-02-26  217304.159337  19075.259766
2    2025-02-27  202765.038710  18544.419922
3    2025-02-28  201317.512520  18847.279297
4    2025-03-03  220175.988421  18350.189453
..          ...            ...           ...
244  2026-02-13  176214.238345  22546.669922
245  2026-02-17  181624.154700  22578.380859
246  2026-02-18  180528.328343  22753.630859
247  2026-02-19  177478.459914  22682.730469
248  2026-02-20  177249.247482  22886.070312

[249 rows x 3 columns]

In [68]:
# 9. Join top 3 crypto coins with stock indices for 2025
df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.coin_id AS crypto,
    t.price AS crypto_price,
    s.Ticker AS index_symbol,
    s.Close AS index_close
FROM top_coins t
JOIN stk_prices s
    ON date(t.Date) = date(s.Date)
WHERE t.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
  AND strftime('%Y', t.Date) = '2025'
ORDER BY date;
""", conn)

df

            date    crypto  crypto_price index_symbol   index_close
0     2025-02-25   bitcoin  7.922798e+06        ^NSEI  22547.550781
1     2025-02-25   bitcoin  7.922798e+06        ^IXIC  19026.390625
2     2025-02-25   bitcoin  7.922798e+06        ^GSPC   5955.250000
3     2025-02-25  ethereum  2.169834e+05        ^NSEI  22547.550781
4     2025-02-25  ethereum  2.169834e+05        ^IXIC  19026.390625
...          ...       ...           ...          ...           ...
1273  2025-12-31   bitcoin  7.936951e+06        ^IXIC  23241.990234
1274  2025-12-31   bitcoin  7.936951e+06        ^GSPC   6845.500000
1275  2025-12-31  ethereum  2.666209e+05        ^NSEI  26129.599609
1276  2025-12-31  ethereum  2.666209e+05        ^IXIC  23241.990234
1277  2025-12-31  ethereum  2.666209e+05        ^GSPC   6845.500000

[1278 rows x 5 columns]

In [69]:
# 10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    s.Close AS stk_close,
    o.Price AS oil_price
FROM top_coins t
JOIN stk_prices s
    ON date(t.Date) = date(s.Date)
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
ORDER BY date;
""", conn)

df

           date     btc_price    stk_close  oil_price
0    2025-02-25  7.922798e+06  5955.250000      69.15
1    2025-02-26  7.729282e+06  5956.060059      68.87
2    2025-02-27  7.314307e+06  5861.569824      70.62
3    2025-02-28  7.397417e+06  5954.500000      69.97
4    2025-03-03  8.244473e+06  5849.720215      68.63
..          ...           ...          ...        ...
239  2026-02-10  6.363124e+06  6941.810059      64.20
240  2026-02-11  6.230645e+06  6941.470215      64.80
241  2026-02-12  6.073657e+06  6832.759766      63.08
242  2026-02-13  5.993963e+06  6836.169922      63.05
243  2026-02-17  6.255750e+06  6843.220215      62.53

[244 rows x 4 columns]

**Saving files and donloading for future reference**

In [70]:
# saving data frames as csv files
crypto_df.to_csv("crypto.csv", index=False)
top_coins_df.to_csv("top_coins.csv", index=False)
oil_df.to_csv("oil.csv", index=False)
stk_df.to_csv("stk.csv", index=False)

In [71]:
from google.colab import files # dowmload files as csv

files.download("crypto.csv")
files.download("top_coins.csv")
files.download("oil.csv")
files.download("stk.csv")

# **Streamlit App**

In [72]:
!pip install -q streamlit plotly pandas

!wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared-linux-amd64

In [86]:
%%writefile app.py
import streamlit as st
import pandas as pd
import sqlite3
import plotly.express as px
from datetime import datetime

st.set_page_config(page_title="Cross-Market Analysis", layout="wide")
st.title("💰🛢️📈 Cross-Market Analysis: Crypto, Oil & Stocks")
# LOAD CSVs
@st.cache_data
def load_data():
    crypto_df = pd.read_csv("crypto.csv")
    top_coins_df = pd.read_csv("top_coins.csv")
    oil_df = pd.read_csv("oil.csv")
    stk_df = pd.read_csv("stk.csv")

    top_coins_df['date'] = pd.to_datetime(top_coins_df['date'])
    oil_df['Date'] = pd.to_datetime(oil_df['Date'])
    stk_df['Date'] = pd.to_datetime(stk_df['Date'])

    return crypto_df, top_coins_df, oil_df, stk_df

crypto_df, top_coins_df, oil_df, stk_df = load_data()

#CREATE SQLITE DB
@st.cache_resource
def create_db():
    conn = sqlite3.connect ("cross_mtk.db")
    crypto_df.to_sql ("cryptocurrencies", conn,if_exists = "replace", index = False)
    top_coins_df.to_sql ("top_coins", conn,if_exists = "replace", index = False)
    oil_df.to_sql ("oil_prices", conn,if_exists = "replace", index = False)
    stk_df.to_sql ("stk_prices", conn,if_exists = "replace", index = False)
    return conn

conn = create_db()

# SIDEBAR
page = st.sidebar.selectbox(
    "Select Page",
    ["Filters & Data Exploration", "SQL Query Runner", "Top Crypto Analysis"]
)

# PAGE 1: Filters & Data Exploration
if page == "Filters & Data Exploration":
    st.subheader("📊 Market Overview")
    start_date = st.date_input("Start Date", datetime(2025, 1, 1))
    end_date = st.date_input("End Date", datetime(2026, 1, 1))

    # convert to datetime64 for comparison
    start_dt = pd.to_datetime(start_date)
    end_dt = pd.to_datetime(end_date)

    btc_df = top_coins_df[
        (top_coins_df["coin_id"] == "bitcoin") &
        (top_coins_df["date"].between(start_dt, end_dt))
    ]
    btc_df.columns = btc_df.columns.str.strip().str.lower()

    oil_filtered = oil_df[oil_df["Date"].between(start_dt, end_dt)]
    oil_filtered.columns = oil_filtered.columns.str.strip().str.lower()

    nifty = stk_df[(stk_df["Ticker"] == "^NSEI") & (stk_df["Date"].between(start_dt, end_dt))]
    nifty.columns = nifty.columns.str.strip().str.lower()

    col1, col2, col3 = st.columns(3)
    col1.metric("Bitcoin Avg Price", round(btc_df["price"].mean(), 2))
    col2.metric("Oil Avg Price", round(oil_filtered["price"].mean(), 2))
    col3.metric("NIFTY Avg Close", round(nifty["close"].mean(), 2))

    snapshot = (
        btc_df.merge(oil_filtered, on="date", how="inner", suffixes=("_btc","_oil"))
        .merge(nifty[["date","close"]], on="date", how="inner", suffixes=("", "_nifty"))
    )



    st.subheader("📅 Daily Market Snapshot")
    cols = [col for col in ["date","price_btc","price_oil","close_nifty","close"] if col in snapshot.columns]
    st.dataframe(snapshot[cols])

#  PAGE 2: SQL Query Runner
elif page == "SQL Query Runner":
    st.subheader("🧠 SQL Query Runner")

    # Queries Categorization
    queries = {
        "cryptocurrencies": {
            "Top 3 by Market Cap": """SELECT coin_name, MAX(market_cap) AS market_cap FROM cryptocurrencies
                                      WHERE market_cap IS NOT NULL GROUP BY coin_name ORDER BY market_cap DESC LIMIT 3;""",

            "Circulating supply > 90% of total supply": "SELECT * FROM cryptocurrencies WHERE circulating_supply > 0.9 * total_supply;",

            "Within 10% of ath": "SELECT * FROM cryptocurrencies WHERE current_price >= 0.9 * ath;",

            "Average market_cap_rank for volume > $1B": "SELECT AVG(market_cap_rank) AS avg_rank FROM cryptocurrencies WHERE Total_volume > 1000000000;",

            "Most recently updated coin": "SELECT * FROM cryptocurrencies ORDER BY date DESC LIMIT 1;"
        },

        "top_coins": {
            "Highest daily BTC price last 365 days": """SELECT * FROM top_coins WHERE coin_id='bitcoin'
                                                        AND date >= date('now','-365 days') ORDER BY date DESC LIMIT 1;""",

            "Average ETH daily price past year": """SELECT AVG(price) AS avg_daily_price FROM top_coins
                                                    WHERE coin_id='ethereum' AND date >= date('now','-365 days');""",

            "BTC daily trend Feb 2025": """SELECT * FROM top_coins WHERE coin_id='bitcoin' AND date BETWEEN '2025-02-01' AND '2025-02-28'
                                            ORDER BY date;""",

            "Highest avg coin price 1Y": """SELECT coin_id, AVG(price) AS avg_price_1y FROM top_coins
                                            WHERE date >= date('now','-1 year') GROUP BY coin_id ORDER BY avg_price_1y DESC LIMIT 1;""",

            "BTC % change Feb 2025–Feb 2026": """SELECT ((p2026.price - p2025.price)*100.0/p2025.price) AS pct_change
                                                 FROM top_coins p2025 JOIN top_coins p2026 ON p2025.coin_id=p2026.coin_id
                                                 WHERE p2025.coin_id='bitcoin' AND p2025.date='2025-02-05' AND p2026.date='2026-02-04';"""
        },

        "oil_prices": {

            "Highest oil price last 5 years": """SELECT MAX(Price) AS highest_price FROM oil_prices
                                                 WHERE date >= (SELECT substr(MAX(Date),1,4)-5||'-01-01' FROM oil_prices);""",

            "Average oil price per year": """SELECT substr(date,1,4) AS year, AVG(Price) AS avg_price
                                             FROM oil_prices GROUP BY substr(date,1,4) ORDER BY year;""",

            "Oil prices COVID crash Mar-Apr 2020": "SELECT * FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date;",

            "Lowest oil price last 10 years": """SELECT MIN(Price) AS lowest_price FROM oil_prices
                                                 WHERE date >= (SELECT substr(MAX(date),1,4)-10||'-01-01' FROM oil_prices);""",

            "Oil volatility per year": """SELECT substr(date,1,4) AS year, MAX(Price)-MIN(Price) AS volatility
                                          FROM oil_prices GROUP BY substr(date,1,4) ORDER BY year;"""
        },

        "stk_prices": {
            "All prices for ^IXIC/^NSEI/^GSPC": "SELECT * FROM stk_prices WHERE Ticker IN ('^IXIC','^NSEI','^GSPC') ORDER BY date;",

            "Highest NASDAQ close": "SELECT MAX(Close) AS highest_close FROM stk_prices WHERE Ticker='^IXIC';",

            "Top 5 high-low diff S&P 500": """SELECT date,(High-Low) AS price_difference FROM stk_prices WHERE Ticker='^GSPC'
                                              ORDER BY price_difference DESC LIMIT 5;""",

            "Monthly avg close per ticker": """SELECT Ticker, substr(date,1,7) AS month, AVG(Close) AS avg_monthly_close
                                               FROM stk_prices GROUP BY Ticker, substr(date,1,7) ORDER BY Ticker, month;""",
        },

        "join_queries": {
            "Bitcoin vs Oil avg 2025": """SELECT 'bitcoin' AS asset, AVG(price) AS avg_price FROM top_coins WHERE coin_id='bitcoin'
                                          AND strftime('%Y',date)='2025' UNION ALL SELECT 'OIL' AS asset, AVG(Price) AS avg_price
                                          FROM oil_prices WHERE strftime('%Y',date)='2025';""",

            "BTC correlation with S&P500": """SELECT date(c.date) AS date, c.price AS btc_close, s.Close AS sp500_close FROM top_coins c
                                              LEFT JOIN stk_prices s ON date(c.date)=date(s.date) AND s.Ticker='^GSPC'
                                              WHERE c.coin_id='bitcoin' ORDER BY date;""",

            "ETH vs NASDAQ daily 2025": """SELECT date(c.date) AS date, c.price AS eth_price, s.Close AS nasdaq_close FROM top_coins c
                                           JOIN stk_prices s ON date(c.date)=date(s.Date)
                                           WHERE c.coin_id='ethereum' AND s.Ticker='^IXIC' AND strftime('%Y',c.date)='2025'
                                           ORDER BY date;""",

            "Oil spike vs BTC price": """SELECT date(o.date) AS date, o.Price AS oil_price, b.price AS btc_price FROM oil_prices o
                                         JOIN top_coins b ON date(o.date)=date(b.Date)
                                         WHERE b.coin_id='bitcoin' ORDER BY date;""",

            "Top 3 coins vs Nifty": """SELECT date(c.date) AS date, c.coin_id AS crypto, c.price AS crypto_price, n.Close AS nifty_close
                                        FROM top_coins c JOIN stk_prices n ON date(c.Date)=date(n.date)
                                        WHERE c.coin_id IN ('bitcoin','ethereum','binancecoin') AND n.Ticker='^NSEI' ORDER BY date, crypto;""",

            "S&P500 vs Oil": """SELECT date(s.date) AS date, s.Close AS sp500_close, o.Price AS oil_price FROM stk_prices s
                               JOIN oil_prices o ON date(s.Date)=date(o.date) WHERE s.Ticker='^GSPC' ORDER BY date;""",

            "BTC vs Oil closing price": """SELECT date(b.date) AS date, b.price AS btc_price, o.Price AS oil_price FROM top_coins b
                                          JOIN oil_prices o ON date(b.date)=date(o.date) WHERE b.coin_id='bitcoin' ORDER BY date;""",

            "NASDAQ vs ETH": """SELECT date(e.date) AS date, e.price AS eth_price, n.Close AS nasdaq_close FROM top_coins e
                               JOIN stk_prices n ON date(e.date)=date(n.Date) WHERE e.coin_id='ethereum' AND n.Ticker='^IXIC' ORDER BY date;""",

            "Top 3 coins vs indices 2025": """SELECT date(c.date) AS date, c.coin_id AS crypto, c.price AS crypto_price, s.Ticker AS index_symbol,
                                              s.Close AS index_close
                                              FROM top_coins c JOIN stk_prices s ON date(c.Date)=date(s.date)
                                              WHERE c.coin_id IN ('bitcoin','ethereum','binancecoin') AND s.Ticker IN ('^GSPC','^IXIC','^NSEI')
                                              AND strftime('%Y',c.date)='2025' ORDER BY date, crypto;""",

            "Multi-join BTC+S&P+Oil": """SELECT date(b.date) AS date, b.price AS btc_price, s.Close AS sp500_close, o.Price AS oil_price
                                         FROM top_coins b JOIN stk_prices s ON date(b.date)=date(s.date)
                                         JOIN oil_prices o ON date(b.date)=date(o.Date)
                                         WHERE b.coin_id='bitcoin' AND s.Ticker='^GSPC' ORDER BY date;"""
        }
    }

    category = st.selectbox("Select Category", list(queries.keys()))
    query_name = st.selectbox("Select Query", list(queries[category].keys()))

    if st.button("Run Query"):
        sql = queries[category][query_name]
        df = pd.read_sql(sql, conn)
        st.dataframe(df)

        # For join_queries, show line chart automatically
        if category=="join_queries":
            numeric_cols = df.select_dtypes(include='number').columns
            if len(numeric_cols) > 1:
                fig = px.line(df, x=df.columns[0], y=numeric_cols, title=query_name)
                st.plotly_chart(fig, use_container_width=True)

# PAGE 3: Top Crypto Analysis
else:
    st.subheader("📈 Top Crypto Price Trend")

    top_coins = (crypto_df.sort_values("market_cap_rank").drop_duplicates(subset="coin_id").head(5)["coin_id"].tolist())

    selected_coin = st.selectbox("Select Coin", top_coins)

    start = st.date_input("From", datetime(2024, 1, 1), key="c1")
    end = st.date_input("To", datetime(2025, 1, 1), key="c2")

    start_dt = pd.to_datetime(start)
    end_dt = pd.to_datetime(end)

    # normalize columns
    top_coins_df.columns = top_coins_df.columns.str.lower()
    top_coins_df["date"] = pd.to_datetime(top_coins_df["date"], errors="coerce")

    # filtering INSIDE block
    selected_coin_df = top_coins_df[
        (top_coins_df["coin_id"] == selected_coin) &
        (top_coins_df["date"].between(start_dt, end_dt))
    ]

    fig = px.line(selected_coin_df, x="date", y="price", title=f"{selected_coin.upper()} Price Trend")
    st.plotly_chart(fig, use_container_width=True)
    st.dataframe(selected_coin_df)

Overwriting app.py

In [74]:
!streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &>/content/streamlit.log &

In [75]:
!./cloudflared-linux-amd64 tunnel --url http://localhost:8501 &>/content/cloudflare.log &

In [77]:
!grep -o 'https://.*trycloudflare.com' /content/cloudflare.log | head -n 1

https://sons-standings-len-numerical.trycloudflare.com

In [76]:
with open('/content/streamlit.log', 'r') as f: # for verification of host availability
    print(f.read())

Collecting usage statistics. To deactivate, set browser.gatherUsageStats to false.


  You can now view your Streamlit app in your browser.

  Local URL: http://localhost:8501
  Network URL: http://172.28.0.12:8501
  External URL: http://34.80.19.211:8501

In [ ]:
# Used to expose a local app to the internet.
## !wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64!chmod +x cloudflared-linux-amd64

#Runs your Streamlit app  0.0.0.0 → allows external access & → runs in background (important in notebooks)
## !streamlit run app.py --server.port 8501 --server.address 0.0.0.0 &>/content/streamlit.log &

# This creates a temporary public link like:
## !./cloudflared-linux-amd64 tunnel --url http://localhost:8501 &>/content/cloudflare.log &

# Just prints the URL so you can click it
## !grep -o 'https://.*trycloudflare.com' /content/cloudflare.log | head -n 1