--------------------------------------------------------------------------------
# **Author** : ***Mohamed Halith M K***
## **Title**  : ***Cross Market Analysis***
### ***GUVI Mini Project - 1***
--------------------------------------------------------------------------------

# Data Collection

In [ ]:
import requests
import time
import pandas as pd

In [ ]:
data_crypto = []

for page_num in range(1,6):
  url = f"https://api.coingecko.com/api/v3/coins/markets?vs_currency=inr&per_page=250&order=market_cap_desc&page=1&sparkline=False"
  response = requests.get(url)
  if response.status_code == 200:
    data_crypto.extend(response.json()) # Extend the list with data from current page
    print(f"Collected data from page {page_num}")
  else:
    print(f"Error collecting data from page {page_num}: {response.status_code}")
    page_num += 1
  time.sleep(5) # Increased wait time to 1 second to avoid rate limiting

print ("==========================================")
print(f"Total data collected: {len(data_crypto)}")

Collected data from page 1
Collected data from page 2
Collected data from page 3
Collected data from page 4
Collected data from page 5
==========================================
Total data collected: 1250

In [ ]:
import pprint

In [ ]:
pprint.pprint(data_crypto)

Streaming output truncated to the last 5000 lines.
  'market_cap': 131971891489,
  'market_cap_change_24h': 886664570,
  'market_cap_change_percentage_24h': 0.6764,
  'market_cap_rank': 60,
  'max_supply': 2000000000.0,
  'name': 'Bitget Token',
  'price_change_24h': 1.27,
  'price_change_percentage_24h': 0.67635,
  'roi': None,
  'symbol': 'bgb',
  'total_supply': 913931280.9787906,
  'total_volume': 1333691748},
 {'ath': 96.87,
  'ath_change_percentage': -1.35307,
  'ath_date': '2026-05-20T14:15:46.804Z',
  'atl': 86.85,
  'atl_change_percentage': 10.03244,
  'atl_date': '2025-08-19T09:52:03.013Z',
  'circulating_supply': 1320000000.0,
  'current_price': 95.56,
  'fully_diluted_valuation': 126136257990,
  'high_24h': 95.57,
  'id': 'bfusd',
  'image': 'https://coin-images.coingecko.com/coins/images/68227/large/bfusd.png?1755132827',
  'last_updated': '2026-05-24T15:50:44.955Z',
  'low_24h': 95.54,
  'market_cap': 126136257990,
  'market_cap_change_24h': -11579478.175567627,
  'market_cap_change_percentage_24h': -0.00918,
  'market_cap_rank': 61,
  'max_supply': None,
  'name': 'BFUSD',
  'price_change_24h': 0.00053679,
  'price_change_percentage_24h': 0.00056,
  'roi': None,
  'symbol': 'bfusd',
  'total_supply': 1320000000.0,
  'total_volume': 26017132},
 {'ath': 48387,
  'ath_change_percentage': -83.03395,
  'ath_date': '2021-05-18T21:19:59.514Z',
  'atl': 1933.39,
  'atl_change_percentage': 324.61262,
  'atl_date': '2020-11-05T09:20:11.928Z',
  'circulating_supply': 15179911.874935383,
  'current_price': 8209.31,
  'fully_diluted_valuation': 131320785241,
  'high_24h': 8483.17,
  'id': 'aave',
  'image': 'https://coin-images.coingecko.com/coins/images/12645/large/aave-token-round.png?1720472354',
  'last_updated': '2026-05-24T15:50:41.332Z',
  'low_24h': 8146.8,
  'market_cap': 124589871707,
  'market_cap_change_24h': 994394199,
  'market_cap_change_percentage_24h': 0.80456,
  'market_cap_rank': 62,
  'max_supply': 16000000.0,
  'name': 'Aave',
  'price_change_24h': 61.1,
  'price_change_percentage_24h': 0.74982,
  'roi': None,
  'symbol': 'aave',
  'total_supply': 16000000.0,
  'total_volume': 14589508807},
 {'ath': 31427,
  'ath_change_percentage': -75.70164,
  'ath_date': '2021-09-11T09:15:00.668Z',
  'atl': 15.06,
  'atl_change_percentage': 50606.10272,
  'atl_date': '2018-08-23T00:00:00.000Z',
  'circulating_supply': 14544176.164081175,
  'current_price': 7635.99,
  'fully_diluted_valuation': 111554661270,
  'high_24h': 7994.03,
  'id': 'quant-network',
  'image': 'https://coin-images.coingecko.com/coins/images/3370/large/5ZOu7brX_400x400.jpg?1696504070',
  'last_updated': '2026-05-24T15:50:42.789Z',
  'low_24h': 7328.71,
  'market_cap': 111033117034,
  'market_cap_change_24h': 2331316968,
  'market_cap_change_percentage_24h': 2.14469,
  'market_cap_rank': 63,
  'max_supply': 14612493.0,
  'name': 'Quant',
  'price_change_24h': 179.3,
  'price_change_percentage_24h': 2.40454,
  'roi': {'currency': 'eth',
          'percentage': 1538.6860900415477,
          'times': 15.386860900415478},
  'symbol': 'qnt',
  'total_supply': 14612493.0,
  'total_volume': 1964770461},
 {'ath': 96.94,
  'ath_change_percentage': -1.34173,
  'ath_date': '2026-05-20T14:15:56.839Z',
  'atl': 77.41,
  'atl_change_percentage': 23.55274,
  'atl_date': '2025-07-17T08:05:52.672Z',
  'circulating_supply': 1089208402.796182,
  'current_price': 95.64,
  'fully_diluted_valuation': 104166724701,
  'high_24h': 95.66,
  'id': 'usdtb',
  'image': 'https://coin-images.coingecko.com/coins/images/52804/large/76357aa8-4ef7-446c-bad3-a3f944eeec7a.jpeg?1758277468',
  'last_updated': '2026-05-24T15:50:43.916Z',
  'low_24h': 95.6,
  'market_cap': 104166724701,
  'market_cap_change_24h': 39011703,
  'market_cap_change_percentage_24h': 0.03747,
  'market_cap_rank': 64,
  'max_supply': None,
  'name': 'USDtb',
  'price_change_24h': 0.03903312,
  'price_change_percentage_24h': 0.04083,
  'roi': None,
  'symbol': 'usdtb',
  'total_supply': 1089208402.796182,
  'total_volume': 100005078},
 {'ath': 2158.41,
  'ath_change_percentage': -64.38301,
  'ath_date': '2021-12-01T15:09:35.541Z',
  'atl': 24.48,
  'atl_change_percentage': 3040.14819,
  'atl_date': '2019-02-13T00:00:00.000Z',
  'circulating_supply': 134655021.7355671,
  'current_price': 768.69,
  'fully_diluted_valuation': 109243693470,
  'high_24h': 779.01,
  'id': 'kucoin-shares',
  'image': 'https://coin-images.coingecko.com/coins/images/1047/large/sa9z79.png?1696502152',
  'last_updated': '2026-05-24T15:50:40.738Z',
  'low_24h': 753.85,
  'market_cap': 103480072242,
  'market_cap_change_24h': 1783997743,
  'market_cap_change_percentage_24h': 1.75424,
  'market_cap_rank': 65,
  'max_supply': None,
  'name': 'KuCoin',
  'price_change_24h': 13.54,
  'price_change_percentage_24h': 1.79331,
  'roi': None,
  'symbol': 'kcs',
  'total_supply': 142155021.7355671,
  'total_volume': 257282156},
 {'ath': 118.63,
  'ath_change_percentage': -1.50318,
  'ath_date': '2026-05-21T01:00:19.118Z',
  'atl': 84.72,
  'atl_change_percentage': 37.92456,
  'atl_date': '2024-08-20T06:40:12.965Z',
  'circulating_supply': 866127792.27097,
  'current_price': 116.84,
  'fully_diluted_valuation': 101201254851,
  'high_24h': 116.84,
  'id': 'eutbl',
  'image': 'https://coin-images.coingecko.com/coins/images/39657/large/EUTBL.png?1723517425',
  'last_updated': '2026-05-24T15:40:18.683Z',
  'low_24h': 116.84,
  'market_cap': 101201254851,
  'market_cap_change_24h': 0.0,
  'market_cap_change_percentage_24h': 0.0,
  'market_cap_rank': 66,
  'max_supply': None,
  'name': 'Spiko EU T-Bills Money Market Fund',
  'price_change_24h': -1.4211e-14,
  'price_change_percentage_24h': 0.0,
  'roi': None,
  'symbol': 'eutbl',
  'total_supply': 866127792.27097,
  'total_volume': None},
 {'ath': 3233.07,
  'ath_change_percentage': -93.91577,
  'ath_date': '2022-01-17T00:00:00.000Z',
  'atl': 87.61,
  'atl_change_percentage': 124.51914,
  'atl_date': '2020-03-13T02:27:44.591Z',
  'circulating_supply': 510310254.147613,
  'current_price': 196.46,
  'fully_diluted_valuation': 100316438756,
  'high_24h': 204.55,
  'id': 'cosmos',
  'image': 'https://coin-images.coingecko.com/coins/images/1481/large/cosmos_hub.png?1696502525',
  'last_updated': '2026-05-24T15:50:41.944Z',
  'low_24h': 195.95,
  'market_cap': 100314901809,
  'market_cap_change_24h': -527758611.0467987,
  'market_cap_change_percentage_24h': -0.52335,
  'market_cap_rank': 67,
  'max_supply': None,
  'name': 'Cosmos Hub',
  'price_change_24h': -1.2652485574532761,
  'price_change_percentage_24h': -0.63989,
  'roi': {'currency': 'usd',
          'percentage': 1952.895911391896,
          'times': 19.52895911391896},
  'symbol': 'atom',
  'total_supply': 510318072.721986,
  'total_volume': 3256036587},
 {'ath': 971.56,
  'ath_change_percentage': -97.04911,
  'ath_date': '2024-03-10T00:10:42.330Z',
  'atl': 22.04,
  'atl_change_percentage': 30.08748,
  'atl_date': '2026-05-02T05:30:44.240Z',
  'circulating_supply': 3414545758.127662,
  'current_price': 28.86,
  'fully_diluted_valuation': 288526425980,
  'high_24h': 29.71,
  'id': 'worldcoin-wld',
  'image': 'https://coin-images.coingecko.com/coins/images/31069/large/worldcoin.jpeg?1696529903',
  'last_updated': '2026-05-24T15:50:42.633Z',
  'low_24h': 26.8,
  'market_cap': 98518668394,
  'market_cap_change_24h': 6679048642,
  'market_cap_change_percentage_24h': 7.27251,
  'market_cap_rank': 68,
  'max_supply': 10000000000.0,
  'name': 'Worldcoin',
  'price_change_24h': 1.94,
  'price_change_percentage_24h': 7.22192,
  'roi': None,
  'symbol': 'wld',
  'total_supply': 10000000000.0,
  'total_volume': 22483575602},
 {'ath': 97.11,
  'ath_change_percentage': -1.4453,
  'ath_date': '2026-05-21T00:55:29.223Z',
  'atl': 86.73,
  'atl_change_percentage': 10.35314,
  'atl_date': '2025-12-21T00:47:20.303Z',
  'circulating_supply': 1027858682.01,
  'current_price': 95.61,
  'fully_diluted_valuation': 98310690334,
  'high_24h': 95.83,
  'id': 'united-stables',
  'image': 'https://coin-images.coingecko.com/coins/images/71157/large/united-stables-logo.jpg?1766061640',
  'last_updated': '2026-05-24T15:50:26.041Z',
  'low_24h': 95.29,
  'market_cap': 98310690334,
  'market_cap_change_24h': -53757997.33546448,
  'market_cap_change_percentage_24h': -0.05465,
  'market_cap_rank': 69,
  'max_supply': None,
  'name': 'United Stables',
  'price_change_24h': -0.08506152615230178,
  'price_change_percentage_24h': -0.08888,
  'roi': None,
  'symbol': 'u',
  'total_supply': 1027858682.01,
  'total_volume': 17032050473},
 {'ath': 1121.89,
  'ath_change_percentage': -83.33128,
  'ath_date': '2024-03-17T16:30:24.636Z',
  'atl': 2.79,
  'atl_change_percentage': 6602.69334,
  'atl_date': '2020-06-16T13:22:25.900Z',
  'circulating_supply': 518743261.0140742,
  'current_price': 187.47,
  'fully_diluted_valuation': 99977328025,
  'high_24h': 193.02,
  'id': 'render-token',
  'image': 'https://coin-images.coingecko.com/coins/images/11636/large/rndr.png?1696511529',
  'last_updated': '2026-05-24T15:50:41.096Z',
  'low_24h': 178.68,
  'market_cap': 97211305183,
  'market_cap_change_24h': 4203131627,
  'market_cap_change_percentage_24h': 4.5191,
  'market_cap_rank': 70,
  'max_supply': 644245094.0,
  'name': 'Render',
  'price_change_24h': 7.99,
  'price_change_percentage_24h': 4.45306,
  'roi': None,
  'symbol': 'render',
  'total_supply': 533503434.2940742,
  'total_volume': 8415390519},
 {'ath': 247.29,
  'ath_change_percentage': -95.6615,
  'ath_date': '2019-06-20T14:51:19.480Z',
  'atl': 7.26,
  'atl_change_percentage': 47.87824,
  'atl_date': '2023-09-11T19:42:08.247Z',
  'circulating_supply': 8917352824.722261,
  'current_price': 10.73,
  'fully_diluted_valuation': 95672433907,
  'high_24h': 11.13,
  'id': 'algorand',
  'image': 'https://coin-images.coingecko.com/coins/images/4380/large/download.png?1696504978',
  'last_updated': '2026-05-24T15:50:43.807Z',
  'low_24h': 10.69,
  'market_cap': 95670090709,
  'market_cap_change_24h': -486979416.9368744,
  'market_cap_change_percentage_24h': -0.50644,
  'market_cap_rank': 71,
  'max_supply': 10000000000.0,
  'name': 'Algorand',
  'price_change_24h': -0.05853485939745262,
  'price_change_percentage_24h': -0.5424,
  'roi': {'currency': 'usd',
          'percentage': -95.3269147815317,
          'times': -0.9532691478153169},
  'symbol': 'algo',
  'total_supply': 8917571232.868385,
  'total_volume': 2457034921},
 {'ath': 1075.49,
  'ath_change_percentage': -1.32153,
  'ath_date': '2026-05-20T14:15:03.147Z',
  'atl': 876.83,
  'atl_change_percentage': 21.03571,
  'atl_date': '2024-11-01T12:45:33.122Z',
  'circulating_supply': 88650971.385841,
  'current_price': 1061.28,
  'fully_diluted_valuation': 94274430976,
  'high_24h': 1061.28,
  'id': 'superstate-short-duration-us-government-securities-fund-ustb',
  'image': 'https://coin-images.coingecko.com/coins/images/35012/large/ustb.jpeg?1707102680',
  'last_updated': '2026-05-24T15:50:09.424Z',
  'low_24h': 1061.28,
  'market_cap': 94083079579,
  'market_cap_change_24h': 483827546,
  'market_cap_change_percentage_24h': 0.51691,
  'market_cap_rank': 72,
  'max_supply': None,
  'name': 'Superstate Short Duration U.S. Government Securities Fund (USTB)',
  'price_change_24h': 0.0,
  'price_change_percentage_24h': 0.0,
  'roi': None,
  'symbol': 'ustb',
  'total_supply': 88831274.659553,
  'total_volume': None},
 {'ath': 10258.25,
  'ath_change_percentage': -1.35388,
  'ath_date': '2026-05-20T14:20:11.624Z',
  'atl': 1516.02,
  'atl_change_percentage': 567.49681,
  'atl_date': '2025-06-02T23:15:02.895Z',
  'circulating_supply': 9112111.0,
  'current_price': 10119.37,
  'fully_diluted_valuation': 92208808457,
  'high_24h': 10119.37,
  'id': 'blockchain-capital',
  'image': 'https://coin-images.coingecko.com/coins/images/56040/large/bcap_logo_200.png?1748088291',
  'last_updated': '2026-05-24T15:50:08.833Z',
  'low_24h': 10119.37,
  'market_cap': 92208808457,
  'market_cap_change_24h': 0.0,
  'market_cap_change_percentage_24h': 0.0,
  'market_cap_rank': 73,
  'max_supply': None,
  'name': 'Blockchain Capital',
  'price_change_24h': -1.818989e-12,
  'price_change_percentage_24h': 0.0,
  'roi': None,
  'symbol': 'bcap',
  'total_supply': 9112111.0,
  'total_volume': None},
 {'ath': 106.68,
  'ath_change_percentage': -91.89189,
  'ath_date': '2024-03-13T18:55:06.692Z',
  'atl': 7.58,
  'atl_change_percentage': 14.07064,
  'atl_date': '2026-04-12T22:30:40.372Z',
  'circulating_supply': 10648620284.29958,
  'current_price': 8.65,
  'fully_diluted_valuation': 92139200891,
  'high_24h': 8.8,
  'id': 'polygon-ecosystem-token',
  'image': 'https://coin-images.coingecko.com/coins/images/32440/large/pol.png?1759114181',
  'last_updated': '2026-05-24T15:50:42.551Z',
  'low_24h': 8.6,
  'market_cap': 92139200891,
  'market_cap_change_24h': 251591437,
  'market_cap_change_percentage_24h': 0.2738,
  'market_cap_rank': 74,
  'max_supply': None,
  'name': 'POL (ex-MATIC)',
  'price_change_24h': 0.02022389,
  'price_change_percentage_24h': 0.23425,
  'roi': None,
  'symbol': 'pol',
  'total_supply': 10648620284.29958,
  'total_volume': 3111322585},
 {'ath': 107.1,
  'ath_change_percentage': -1.33735,
  'ath_date': '2026-05-20T14:20:22.965Z',
  'atl': 95.98,
  'atl_change_percentage': 10.08908,
  'atl_date': '2025-11-19T05:25:04.387Z',
  'circulating_supply': 850609381.31547,
  'current_price': 105.67,
  'fully_diluted_valuation': 89880863090,
  'high_24h': 105.67,
  'id': 'janus-henderson-anemoy-treasury-fund',
  'image': 'https://coin-images.coingecko.com/coins/images/70445/large/JTRSY.png?1762078582',
  'last_updated': '2026-05-24T15:50:02.868Z',
  'low_24h': 105.67,
  'market_cap': 89880863090,
  'market_cap_change_24h': 0.0,
  'market_cap_change_percentage_24h': 0.0,
  'market_cap_rank': 75,
  'max_supply': None,
  'name': 'Janus Henderson Anemoy Treasury Fund',
  'price_change_24h': -1.4211e-14,
  'price_change_percentage_24h': 0.0,
  'roi': None,
  'symbol': 'jtrsy',
  'total_supply': 850609381.31547,
  'total_volume': None},
 {'ath': 1952.18,
  'ath_change_percentage': -1.69245,
  'ath_date': '2025-01-28T00:06:36.780Z',
  'atl': 82.42,
  'atl_change_percentage': 2228.58945,
  'atl_date': '2025-12-01T16:26:06.891Z',
  'circulating_supply': 46342744.63030691,
  'current_price': 1936.66,
  'fully_diluted_valuation': 155163465090,
  'high_24h': 1945.32,
  'id': 'venice-token',
  'image': 'https://coin-images.coingecko.com/coins/images/54023/large/VVV_Token_Transparent.png?1741856877',
  'last_updated': '2026-05-24T15:50:44.125Z',
  'low_24h': 1669.43,
  'market_cap': 89797860428,
  'market_cap_change_24h': 10554902218,
  'market_cap_change_percentage_24h': 13.31967,
  'market_cap_rank': 76,
  'max_supply': None,
  'name': 'Venice Token',
  'price_change_24h': 207.67,
  'price_change_percentage_24h': 12.01108,
  'roi': None,
  'symbol': 'vvv',
  'total_supply': 80076527.48421782,
  'total_volume': 8525081209},
 {'ath': 17.36,
  'ath_change_percentage': -81.66209,
  'ath_date': '2024-08-01T00:40:47.164Z',
  'atl': 0.01327337,
  'atl_change_percentage': 23884.66203,
  'atl_date': '2022-05-26T14:42:59.316Z',
  'circulating_supply': 27416658504.52483,
  'current_price': 3.18,
  'fully_diluted_valuation': 87464421865,
  'high_24h': 3.28,
  'id': 'kaspa',
  'image': 'https://coin-images.coingecko.com/coins/images/25751/large/kaspa-icon-exchanges.png?1696524837',
  'last_updated': '2026-05-24T15:50:42.124Z',
  'low_24h': 3.17,
  'market_cap': 87326526770,
  'market_cap_change_24h': 240805986,
  'market_cap_change_percentage_24h': 0.27652,
  'market_cap_rank': 77,
  'max_supply': 28704026601.0,
  'name': 'Kaspa',
  'price_change_24h': 0.00860159,
  'price_change_percentage_24h': 0.27083,
  'roi': None,
  'symbol': 'kas',
  'total_supply': 27459951452.02709,
  'total_volume': 967630709},
 {'ath': 126.48,
  'ath_change_percentage': -92.5228,
  'ath_date': '2024-04-11T13:15:15.057Z',
  'atl': 7.15,
  'atl_change_percentage': 32.32412,
  'atl_date': '2026-04-05T12:50:40.489Z',
  'circulating_supply': 9026562500.0,
  'current_price': 9.47,
  'fully_diluted_valuation': 141941060340,
  'high_24h': 10.09,
  'id': 'ethena',
  'image': 'https://coin-images.coingecko.com/coins/images/36530/large/ethena.png?1711701436',
  'last_updated': '2026-05-24T15:50:43.484Z',
  'low_24h': 9.35,
  'market_cap': 85415990165,
  'market_cap_change_24h': 969336310,
  'market_cap_change_percentage_24h': 1.14787,
  'market_cap_rank': 78,
  'max_supply': 15000000000.0,
  'name': 'Ethena',
  'price_change_24h': 0.112647,
  'price_change_percentage_24h': 1.20402,
  'roi': None,
  'symbol': 'ena',
  'total_supply': 15000000000.0,
  'total_volume': 7443735015},
 {'ath': 298.99,
  'ath_change_percentage': -72.50908,
  'ath_date': '2021-05-12T14:37:47.535Z',
  'atl': 3.25,
  'atl_change_percentage': 2430.56971,
  'atl_date': '2018-09-13T00:00:00.000Z',
  'circulating_supply': 1000000000.0,
  'current_price': 82.14,
  'fully_diluted_valuation': 82212193771,
  'high_24h': 84.69,
  'id': 'nexo',
  'image': 'https://coin-images.coingecko.com/coins/images/3695/large/CG-nexo-token-200x200_2x.png?1730414360',
  'last_updated': '2026-05-24T15:50:43.110Z',
  'low_24h': 80.69,
  'market_cap': 82212193771,
  'market_cap_change_24h': 10238240,
  'market_cap_change_percentage_24h': 0.01245,
  'market_cap_rank': 79,
  'max_supply': 1000000000.0,
  'name': 'NEXO',
  'price_change_24h': -0.05556838608373482,
  'price_change_percentage_24h': -0.06761,
  'roi': {'currency': 'usd',
          'percentage': 758.3037617170729,
          'times': 7.583037617170729},
  'symbol': 'nexo',
  'total_supply': 1000000000.0,
  'total_volume': 806736029},
 {'ath': 14.19,
  'ath_change_percentage': -36.96454,
  'ath_date': '2021-04-05T04:34:23.454Z',
  'atl': 0.359754,
  'atl_change_percentage': 2386.98543,
  'atl_date': '2020-05-09T06:08:54.872Z',
  'circulating_supply': 8543764567.312736,
  'current_price': 8.95,
  'fully_diluted_valuation': 76424935329,
  'high_24h': 8.96,
  'id': 'just',
  'image': 'https://coin-images.coingecko.com/coins/images/11095/large/JUST.jpg?1696511035',
  'last_updated': '2026-05-24T15:50:40.912Z',
  'low_24h': 8.76,
  'market_cap': 76424935329,
  'market_cap_change_24h': 1536122416,
  'market_cap_change_percentage_24h': 2.0512,
  'market_cap_rank': 80,
  'max_supply': 9900000000.0,
  'name': 'JUST',
  'price_change_24h': 0.182543,
  'price_change_percentage_24h': 2.08289,
  'roi': None,
  'symbol': 'jst',
  'total_supply': 8543764567.312736,
  'total_volume': 2301823368},
 {'ath': 1622.34,
  'ath_change_percentage': -94.41154,
  'ath_date': '2023-01-26T14:25:17.390Z',
  'atl': 72.2,
  'atl_change_percentage': 25.56878,
  'atl_date': '2026-02-23T01:30:53.133Z',
  'circulating_supply': 819473954.8464024,
  'current_price': 90.78,
  'fully_diluted_valuation': 109202525786,
  'high_24h': 95.23,
  'id': 'aptos',
  'image': 'https://coin-images.coingecko.com/coins/images/26455/large/Aptos-Network-Symbol-Black-RGB-1x.png?1761789140',
  'last_updated': '2026-05-24T15:50:42.186Z',
  'low_24h': 89.81,
  'market_cap': 74378410916,
  'market_cap_change_24h': 616055957,
  'market_cap_change_percentage_24h': 0.83519,
  'market_cap_rank': 81,
  'max_supply': 2100000000.0,
  'name': 'Aptos',
  'price_change_24h': 0.755662,
  'price_change_percentage_24h': 0.83943,
  'roi': None,
  'symbol': 'apt',
  'total_supply': 1203153234.69234,
  'total_volume': 5668901303},
 {'ath': 4.08,
  'ath_change_percentage': -21.21695,
  'ath_date': '2026-05-14T23:25:26.430Z',
  'atl': 0.827533,
  'atl_change_percentage': 288.82326,
  'atl_date': '2025-12-24T05:49:32.232Z',
  'circulating_supply': 22967292181.0,
  'current_price': 3.22,
  'fully_diluted_valuation': 321972089732,
  'high_24h': 3.31,
  'id': 'stable-2',
  'image': 'https://coin-images.coingecko.com/coins/images/69242/large/stable-logotype-framed-square-light.png?1762753913',
  'last_updated': '2026-05-24T15:50:45.356Z',
  'low_24h': 3.17,
  'market_cap': 73948270590,
  'market_cap_change_24h': 592670649,

In [ ]:
print(f"Total Data of Cryptocurrencies: {len(data_crypto)}")

Total Data of Cryptocurrencies: 1250

**Column Rename**

In [ ]:
rename_columns = []

for i in data_crypto:
  rename_columns.append(dict(
      coin_id = i['id'],
      symbol = i['symbol'],
      coin_name = i['name'],
      current_price = i['current_price'],
      market_cap = i['market_cap'],
      market_cap_rank = i['market_cap_rank'],
      total_volume = i['total_volume'],
      circulating_supply = i['circulating_supply'],
      total_supply = i['total_supply'],
      ath = i['ath'],
      atl = i['atl'],
      last_updated = i['last_updated']
      ))

In [ ]:
pprint.pprint(rename_columns)

[{'ath': 11187013,
  'atl': 3993.42,
  'circulating_supply': 20033796.0,
  'coin_id': 'bitcoin',
  'coin_name': 'Bitcoin',
  'current_price': 7308304,
  'last_updated': '2026-05-24T15:50:44.026Z',
  'market_cap': 146386017371486,
  'market_cap_rank': 1,
  'symbol': 'btc',
  'total_supply': 20033812.0,
  'total_volume': 3076641747343},
 {'ath': 431946,
  'atl': 28.13,
  'circulating_supply': 120685539.9707651,
  'coin_id': 'ethereum',
  'coin_name': 'Ethereum',
  'current_price': 200378,
  'last_updated': '2026-05-24T15:50:42.835Z',
  'market_cap': 24171984843745,
  'market_cap_rank': 2,
  'symbol': 'eth',
  'total_supply': 120685539.9707651,
  'total_volume': 1266676989227},
 {'ath': 105.52,
  'atl': 36.86,
  'circulating_supply': 189721145805.9203,
  'coin_id': 'tether',
  'coin_name': 'Tether',
  'current_price': 95.59,
  'last_updated': '2026-05-24T15:50:43.161Z',
  'market_cap': 18134047627886,
  'market_cap_rank': 3,
  'symbol': 'usdt',
  'total_supply': 195188087011.4462,
  'total_volume': 4368704898282},
 {'ath': 121422,
  'atl': 2.58,
  'circulating_supply': 134784946.87,
  'coin_id': 'binancecoin',
  'coin_name': 'BNB',
  'current_price': 62682,
  'last_updated': '2026-05-24T15:50:44.003Z',
  'market_cap': 8446532286283,
  'market_cap_rank': 4,
  'symbol': 'bnb',
  'total_supply': 134784944.32,
  'total_volume': 65614528770},
 {'ath': 313.99,
  'atl': 0.159343,
  'circulating_supply': 61858321245.0,
  'coin_id': 'ripple',
  'coin_name': 'XRP',
  'current_price': 128.98,
  'last_updated': '2026-05-24T15:50:43.908Z',
  'market_cap': 7981145342833,
  'market_cap_rank': 5,
  'symbol': 'xrp',
  'total_supply': 99985662685.0,
  'total_volume': 131052848373},
 {'ath': 96.98,
  'atl': 65.31,
  'circulating_supply': 76433067144.85255,
  'coin_id': 'usd-coin',
  'coin_name': 'USDC',
  'current_price': 95.67,
  'last_updated': '2026-05-24T15:50:44.789Z',
  'market_cap': 7313713649235,
  'market_cap_rank': 6,
  'symbol': 'usdc',
  'total_supply': 76431607223.50403,
  'total_volume': 927080008295},
 {'ath': 25396,
  'atl': 38.03,
  'circulating_supply': 578098853.5945314,
  'coin_id': 'solana',
  'coin_name': 'Solana',
  'current_price': 8159.19,
  'last_updated': '2026-05-24T15:50:43.635Z',
  'market_cap': 4715132292418,
  'market_cap_rank': 7,
  'symbol': 'sol',
  'total_supply': 627007423.1525741,
  'total_volume': 251118010707},
 {'ath': 36.53,
  'atl': 0.117589,
  'circulating_supply': 94804720740.6219,
  'coin_id': 'tron',
  'coin_name': 'TRON',
  'current_price': 34.97,
  'last_updated': '2026-05-24T15:50:41.309Z',
  'market_cap': 3315695110115,
  'market_cap_rank': 8,
  'symbol': 'trx',
  'total_supply': 94807953257.69919,
  'total_volume': 43313747786},
 {'ath': 100.4,
  'atl': 13.78,
  'circulating_supply': 18079770536.887,
  'coin_id': 'figure-heloc',
  'coin_name': 'Figure Heloc',
  'current_price': 98.57,
  'last_updated': '2026-05-24T03:06:45.343Z',
  'market_cap': 1782149944364,
  'market_cap_rank': 9,
  'symbol': 'figr_heloc',
  'total_supply': 18079770536.887,
  'total_volume': 10151878},
 {'ath': 53.62,
  'atl': 0.00552883,
  'circulating_supply': 154372206383.7052,
  'coin_id': 'dogecoin',
  'coin_name': 'Dogecoin',
  'current_price': 9.75,
  'last_updated': '2026-05-24T15:50:43.904Z',
  'market_cap': 1504990371577,
  'market_cap_rank': 10,
  'symbol': 'doge',
  'total_supply': 170084603126.5791,
  'total_volume': 66426758963},
 {'ath': 6151.13,
  'atl': 321.88,
  'circulating_supply': 238385315.9541414,
  'coin_id': 'hyperliquid',
  'coin_name': 'Hyperliquid',
  'current_price': 6089.03,
  'last_updated': '2026-05-24T15:50:43.693Z',
  'market_cap': 1448002731593,
  'market_cap_rank': 11,
  'symbol': 'hype',
  'total_supply': 962274028.9541414,
  'total_volume': 117577835209},
 {'ath': 107.5,
  'atl': 79.67,
  'circulating_supply': 11137719564.26634,
  'coin_id': 'usds',
  'coin_name': 'USDS',
  'current_price': 95.65,
  'last_updated': '2026-05-24T15:50:43.629Z',
  'market_cap': 1065270069740,
  'market_cap_rank': 12,
  'symbol': 'usds',
  'total_supply': 11140584915.09768,
  'total_volume': 1479260502},
 {'ath': 211171,
  'atl': 1342.38,
  'circulating_supply': 16688225.1655448,
  'coin_id': 'zcash',
  'coin_name': 'Zcash',
  'current_price': 63059,
  'last_updated': '2026-05-24T15:50:44.260Z',
  'market_cap': 1050950478259,
  'market_cap_rank': 13,
  'symbol': 'zec',
  'total_supply': 16688225.1655448,
  'total_volume': 77819571095},
 {'ath': 1004.84,
  'atl': 56.97,
  'circulating_supply': 920557129.9,
  'coin_id': 'leo-token',
  'coin_name': 'LEO Token',
  'current_price': 959.99,
  'last_updated': '2026-05-24T15:50:44.058Z',
  'market_cap': 883730613959,
  'market_cap_rank': 14,
  'symbol': 'leo',
  'total_supply': 985239504.0,
  'total_volume': 29171687},
 {'ath': 225.26,
  'atl': 1.38,
  'circulating_supply': 37001084154.71531,
  'coin_id': 'cardano',
  'coin_name': 'Cardano',
  'current_price': 23.23,
  'last_updated': '2026-05-24T15:50:26.533Z',
  'market_cap': 859452927743,
  'market_cap_rank': 15,
  'symbol': 'ada',
  'total_supply': 45000000000.0,
  'total_volume': 28951389938},
 {'ath': 72026,
  'atl': 13.57,
  'circulating_supply': 18446744.07370955,
  'coin_id': 'monero',
  'coin_name': 'Monero',
  'current_price': 37436,
  'last_updated': '2026-05-24T15:50:45.582Z',
  'market_cap': 690297446998,
  'market_cap_rank': 16,
  'symbol': 'xmr',
  'total_supply': 18446744.07370955,
  'total_volume': 7636066882},
 {'ath': 242198,
  'atl': 5536.54,
  'circulating_supply': 20038790.52165078,
  'coin_id': 'bitcoin-cash',
  'coin_name': 'Bitcoin Cash',
  'current_price': 33442,
  'last_updated': '2026-05-24T15:50:26.115Z',
  'market_cap': 670250122485,
  'market_cap_rank': 17,
  'symbol': 'bch',
  'total_supply': 20038812.39665078,
  'total_volume': 33899343093},
 {'ath': 3862.15,
  'atl': 9.55,
  'circulating_supply': 727099970.4255477,
  'coin_id': 'chainlink',
  'coin_name': 'Chainlink',
  'current_price': 901.86,
  'last_updated': '2026-05-24T15:50:26.440Z',
  'market_cap': 655446791110,
  'market_cap_rank': 18,
  'symbol': 'link',
  'total_supply': 1000000000.0,
  'total_volume': 27156662223},
 {'ath': 5788.09,
  'atl': 245.71,
  'circulating_supply': 118458551.0,
  'coin_id': 'whitebit',
  'coin_name': 'WhiteBIT Coin',
  'current_price': 5388.19,
  'last_updated': '2026-05-24T15:50:42.222Z',
  'market_cap': 638269818133,
  'market_cap_rank': 19,
  'symbol': 'wbt',
  'total_supply': 294358550.0,
  'total_volume': 11160114781},
 {'ath': 17.72,
  'atl': 5.31,
  'circulating_supply': 38614942722.34335,
  'coin_id': 'canton-network',
  'coin_name': 'Canton',
  'current_price': 15.92,
  'last_updated': '2026-05-24T15:50:45.583Z',
  'market_cap': 614386906069,
  'market_cap_rank': 20,
  'symbol': 'cc',
  'total_supply': 38616169338.51177,
  'total_volume': 895609104},
 {'ath': 55.54,
  'atl': 0.02966141,
  'circulating_supply': 33528148789.57752,
  'coin_id': 'stellar',
  'coin_name': 'Stellar',
  'current_price': 14.06,
  'last_updated': '2026-05-24T15:50:40.802Z',
  'market_cap': 470986503474,
  'market_cap_rank': 21,
  'symbol': 'xlm',
  'total_supply': 50001786839.91458,
  'total_volume': 8057299098},
 {'ath': 96.97,
  'atl': 83.75,
  'circulating_supply': 4786390649.798471,
  'coin_id': 'usd1-wlfi',
  'coin_name': 'USD1',
  'current_price': 95.58,
  'last_updated': '2026-05-24T15:50:44.606Z',
  'market_cap': 457467285809,
  'market_cap_rank': 22,
  'symbol': 'usd1',
  'total_supply': 4786440649.798471,
  'total_volume': 100596899081},
 {'ath': 689.6,
  'atl': 38.25,
  'circulating_supply': 2694356840.120929,
  'coin_id': 'the-open-network',
  'coin_name': 'Toncoin',
  'current_price': 166.83,
  'last_updated': '2026-05-24T15:50:41.597Z',
  'market_cap': 449416165462,
  'market_cap_rank': 23,
  'symbol': 'ton',
  'total_supply': 5185282276.235128,
  'total_volume': 19381731942},
 {'ath': 96.97,
  'atl': 78.05,
  'circulating_supply': 4451953432.964992,
  'coin_id': 'ethena-usde',
  'coin_name': 'Ethena USDe',
  'current_price': 95.58,
  'last_updated': '2026-05-24T15:50:42.815Z',
  'market_cap': 425550103695,
  'market_cap_rank': 24,
  'symbol': 'usde',
  'total_supply': 4451953432.964992,
  'total_volume': 8776759505},
 {'ath': 96.98,
  'atl': 64.85,
  'circulating_supply': 4354615071.439,
  'coin_id': 'dai',
  'coin_name': 'Dai',
  'current_price': 95.67,
  'last_updated': '2026-05-24T15:50:26.322Z',
  'market_cap': 416597711374,
  'market_cap_rank': 25,
  'symbol': 'dai',
  'total_supply': 4360140886.711814,
  'total_volume': 11579340563},
 {'ath': 458.6,
  'atl': 30.36,
  'circulating_supply': 4005418369.566699,
  'coin_id': 'sui',
  'coin_name': 'Sui',
  'current_price': 99.91,
  'last_updated': '2026-05-24T15:50:42.080Z',
  'market_cap': 400170787791,
  'market_cap_rank': 26,
  'symbol': 'sui',
  'total_supply': 10000000000.0,
  'total_volume': 64068759832},
 {'ath': 30082,
  'atl': 72.12,
  'circulating_supply': 77202401.98347135,
  'coin_id': 'litecoin',
  'coin_name': 'Litecoin',
  'current_price': 5048.59,
  'last_updated': '2026-05-24T15:50:42.010Z',
  'market_cap': 389903076118,
  'market_cap_rank': 27,
  'symbol': 'ltc',
  'total_supply': 77204958.23347135,
  'total_volume': 20060594503},
 {'ath': 10772.35,
  'atl': 204.63,
  'circulating_supply': 431771961.1772119,
  'coin_id': 'avalanche-2',
  'coin_name': 'Avalanche',
  'current_price': 883.29,
  'last_updated': '2026-05-24T15:50:41.137Z',
  'market_cap': 381145954550,
  'market_cap_rank': 28,
  'symbol': 'avax',
  'total_supply': 463441061.1772119,
  'total_volume': 17511556323},
 {'ath': 41.81,
  'atl': 0.703644,
  'circulating_supply': 43373490530.38489,
  'coin_id': 'hedera-hashgraph',
  'coin_name': 'Hedera',
  'current_price': 8.49,
  'last_updated': '2026-05-24T15:50:43.163Z',
  'market_cap': 368054799228,
  'market_cap_rank': 29,
  'symbol': 'hbar',
  'total_supply': 50000000000.0,
  'total_volume': 4960197001},
 {'ath': 453.47,
  'atl': 4.05,
  'circulating_supply': 1304954247.430681,
  'coin_id': 'memecore',
  'coin_name': 'MemeCore',
  'current_price': 280.03,
  'last_updated': '2026-05-24T15:50:44.261Z',
  'market_cap': 365650915031,
  'market_cap_rank': 30,
  'symbol': 'm',
  'total_supply': 5372286439.832738,
  'total_volume': 620441116},
 {'ath': 100.8,
  'atl': 80.95,
  'circulating_supply': 3615224440.932459,
  'coin_id': 'paypal-usd',
  'coin_name': 'PayPal USD',
  'current_price': 95.67,
  'last_updated': '2026-05-24T15:50:42.447Z',
  'market_cap': 345868652166,
  'market_cap_rank': 31,
  'symbol': 'pyusd',
  'total_supply': 3615224440.932459,
  'total_volume': 3488766511},
 {'ath': 0.989197,
  'atl': 0.196087,
  'circulating_supply': 479110542855.1364,
  'coin_id': 'rain',
  'coin_name': 'Rain',
  'current_price': 0.70993,
  'last_updated': '2026-05-24T15:50:45.225Z',
  'market_cap': 340153477535,
  'market_cap_rank': 32,
  'symbol': 'rain',
  'total_supply': 1149896726504.505,
  'total_volume': 2214970136},
 {'ath': 0.00645756,
  'atl': 4.169e-09,
  'circulating_supply': 589243266197270.2,
  'coin_id': 'shiba-inu',
  'coin_name': 'Shiba Inu',
  'current_price': 0.00053427,
  'last_updated': '2026-05-24T15:50:41.131Z',
  'market_cap': 314561876646,
  'market_cap_rank': 33,
  'symbol': 'shib',
  'total_supply': 589499893114273.9,
  'total_volume': 6695015795},
 {'ath': 1518.16,
  'atl': 39.17,
  'circulating_supply': 1296351039.0,
  'coin_id': 'near',
  'coin_name': 'NEAR Protocol',
  'current_price': 233.25,
  'last_updated': '2026-05-24T15:50:40.972Z',
  'market_cap': 301526439787,
  'market_cap_rank': 34,
  'symbol': 'near',
  'total_supply': 1296351031.0,
  'total_volume': 97591563889},
 {'ath': 66.37,
  'atl': 0.864137,
  'circulating_supply': 44791304735.57631,
  'coin_id': 'crypto-com-chain',
  'coin_name': 'Cronos',
  'current_price': 6.59,
  'last_updated': '2026-05-24T15:50:25.964Z',
  'market_cap': 295420529141,
  'market_cap_rank': 35,
  'symbol': 'cro',
  'total_supply': 98657996172.03961,
  'total_volume': 818233742},
 {'ath': 108.39,
  'atl': 86.89,
  'circulating_supply': 2663603923.787158,
  'coin_id': 'hashnote-usyc',
  'coin_name': 'Circle USYC',
  'current_price': 107.76,
  'last_updated': '2026-05-23T17:47:24.985Z',
  'market_cap': 287039708901,
  'market_cap_rank': 36,
  'symbol': 'usyc',
  'total_supply': 2663603923.787158,
  'total_volume': 459392},
 {'ath': 143.35,
  'atl': 76.61,
  'circulating_supply': 2748812719.020469,
  'coin_id': 'global-dollar',
  'coin_name': 'Global Dollar',
  'current_price': 95.68,
  'last_updated': '2026-05-24T15:50:43.692Z',
  'market_cap': 263007037190,
  'market_cap_rank': 37,
  'symbol': 'usdg',
  'total_supply': 2748812719.020469,
  'total_volume': 4881925031},
 {'ath': 506656,
  'atl': 108167,
  'circulating_supply': 592823.659532,
  'coin_id': 'tether-gold',
  'coin_name': 'Tether Gold',
  'current_price': 431043,
  'last_updated': '2026-05-24T15:50:40.846Z',
  'market_cap': 255521860640,
  'market_cap_rank': 38,
  'symbol': 'xaut',
  'total_supply': 707747.089,
  'total_volume': 19948714630},
 {'ath': 62722,
  'atl': 2535.93,
  'circulating_supply': 9597491.0,
  'coin_id': 'bittensor',
  'coin_name': 'Bittensor',
  'current_price': 26357,
  'last_updated': '2026-05-24T15:50:42.381Z',
  'market_cap': 252861240590,
  'market_cap_rank': 39,
  'symbol': 'tao',
  'total_supply': 21000000.0,
  'total_volume': 20749195767},
 {'ath': 97.01,
  'atl': 83.81,
  'circulating_supply': 2511778552.860449,
  'coin_id': 'blackrock-usd-institutional-digital-liquidity-fund',
  'coin_name': 'BlackRock USD Institutional Digital Liquidity Fund',
  'current_price': 95.7,
  'last_updated': '2026-05-24T15:50:11.693Z',
  'market_cap': 240378405627,
  'market_cap_rank': 40,
  'symbol': 'buidl',
  'total_supply': 2511778552.860449,
  'total_volume': None},
 {'ath': 253.43,
  'atl': 25.64,
  'circulating_supply': 3302294382.53684,
  'coin_id': 'mantle',
  'coin_name': 'Mantle',
  'current_price': 62.45,
  'last_updated': '2026-05-24T15:50:42.520Z',
  'market_cap': 206219195821,
  'market_cap_rank': 41,
  'symbol': 'mnt',
  'total_supply': 6219316794.889999,
  'total_volume': 2657354055},
 {'ath': 181.52,
  'atl': 6.83,
  'circulating_supply': 4869330647.0,
  'coin_id': 'ondo-finance',
  'coin_name': 'Ondo',
  'current_price': 42.38,
  'last_updated': '2026-05-24T15:50:42.101Z',
  'market_cap': 206121562016,
  'market_cap_rank': 42,
  'symbol': 'ondo',
  'total_supply': 10000000000.0,
  'total_volume': 31794600035},
 {'ath': 3333.06,
  'atl': 75.81,
  'circulating_supply': 635699562.7428479,
  'coin_id': 'uniswap',
  'coin_name': 'Uniswap',
  'current_price': 323.98,
  'last_updated': '2026-05-24T15:50:41.757Z',
  'market_cap': 205888395550,
  'market_cap_rank': 43,
  'symbol': 'uni',
  'total_supply': 895334420.0329479,
  'total_volume': 11846948456},
 {'ath': 110.62,
  'atl': 77.42,
  'circulating_supply': 1889179688.172766,
  'coin_id': 'ondo-us-dollar-yield',
  'coin_name': 'Ondo US Dollar Yield',
  'current_price': 108.84,
  'last_updated': '2026-05-24T15:50:43.011Z',
  'market_cap': 205605566707,
  'market_cap_rank': 44,
  'symbol': 'usdy',
  'total_supply': 1889179688.172766,
  'total_volume': 138590042},
 {'ath': 4095.22,
  'atl': 103.91,
  'circulating_supply': 1685286630.383482,
  'coin_id': 'polkadot',
  'coin_name': 'Polkadot',
  'current_price': 120.65,
  'last_updated': '2026-05-24T15:50:41.094Z',
  'market_cap': 203269632527,
  'market_cap_rank': 45,
  'symbol': 'dot',
  'total_supply': 1685290894.794631,
  'total_volume': 13105577203},
 {'ath': 516779,
  'atl': 100361,
  'circulating_supply': 470301.37,
  'coin_id': 'pax-gold',
  'coin_name': 'PAX Gold',
  'current_price': 432263,
  'last_updated': '2026-05-24T15:50:26.286Z',
  'market_cap': 203267724908,
  'market_cap_rank': 46,
  'symbol': 'paxg',
  'total_supply': 470301.37,
  'total_volume': 10023294350},
 {'ath': 29.22,
  'atl': 4.9,
  'circulating_supply': 31773134306.0,
  'coin_id': 'world-liberty-financial',
  'coin_name': 'World Liberty Financial',
  'current_price': 5.9,
  'last_updated': '2026-05-24T15:50:43.971Z',
  'market_cap': 187289112999,
  'market_cap_rank': 47,
  'symbol': 'wlfi',
  'total_supply': 100000000000.0,
  'total_volume': 2941231216},
 {'ath': 213.7,
  'atl': 8.76,
  'circulating_supply': 2579922243.4698935,
  'coin_id': 'aster-2',
  'coin_name': 'Aster',
  'current_price': 67.8,
  'last_updated': '2026-05-24T15:50:45.506Z',
  'market_cap': 174601420984,
  'market_cap_rank': 48,
  'symbol': 'aster',
  'total_supply': 7822218820.515041,
  'total_volume': 14559512365},
 {'ath': 0.00031771,
  'atl': 6.739e-05,
  'circulating_supply': 905707664073577.8,
  'coin_id': 'htx-dao',
  'coin_name': 'HTX DAO',
  'current_price': 0.00019226,
  'last_updated': '2026-05-24T15:50:43.462Z',
  'market_cap': 174123333410,
  'market_cap_rank': 49,
  'symbol': 'htx',
  'total_supply': 905707664073577.8,
  'total_volume': 1413592548},
 {'ath': 96.79,
  'atl': 80.47,
  'circulating_supply': 1784655676.344749,
  'coin_id': 'falcon-finance',
  'coin_name': 'Falcon USD',
  'current_price': 95.39,
  'last_updated': '2026-05-24T15:50:44.184Z',
  'market_cap': 170234003987,
  'market_cap_rank': 50,
  'symbol': 'usdf',
  'total_supply': 1784655676.344749,
  'total_volume': 133730542},
 {'ath': 97.01,
  'atl': 81.72,
  'circulating_supply': 1749663362.596745,
  'coin_id': 'ripple-usd',
  'coin_name': 'Ripple USD',
  'current_price': 95.71,
  'last_updated': '2026-05-24T15:50:43.437Z',
  'market_cap': 167465878885,
  'market_cap_rank': 51,
  'symbol': 'rlusd',
  'total_supply': 1749663362.596745,
  'total_volume': 8910509348},
 {'ath': 20297,
  'atl': 40.86,
  'circulating_supply': 21000000.0,
  'coin_id': 'okb',
  'coin_name': 'OKB',
  'current_price': 7884.57,
  'last_updated': '2026-05-24T15:50:43.606Z',
  'market_cap': 165559057149,
  'market_cap_rank': 52,
  'symbol': 'okb',
  'total_supply': 21000000.0,
  'total_volume': 864745778},
 {'ath': 8.62,
  'atl': 3.12,
  'circulating_supply': 23227109059.381252,
  'coin_id': 'sky',
  'coin_name': 'Sky',
  'current_price': 6.68,
  'last_updated': '2026-05-24T15:50:43.529Z',
  'market_cap': 154981014009,
  'market_cap_rank': 53,
  'symbol': 'sky',
  'total_supply': 23462665147.36596,
  'total_volume': 703422845},
 {'ath': 260.4,
  'atl': 11.91,
  'circulating_supply': 10592041067.84851,
  'coin_id': 'pi-network',
  'coin_name': 'Pi Network',
  'current_price': 14.32,
  'last_updated': '2026-05-24T15:50:44.140Z',
  'market_cap': 151646165864,
  'market_cap_rank': 54,
  'symbol': 'pi',
  'total_supply': 16295447796.69001,
  'total_volume': 971608863},
 {'ath': 96.99,
  'atl': 72.35,
  'circulating_supply': 1512858460.0,
  'coin_id': 'usdd',
  'coin_name': 'USDD',
  'current_price': 95.59,
  'last_updated': '2026-05-24T15:50:41.931Z',
  'market_cap': 144607507907,
  'market_cap_rank': 55,
  'symbol': 'usdd',
  'total_supply': 1512808460.0,
  'total_volume': 220908411},
 {'ath': 0.00237833,
  'atl': 4.52e-06,
  'circulating_supply': 420690000000000.0,
  'coin_id': 'pepe',
  'coin_name': 'Pepe',
  'current_price': 0.00034224,
  'last_updated': '2026-05-24T15:50:42.366Z',
  'market_cap': 143915962587,
  'market_cap_rank': 56,
  'symbol': 'pepe',
  'total_supply': 420690000000000.0,
  'total_volume': 15232014668},
 {'ath': 51433,
  'atl': 183.62,
  'circulating_supply': 553022826.3414009,
  'coin_id': 'internet-computer',
  'coin_name': 'Internet Computer',
  'current_price': 244.19,
  'last_updated': '2026-05-24T15:50:41.567Z',
  'market_cap': 134995860562,
  'market_cap_rank': 57,
  'symbol': 'icp',
  'total_supply': 553022826.3414009,
  'total_volume': 5496175444},
 {'ath': 361.23,
  'atl': 60.2,
  'circulating_supply': 633139698.5374187,
  'coin_id': 'morpho',
  'coin_name': 'Morpho',
  'current_price': 212.62,
  'last_updated': '2026-05-24T15:50:42.252Z',
  'market_cap': 134592832613,
  'market_cap_rank': 58,
  'symbol': 'morpho',
  'total_supply': 1000000000.0,
  'total_volume': 1689718222},
 {'ath': 12296.58,
  'atl': 41.44,

In [ ]:
print(f"Total data for filtered columns: {len(rename_columns)}")

Total data for filtered columns: 1250

In [ ]:
crypto_df = pd.DataFrame(rename_columns) #visualizing data in pandas
crypto_df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.00,146386017371486,1,3.076642e+12,2.003380e+07,2.003381e+07,11187013.00,3993.420000,2026-05-24T15:50:44.026Z
1,ethereum,eth,Ethereum,200378.00,24171984843745,2,1.266677e+12,1.206855e+08,1.206855e+08,431946.00,28.130000,2026-05-24T15:50:42.835Z
2,tether,usdt,Tether,95.59,18134047627886,3,4.368705e+12,1.897211e+11,1.951881e+11,105.52,36.860000,2026-05-24T15:50:43.161Z
3,binancecoin,bnb,BNB,62682.00,8446532286283,4,6.561453e+10,1.347849e+08,1.347849e+08,121422.00,2.580000,2026-05-24T15:50:44.003Z
4,ripple,xrp,XRP,128.98,7981145342833,5,1.310528e+11,6.185832e+10,9.998566e+10,313.99,0.159343,2026-05-24T15:50:43.908Z
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,vaulta,a,Vaulta,7.49,12314406425,246,1.145042e+09,1.643370e+09,2.100000e+09,66.55,6.410000,2026-05-24T15:50:44.512Z
1246,instadapp,fluid,Fluid,157.93,12302563147,247,2.787547e+08,7.794700e+07,1.000000e+08,1799.83,30.330000,2026-05-24T15:50:41.360Z
1247,wemix-token,wemix,WEMIX,26.56,12275525199,248,1.013455e+08,4.622778e+08,5.524732e+08,1836.35,9.550000,2026-05-24T15:50:41.231Z
1248,1inch,1inch,1INCH,8.68,12195153213,249,6.209907e+08,1.405574e+09,1.500000e+09,648.39,7.550000,2026-05-24T15:50:41.289Z
1249,theo-short-duration-us-treasury-fund,thbill,Theo Short Duration US Treasury Fund,98.06,12111736268,250,1.638317e+07,1.236424e+08,1.236424e+08,100.55,80.460000,2026-05-24T15:50:44.963Z

In [ ]:
# date only extract from last_updated
crypto_df["last_updated"] = pd.to_datetime(crypto_df["last_updated"]).dt.date
crypto_df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.00,146386017371486,1,3.076642e+12,2.003380e+07,2.003381e+07,11187013.00,3993.420000,2026-05-24
1,ethereum,eth,Ethereum,200378.00,24171984843745,2,1.266677e+12,1.206855e+08,1.206855e+08,431946.00,28.130000,2026-05-24
2,tether,usdt,Tether,95.59,18134047627886,3,4.368705e+12,1.897211e+11,1.951881e+11,105.52,36.860000,2026-05-24
3,binancecoin,bnb,BNB,62682.00,8446532286283,4,6.561453e+10,1.347849e+08,1.347849e+08,121422.00,2.580000,2026-05-24
4,ripple,xrp,XRP,128.98,7981145342833,5,1.310528e+11,6.185832e+10,9.998566e+10,313.99,0.159343,2026-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,vaulta,a,Vaulta,7.49,12314406425,246,1.145042e+09,1.643370e+09,2.100000e+09,66.55,6.410000,2026-05-24
1246,instadapp,fluid,Fluid,157.93,12302563147,247,2.787547e+08,7.794700e+07,1.000000e+08,1799.83,30.330000,2026-05-24
1247,wemix-token,wemix,WEMIX,26.56,12275525199,248,1.013455e+08,4.622778e+08,5.524732e+08,1836.35,9.550000,2026-05-24
1248,1inch,1inch,1INCH,8.68,12195153213,249,6.209907e+08,1.405574e+09,1.500000e+09,648.39,7.550000,2026-05-24
1249,theo-short-duration-us-treasury-fund,thbill,Theo Short Duration US Treasury Fund,98.06,12111736268,250,1.638317e+07,1.236424e+08,1.236424e+08,100.55,80.460000,2026-05-24

In [ ]:
crypto_df.head()

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.00,146386017371486,1,3.076642e+12,2.003380e+07,2.003381e+07,11187013.00,3993.420000,2026-05-24
1,ethereum,eth,Ethereum,200378.00,24171984843745,2,1.266677e+12,1.206855e+08,1.206855e+08,431946.00,28.130000,2026-05-24
2,tether,usdt,Tether,95.59,18134047627886,3,4.368705e+12,1.897211e+11,1.951881e+11,105.52,36.860000,2026-05-24
3,binancecoin,bnb,BNB,62682.00,8446532286283,4,6.561453e+10,1.347849e+08,1.347849e+08,121422.00,2.580000,2026-05-24
4,ripple,xrp,XRP,128.98,7981145342833,5,1.310528e+11,6.185832e+10,9.998566e+10,313.99,0.159343,2026-05-24

**Top Coins Historical Prices**

In [ ]:
# getting data for top coins price history
all_coins = []

coin_ids = ['bitcoin','ethereum','tether','binancecoin','ripple']

for i in coin_ids:
  url = f"https://api.coingecko.com/api/v3/coins/{i}/market_chart?vs_currency=inr&days=365"
  response=requests.get(url)

  if response.status_code == 200:
    coins=response.json()
    prices = coins["prices"]#extracting data to table and converting ms to datestamp
    time.sleep(5)

    for ts, price in prices:
      all_coins.append({"coin_id": i,"date": pd.to_datetime(ts, unit="ms"),"price": price})

top_coins_df = pd.DataFrame(all_coins)

In [ ]:
top_coins_df

      coin_id                date         price
0     bitcoin 2025-05-25 00:00:00  9.173866e+06
1     bitcoin 2025-05-26 00:00:00  9.274976e+06
2     bitcoin 2025-05-27 00:00:00  9.314437e+06
3     bitcoin 2025-05-28 00:00:00  9.310175e+06
4     bitcoin 2025-05-29 00:00:00  9.208281e+06
..        ...                 ...           ...
727  ethereum 2026-05-21 00:00:00  2.053445e+05
728  ethereum 2026-05-22 00:00:00  2.050139e+05
729  ethereum 2026-05-23 00:00:00  1.976018e+05
730  ethereum 2026-05-24 00:00:00  2.024743e+05
731  ethereum 2026-05-24 15:54:11  2.003096e+05

[732 rows x 3 columns]

In [ ]:
# date only extract from datestamp
top_coins_df["date"] = pd.to_datetime(top_coins_df["date"]).dt.date
top_coins_df

      coin_id        date         price
0     bitcoin  2025-05-25  9.173866e+06
1     bitcoin  2025-05-26  9.274976e+06
2     bitcoin  2025-05-27  9.314437e+06
3     bitcoin  2025-05-28  9.310175e+06
4     bitcoin  2025-05-29  9.208281e+06
..        ...         ...           ...
727  ethereum  2026-05-21  2.053445e+05
728  ethereum  2026-05-22  2.050139e+05
729  ethereum  2026-05-23  1.976018e+05
730  ethereum  2026-05-24  2.024743e+05
731  ethereum  2026-05-24  2.003096e+05

[732 rows x 3 columns]

**Oil Prices(WTI Crude)**

In [ ]:
# data collection from csv file - github link
import pandas as pd

oil_df = pd.read_csv("https://raw.githubusercontent.com/datasets/oil-prices/main/data/wti-daily.csv")
oil_df

             Date   Price
0      1986-01-02   25.56
1      1986-01-03   26.00
2      1986-01-06   26.53
3      1986-01-07   25.85
4      1986-01-08   25.87
...           ...     ...
10158  2026-05-12  105.78
10159  2026-05-13  104.52
10160  2026-05-14  104.66
10161  2026-05-15  108.99
10162  2026-05-18  112.25

[10163 rows x 2 columns]

In [ ]:
# extracting data from Jan 2020 - Feb 2026 ==> mentioned in project file
oil_df['Date'] = pd.to_datetime(oil_df['Date'])
start_date = pd.to_datetime('2020-01-01')
end_date   = pd.to_datetime('2026-02-23')

oil_df = oil_df[(oil_df['Date'] >= start_date) & (oil_df['Date'] <= end_date)]

oil_df

            Date  Price
8569  2020-01-02  61.17
8570  2020-01-03  63.00
8571  2020-01-06  63.27
8572  2020-01-07  62.70
8573  2020-01-08  59.65
...          ...    ...
10099 2026-02-17  62.53
10100 2026-02-18  65.33
10101 2026-02-19  66.66
10102 2026-02-20  66.69
10103 2026-02-23  66.36

[1535 rows x 2 columns]

In [ ]:
oil_df = oil_df.reset_index(drop=True)
oil_df

           Date  Price
0    2020-01-02  61.17
1    2020-01-03  63.00
2    2020-01-06  63.27
3    2020-01-07  62.70
4    2020-01-08  59.65
...         ...    ...
1530 2026-02-17  62.53
1531 2026-02-18  65.33
1532 2026-02-19  66.66
1533 2026-02-20  66.69
1534 2026-02-23  66.36

[1535 rows x 2 columns]

**Stock Prices (Yahoo Finance API)**

In [ ]:
# collect following stocks data from Yahoo Finance API
import yfinance as YF

In [ ]:
tickers = ["^GSPC", "^IXIC", "^NSEI"]
start_date = "2020-01-01"
end_date = "2026-02-23"

stk_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
stk_df.head()

/tmp/ipykernel_61188/823814597.py:5: FutureWarning: YF.download() has changed argument auto_adjust default to True
  stk_df = YF.download(tickers, start=start_date, end=end_date, group_by="ticker")
[*********************100%***********************]  3 of 3 completed

Ticker             ^NSEI                                                      \
Price               Open          High           Low         Close    Volume
Date
2020-01-01  12202.150391  12222.200195  12165.299805  12182.500000  304100.0
2020-01-02  12198.549805  12289.900391  12195.250000  12282.200195  407700.0
2020-01-03  12261.099609  12265.599609  12191.349609  12226.650391  428800.0
2020-01-06  12170.599609  12179.099609  11974.200195  11993.049805  396500.0
2020-01-07  12079.099609  12152.150391  12005.349609  12052.950195  447800.0

Ticker            ^IXIC                                                       \
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  9039.459961  9093.429688  9010.889648  9092.190430  2.862700e+09
2020-01-03  8976.429688  9065.759766  8976.429688  9020.769531  2.586520e+09
2020-01-06  8943.500000  9072.410156  8943.500000  9071.469727  2.810450e+09
2020-01-07  9076.639648  9091.929688  9042.549805  9068.580078  2.381740e+09

Ticker            ^GSPC
Price              Open         High          Low        Close        Volume
Date
2020-01-01          NaN          NaN          NaN          NaN           NaN
2020-01-02  3244.669922  3258.139893  3235.530029  3257.850098  3.459930e+09
2020-01-03  3226.360107  3246.149902  3222.340088  3234.850098  3.484700e+09
2020-01-06  3217.550049  3246.840088  3214.639893  3246.280029  3.702460e+09
2020-01-07  3241.860107  3244.909912  3232.429932  3237.179932  3.435910e+09

In [ ]:
# colleting data separately for easy undersating
# "^NSEI"
stocks1_df = stk_df["^NSEI"].reset_index()
stocks1_df.head()

Price,Date,Open,High,Low,Close,Volume
0,2020-01-01,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,12079.099609,12152.150391,12005.349609,12052.950195,447800.0

In [ ]:
# adding column ==> "tickers"
stocks1_df.insert(1, "Ticker", "^NSEI")
stocks1_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...,...
1588,2026-02-16,^NSEI,25423.599609,25697.000000,25372.699219,25682.750000,275800.0
1589,2026-02-17,^NSEI,25637.949219,25764.400391,25570.300781,25725.400391,344100.0
1590,2026-02-18,^NSEI,25752.650391,25828.050781,25645.150391,25819.349609,310200.0
1591,2026-02-19,^NSEI,25873.349609,25885.300781,25388.750000,25454.349609,298200.0
1592,2026-02-20,^NSEI,25406.550781,25663.550781,25379.750000,25571.250000,296600.0

In [ ]:
# finding nulls from collected data
print(stocks1_df.isnull().sum())

Price
Date       0
Ticker     0
Open      72
High      72
Low       72
Close     72
Volume    72
dtype: int64

In [ ]:
# remove null for clear undersating
stocks1_df = stocks1_df.dropna()

In [ ]:
stocks1_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,304100.0
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,407700.0
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,428800.0
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,396500.0
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,447800.0
...,...,...,...,...,...,...,...
1588,2026-02-16,^NSEI,25423.599609,25697.000000,25372.699219,25682.750000,275800.0
1589,2026-02-17,^NSEI,25637.949219,25764.400391,25570.300781,25725.400391,344100.0
1590,2026-02-18,^NSEI,25752.650391,25828.050781,25645.150391,25819.349609,310200.0
1591,2026-02-19,^NSEI,25873.349609,25885.300781,25388.750000,25454.349609,298200.0
1592,2026-02-20,^NSEI,25406.550781,25663.550781,25379.750000,25571.250000,296600.0

In [ ]:
print(stocks1_df.isnull().sum())

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
# "^IXIC"
stocks2_df = stk_df["^IXIC"].reset_index()

stocks2_df.insert(1, "Ticker", "^IXIC") # inserting column

stocks2_df = stocks2_df.dropna() # removing nulls

stocks2_df

Price,Date,Ticker,Open,High,Low,Close,Volume
1,2020-01-02,^IXIC,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
2,2020-01-03,^IXIC,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
3,2020-01-06,^IXIC,8943.500000,9072.410156,8943.500000,9071.469727,2.810450e+09
4,2020-01-07,^IXIC,9076.639648,9091.929688,9042.549805,9068.580078,2.381740e+09
5,2020-01-08,^IXIC,9068.030273,9168.889648,9059.379883,9129.240234,2.472620e+09
...,...,...,...,...,...,...,...
1587,2026-02-13,^IXIC,22561.460938,22742.060547,22402.380859,22546.669922,7.964830e+09
1589,2026-02-17,^IXIC,22394.759766,22690.830078,22256.759766,22578.380859,7.654300e+09
1590,2026-02-18,^IXIC,22629.849609,22895.960938,22597.769531,22753.630859,7.705590e+09
1591,2026-02-19,^IXIC,22639.880859,22768.830078,22583.609375,22682.730469,6.984780e+09
1592,2026-02-20,^IXIC,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09

In [ ]:
stocks2_df.isnull().sum() # checking null values are removed

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
# "^GSPC"
stocks3_df = stk_df["^GSPC"].reset_index()

stocks3_df.insert(1, "Ticker", "^GSPC") # inserting column

stocks3_df = stocks3_df.dropna() # removing nulls

stocks3_df

Price,Date,Ticker,Open,High,Low,Close,Volume
1,2020-01-02,^GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
2,2020-01-03,^GSPC,3226.360107,3246.149902,3222.340088,3234.850098,3.484700e+09
3,2020-01-06,^GSPC,3217.550049,3246.840088,3214.639893,3246.280029,3.702460e+09
4,2020-01-07,^GSPC,3241.860107,3244.909912,3232.429932,3237.179932,3.435910e+09
5,2020-01-08,^GSPC,3238.590088,3267.070068,3236.669922,3253.050049,3.726840e+09
...,...,...,...,...,...,...,...
1587,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
1589,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
1590,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
1591,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
1592,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [ ]:
stocks3_df.isnull().sum() # checking null values are removed

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
# merging all stocks after cleaning nulls and adding column for comparision
stks_df = pd.concat([stocks1_df, stocks2_df, stocks3_df])
stks_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
1587,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
1589,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
1590,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
1591,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
1592,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [ ]:
stks_df.isnull().sum() # verify nulls after merging all three data

Price
Date      0
Ticker    0
Open      0
High      0
Low       0
Close     0
Volume    0
dtype: int64

In [ ]:
stks_df

Price,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
1587,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
1589,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
1590,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
1591,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
1592,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

# **Saving data into csv**

In [ ]:
crypto_df = crypto_df.to_csv("crypto_df.csv", index=False)

top_coins_df = top_coins_df.to_csv("top_coins_df.csv", index=False)

oil_df = oil_df.to_csv("oil_df.csv", index=False)

stks_df = stks_df.to_csv("stks_df.csv", index=False)

In [ ]:
# reading collected csv data
crypto_df = pd.read_csv("crypto_df.csv")
crypto_df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.00,146386017371486,1,3.076642e+12,2.003380e+07,2.003381e+07,11187013.00,3993.420000,2026-05-24
1,ethereum,eth,Ethereum,200378.00,24171984843745,2,1.266677e+12,1.206855e+08,1.206855e+08,431946.00,28.130000,2026-05-24
2,tether,usdt,Tether,95.59,18134047627886,3,4.368705e+12,1.897211e+11,1.951881e+11,105.52,36.860000,2026-05-24
3,binancecoin,bnb,BNB,62682.00,8446532286283,4,6.561453e+10,1.347849e+08,1.347849e+08,121422.00,2.580000,2026-05-24
4,ripple,xrp,XRP,128.98,7981145342833,5,1.310528e+11,6.185832e+10,9.998566e+10,313.99,0.159343,2026-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,vaulta,a,Vaulta,7.49,12314406425,246,1.145042e+09,1.643370e+09,2.100000e+09,66.55,6.410000,2026-05-24
1246,instadapp,fluid,Fluid,157.93,12302563147,247,2.787547e+08,7.794700e+07,1.000000e+08,1799.83,30.330000,2026-05-24
1247,wemix-token,wemix,WEMIX,26.56,12275525199,248,1.013455e+08,4.622778e+08,5.524732e+08,1836.35,9.550000,2026-05-24
1248,1inch,1inch,1INCH,8.68,12195153213,249,6.209907e+08,1.405574e+09,1.500000e+09,648.39,7.550000,2026-05-24
1249,theo-short-duration-us-treasury-fund,thbill,Theo Short Duration US Treasury Fund,98.06,12111736268,250,1.638317e+07,1.236424e+08,1.236424e+08,100.55,80.460000,2026-05-24

In [ ]:
top_coins_df = pd.read_csv("top_coins_df.csv")
top_coins_df

      coin_id        date         price
0     bitcoin  2025-05-25  9.173866e+06
1     bitcoin  2025-05-26  9.274976e+06
2     bitcoin  2025-05-27  9.314437e+06
3     bitcoin  2025-05-28  9.310175e+06
4     bitcoin  2025-05-29  9.208281e+06
..        ...         ...           ...
727  ethereum  2026-05-21  2.053445e+05
728  ethereum  2026-05-22  2.050139e+05
729  ethereum  2026-05-23  1.976018e+05
730  ethereum  2026-05-24  2.024743e+05
731  ethereum  2026-05-24  2.003096e+05

[732 rows x 3 columns]

In [ ]:
oil_df = pd.read_csv("oil_df.csv")
oil_df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1530  2026-02-17  62.53
1531  2026-02-18  65.33
1532  2026-02-19  66.66
1533  2026-02-20  66.69
1534  2026-02-23  66.36

[1535 rows x 2 columns]

In [ ]:
stks_df = pd.read_csv("stks_df.csv")
stks_df

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
4600,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
4601,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
4602,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
4603,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
4604,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

# **SQL connection Table Creation**

In [ ]:
pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.7.0)

In [ ]:
import mysql.connector

In [ ]:
conn = mysql.connector.connect(
    host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com",
    user = "3fXqCw6nxxduoS8.root",
    password = "u2dctQHUVuOXcZhS",
    port = 4000
)

In [ ]:
cma = conn.cursor()

In [ ]:
cma.execute("DROP DATABASE IF EXISTS Cross_Market_Analysis")
conn.commit()

In [ ]:
cma.execute("CREATE DATABASE Cross_Market_Analysis")
conn.commit()

In [ ]:
cma.execute("show databases")
cma.fetchall()

[('INFORMATION_SCHEMA',),
 ('Cross_Market_Analysis',),
 ('Global_Literacy',),
 ('PERFORMANCE_SCHEMA',),
 ('mysql',)]

In [ ]:
cma.execute("use Cross_Market_Analysis")

In [ ]:
# creating tables for cryptocurrencies

cma.execute("""CREATE TABLE cryptocurrencies
                 (id VARCHAR(50) PRIMARY KEY,
                 symbol VARCHAR(10),
                 name VARCHAR(100),
                 current_price DECIMAL(18, 6),
                 market_cap BIGINT,
                 market_cap_rank INT,
                 total_volume BIGINT,
                 circulating_supply DECIMAL(20, 6),
                 total_supply DECIMAL(20, 6),
                 ath DECIMAL(18, 6),
                 atl DECIMAL(18, 6),
                 date DATE
                 );

                 """)
conn.commit() # apply the changes to the sqlite3

In [ ]:
#creating table for Crypto_prices

cma.execute("""CREATE TABLE top_coins
                 (coin_id VARCHAR(50),
                 date DATE,
                 price DECIMAL(18, 6)
                 );

                 """)
conn.commit()

In [ ]:
#creating table for Oil_prices

cma.execute("""CREATE TABLE oil_prices
                 (date DATE PRIMARY KEY,
                 price_INR DECIMAL(18, 6)
                 );

                 """)
conn.commit()

In [ ]:
#creating table for Stock_prices
cma.execute("""CREATE TABLE stk_prices
                 (date DATE,
                 open DECIMAL(18, 6),
                 high DECIMAL(18, 6),
                 low DECIMAL(18, 6),
                 close DECIMAL(18, 6),
                 volume BIGINT,
                 ticker VARCHAR(20)
                 );

                 """)
conn.commit()

In [ ]:
cma.execute("show tables")
cma.fetchall()

[('cryptocurrencies',), ('oil_prices',), ('stk_prices',), ('top_coins',)]

# **Pushing data frames in to SQL and create sql engine**

In [ ]:
pip install pandas sqlalchemy mysql-connector-python

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: sqlalchemy in /usr/local/lib/python3.12/dist-packages (2.0.49)
Requirement already satisfied: mysql-connector-python in /usr/local/lib/python3.12/dist-packages (9.7.0)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (3.4.0)
Requirement already satisfied: typing-extensions>=4.6.0 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy) (4.15.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine("mysql+mysqlconnector://3fXqCw6nxxduoS8.root:u2dctQHUVuOXcZhS@gateway01.ap-southeast-1.prod.aws.tidbcloud.com:4000/Cross_Market_Analysis")

In [ ]:
crypto_df.to_sql ("cryptocurrencies", con = engine, if_exists = "replace", index = False) # push crypto_df to sqlite

-1

In [ ]:
top_coins_df.to_sql ("top_coins", con = engine, if_exists = "replace", index = False)

-1

In [ ]:
oil_df.to_sql ("oil_prices", con = engine, if_exists = "replace", index = False)

-1

In [ ]:
stks_df.to_sql ("stks_prices", con = engine, if_exists = "replace", index = False)

-1

# **Querries where mentioned in project file**

### **Cryptocurrencies**

In [ ]:
# show/read cryptocurrencies table
df = pd.read_sql("SELECT * FROM  cryptocurrencies;", engine)
df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.00,146386017371486,1,3.076642e+12,2.003380e+07,2.003381e+07,11187013.00,3993.420000,2026-05-24
1,ethereum,eth,Ethereum,200378.00,24171984843745,2,1.266677e+12,1.206855e+08,1.206855e+08,431946.00,28.130000,2026-05-24
2,tether,usdt,Tether,95.59,18134047627886,3,4.368705e+12,1.897211e+11,1.951881e+11,105.52,36.860000,2026-05-24
3,binancecoin,bnb,BNB,62682.00,8446532286283,4,6.561453e+10,1.347849e+08,1.347849e+08,121422.00,2.580000,2026-05-24
4,ripple,xrp,XRP,128.98,7981145342833,5,1.310528e+11,6.185832e+10,9.998566e+10,313.99,0.159343,2026-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...
1245,vaulta,a,Vaulta,7.49,12314406425,246,1.145042e+09,1.643370e+09,2.100000e+09,66.55,6.410000,2026-05-24
1246,instadapp,fluid,Fluid,157.93,12302563147,247,2.787547e+08,7.794700e+07,1.000000e+08,1799.83,30.330000,2026-05-24
1247,wemix-token,wemix,WEMIX,26.56,12275525199,248,1.013455e+08,4.622778e+08,5.524732e+08,1836.35,9.550000,2026-05-24
1248,1inch,1inch,1INCH,8.68,12195153213,249,6.209907e+08,1.405574e+09,1.500000e+09,648.39,7.550000,2026-05-24
1249,theo-short-duration-us-treasury-fund,thbill,Theo Short Duration US Treasury Fund,98.06,12111736268,250,1.638317e+07,1.236424e+08,1.236424e+08,100.55,80.460000,2026-05-24

In [ ]:
# 1. Find the top 5 cryptocurrencies by market cap.
top_cryp = pd.read_sql (
    """SELECT coin_name, MAX(market_cap) AS market_cap FROM cryptocurrencies WHERE market_cap IS NOT NULL GROUP BY coin_name ORDER BY market_cap DESC LIMIT 5;""", engine)

top_cryp

  coin_name       market_cap
0   Bitcoin  146386017371486
1  Ethereum   24171984843745
2    Tether   18134047627886
3       BNB    8446532286283
4       XRP    7981145342833

In [ ]:
# 2. List all coins where circulating supply exceeds 90% of total supply.

cir_sup = pd.read_sql (
    """SELECT * FROM cryptocurrencies WHERE total_supply IS NOT NULL AND total_supply > 0 AND circulating_supply >= 0.9 * total_supply AND circulating_supply IS NOT NULL;""", engine)

cir_sup

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.00,146386017371486,1,3.076642e+12,2.003380e+07,2.003381e+07,11187013.00,3993.42,2026-05-24
1,ethereum,eth,Ethereum,200378.00,24171984843745,2,1.266677e+12,1.206855e+08,1.206855e+08,431946.00,28.13,2026-05-24
2,tether,usdt,Tether,95.59,18134047627886,3,4.368705e+12,1.897211e+11,1.951881e+11,105.52,36.86,2026-05-24
3,binancecoin,bnb,BNB,62682.00,8446532286283,4,6.561453e+10,1.347849e+08,1.347849e+08,121422.00,2.58,2026-05-24
4,usd-coin,usdc,USDC,95.67,7313713649235,6,9.270800e+11,7.643307e+10,7.643161e+10,96.98,65.31,2026-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...
720,tradable-latam-fintech-sstn,pc0000097,Tradable LatAm Fintech SSTN,95.70,12823863918,243,NaN,1.340000e+08,1.340000e+08,97.00,85.32,2026-05-24
721,frax-usd,frxusd,Frax USD,95.67,12747180230,244,5.318948e+08,1.332411e+08,1.332379e+08,96.99,83.77,2026-05-24
722,agora-dollar,ausd,AUSD,95.66,12361882467,245,3.517345e+09,1.292226e+08,1.292226e+08,96.99,80.49,2026-05-24
723,1inch,1inch,1INCH,8.68,12195153213,249,6.209907e+08,1.405574e+09,1.500000e+09,648.39,7.55,2026-05-24
724,theo-short-duration-us-treasury-fund,thbill,Theo Short Duration US Treasury Fund,98.06,12111736268,250,1.638317e+07,1.236424e+08,1.236424e+08,100.55,80.46,2026-05-24

In [ ]:
# 3. Get coins that are within 10% of their all-time-high (ATH).

ath = pd.read_sql(""" SELECT * FROM cryptocurrencies WHERE current_price >= 0.9 * ath
AND current_price IS NOT NULL ORDER BY current_price DESC;
""", engine)

ath

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,ousg,ousg,OUSG,11036.77,52943413128,99,0.000000e+00,4.797003e+06,4.797003e+06,11182.59,7844.420000,2026-05-24
1,ousg,ousg,OUSG,11036.77,52943413128,99,0.000000e+00,4.797003e+06,4.797003e+06,11182.59,7844.420000,2026-05-24
2,ousg,ousg,OUSG,11036.77,52943413128,99,0.000000e+00,4.797003e+06,4.797003e+06,11182.59,7844.420000,2026-05-24
3,ousg,ousg,OUSG,11036.77,52943413128,99,0.000000e+00,4.797003e+06,4.797003e+06,11182.59,7844.420000,2026-05-24
4,ousg,ousg,OUSG,11036.77,52943413128,99,0.000000e+00,4.797003e+06,4.797003e+06,11182.59,7844.420000,2026-05-24
...,...,...,...,...,...,...,...,...,...,...,...,...
275,tron,trx,TRON,34.97,3315695110115,8,4.331375e+10,9.480472e+10,9.480795e+10,36.53,0.117589,2026-05-24
276,tron,trx,TRON,34.97,3315695110115,8,4.331375e+10,9.480472e+10,9.480795e+10,36.53,0.117589,2026-05-24
277,tron,trx,TRON,34.97,3315695110115,8,4.331375e+10,9.480472e+10,9.480795e+10,36.53,0.117589,2026-05-24
278,tron,trx,TRON,34.97,3315695110115,8,4.331375e+10,9.480472e+10,9.480795e+10,36.53,0.117589,2026-05-24
279,tron,trx,TRON,34.97,3315695110115,8,4.331375e+10,9.480472e+10,9.480795e+10,36.53,0.117589,2026-05-24

In [ ]:
# 4. Find the average market cap rank of coins with volume above $1B.

df = pd.read_sql ("SELECT AVG(market_cap_rank) FROM cryptocurrencies WHERE total_volume > 1000000000 AND total_volume IS NOT NULL;", engine)

df

   AVG(market_cap_rank)
0              100.3481

In [ ]:
# 5. Get the most recently updated coin.

df = pd.read_sql ("SELECT * FROM cryptocurrencies ORDER BY last_updated DESC LIMIT 1;", engine)

df

,coin_id,symbol,coin_name,current_price,market_cap,market_cap_rank,total_volume,circulating_supply,total_supply,ath,atl,last_updated
0,bitcoin,btc,Bitcoin,7308304.0,146386017371486,1,3.076642e+12,20033796.0,20033812.0,11187013.0,3993.42,2026-05-24

### **Crypto_Prices (Daily Prices of Top Coins)**

In [ ]:
df = pd.read_sql("SELECT * FROM  top_coins;", engine)
df

      coin_id        date         price
0     bitcoin  2025-05-25  9.173866e+06
1     bitcoin  2025-05-26  9.274976e+06
2     bitcoin  2025-05-27  9.314437e+06
3     bitcoin  2025-05-28  9.310175e+06
4     bitcoin  2025-05-29  9.208281e+06
..        ...         ...           ...
727  ethereum  2026-05-21  2.053445e+05
728  ethereum  2026-05-22  2.050139e+05
729  ethereum  2026-05-23  1.976018e+05
730  ethereum  2026-05-24  2.024743e+05
731  ethereum  2026-05-24  2.003096e+05

[732 rows x 3 columns]

In [ ]:
# 1. Find the highest daily price of Bitcoin in the last 365 days.

df = pd.read_sql(
    """SELECT coin_id, MAX(price) AS highest_daily_price FROM top_coins WHERE coin_id = 'bitcoin' AND DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);""", engine
)

df

   coin_id  highest_daily_price
0  bitcoin         1.107047e+07

In [ ]:
# 2. Calculate the average daily price of Ethereum in the past 1 year.

df = pd.read_sql ("SELECT coin_id, AVG(price) as Avg_price FROM top_coins WHERE coin_id = 'ethereum' AND DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY);", engine)

df

    coin_id      Avg_price
0  ethereum  271467.115309

In [ ]:
# 3. Show the daily price trend of Bitcoin in January 2025. (or change the month and year according you your data)

df = pd.read_sql(
    """SELECT coin_id, price AS daily_price, date FROM top_coins WHERE coin_id = 'bitcoin' AND Date BETWEEN '2025-01-01' AND '2026-02-28' ORDER BY Date;""", engine)

df

     coin_id   daily_price        date
0    bitcoin  9.173866e+06  2025-05-25
1    bitcoin  9.274976e+06  2025-05-26
2    bitcoin  9.314437e+06  2025-05-27
3    bitcoin  9.310175e+06  2025-05-28
4    bitcoin  9.208281e+06  2025-05-29
..       ...           ...         ...
275  bitcoin  5.877905e+06  2026-02-24
276  bitcoin  5.825506e+06  2026-02-25
277  bitcoin  6.179907e+06  2026-02-26
278  bitcoin  6.139222e+06  2026-02-27
279  bitcoin  6.000770e+06  2026-02-28

[280 rows x 3 columns]

In [ ]:
# 4. Find the coin with the highest average price over 1 year.

df = pd.read_sql (
    """SELECT coin_id, AVG(price) AS avg_price FROM top_coins WHERE DATE(date) >= DATE_SUB(CURDATE(), INTERVAL 365 DAY)
    GROUP BY coin_id ORDER BY avg_price DESC LIMIT 1;""",
    engine)

df

   coin_id     avg_price
0  bitcoin  8.470050e+06

In [ ]:
# 5. Get the % change in Bitcoin’s price between Feb 2025 and Feb 2026.

df = pd.read_sql(
    """ SELECT
        (
            (MAX(CASE WHEN DATE(date) BETWEEN '2026-02-01' AND '2026-02-28' THEN price END)
                -
                MAX(CASE WHEN DATE(date) BETWEEN '2025-02-01' AND '2025-02-28' THEN price END)
            )
            /
            MAX(CASE WHEN DATE(date) BETWEEN '2025-02-01' AND '2025-02-28' THEN price END)
        ) * 100 AS percentage_change
    FROM top_coins WHERE coin_id = 'bitcoin';""",
    engine
)

df

  percentage_change
0              None

### **Oil_Price**

In [ ]:
df = pd.read_sql ("SELECT * FROM  oil_prices;", engine)
df

            Date  Price
0     2020-01-02  61.17
1     2020-01-03  63.00
2     2020-01-06  63.27
3     2020-01-07  62.70
4     2020-01-08  59.65
...          ...    ...
1530  2026-02-17  62.53
1531  2026-02-18  65.33
1532  2026-02-19  66.66
1533  2026-02-20  66.69
1534  2026-02-23  66.36

[1535 rows x 2 columns]

In [ ]:
# 1. Find the highest oil price in the last 5 years.

df = pd.read_sql(""" SELECT MAX(price) AS highest_price FROM oil_prices WHERE date >= DATE_SUB(CURDATE(), INTERVAL 5 YEAR);
""", engine)

df

   highest_price
0         123.64

In [ ]:
# 2. Get the average oil price per year.

df = pd.read_sql("""SELECT YEAR(date) AS year, AVG(price) AS avg_price
FROM oil_prices GROUP BY YEAR(date) ORDER BY YEAR(date);""", engine)

df

   year  avg_price
0  2020  39.160437
1  2021  68.135100
2  2022  94.902869
3  2023  77.576532
4  2024  76.632240
5  2025  65.388105
6  2026  61.812000

In [ ]:
# 3. Show oil prices during COVID crash (March–April 2020).

df = pd.read_sql("""SELECT date, price FROM oil_prices WHERE date BETWEEN '2020-03-01' AND '2020-04-30' ORDER BY date;
""", engine)

df

          date  price
0   2020-03-02  46.78
1   2020-03-03  47.27
2   2020-03-04  46.78
3   2020-03-05  45.90
4   2020-03-06  41.14
5   2020-03-09  31.05
6   2020-03-10  34.47
7   2020-03-11  33.13
8   2020-03-12  31.56
9   2020-03-13  31.72
10  2020-03-16  28.96
11  2020-03-17  26.96
12  2020-03-18  20.48
13  2020-03-19  25.09
14  2020-03-20  19.48
15  2020-03-23  23.33
16  2020-03-24  21.03
17  2020-03-25  20.75
18  2020-03-26  16.60
19  2020-03-27  15.48
20  2020-03-30  14.10
21  2020-03-31  20.51
22  2020-04-01  20.28
23  2020-04-02  25.18
24  2020-04-03  28.36
25  2020-04-06  26.21
26  2020-04-07  23.54
27  2020-04-08  24.97
28  2020-04-09  22.90
29  2020-04-13  22.36
30  2020-04-14  20.15
31  2020-04-15  19.96
32  2020-04-16  19.82
33  2020-04-17  18.31
34  2020-04-20 -36.98
35  2020-04-21   8.91
36  2020-04-22  13.64
37  2020-04-23  15.06
38  2020-04-24  15.99
39  2020-04-27  12.17
40  2020-04-28  12.40
41  2020-04-29  15.04
42  2020-04-30  19.23

In [ ]:
# 4. Find the lowest price of oil in the last 10 years.

df = pd.read_sql("""SELECT date, price FROM oil_prices
WHERE price = (SELECT MIN(price) FROM oil_prices WHERE date >= DATE_SUB(CURDATE(), INTERVAL 10 YEAR));
""", engine)

df

         date  price
0  2020-04-20 -36.98

In [ ]:
# 5. Calculate the volatility of oil prices (max-min difference per year).

df = pd.read_sql("""SELECT YEAR(date) AS year, MAX(price) AS highest_price, MIN(price) AS lowest_price, MAX(price) - MIN(price) AS volatility
FROM oil_prices GROUP BY YEAR(date) ORDER BY YEAR(date);
""", engine)

df

   year  highest_price  lowest_price  volatility
0  2020          63.27        -36.98      100.25
1  2021          85.64         47.47       38.17
2  2022         123.64         71.05       52.59
3  2023          93.67         66.61       27.06
4  2024          87.69         66.73       20.96
5  2025          80.73         55.44       25.29
6  2026          66.69         56.01       10.68

### **Stock_Prices**

In [ ]:
df = pd.read_sql("SELECT * FROM stks_prices;", engine)
df

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-03,^NSEI,12261.099609,12265.599609,12191.349609,12226.650391,4.288000e+05
3,2020-01-06,^NSEI,12170.599609,12179.099609,11974.200195,11993.049805,3.965000e+05
4,2020-01-07,^NSEI,12079.099609,12152.150391,12005.349609,12052.950195,4.478000e+05
...,...,...,...,...,...,...,...
4600,2026-02-13,^GSPC,6834.270020,6881.959961,6794.549805,6836.169922,5.718360e+09
4601,2026-02-17,^GSPC,6819.859863,6866.990234,6775.500000,6843.220215,5.418480e+09
4602,2026-02-18,^GSPC,6855.479980,6909.120117,6849.660156,6881.310059,5.098160e+09
4603,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
4604,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09

In [ ]:
# 1. Get all stock prices for a given ticker

df = pd.read_sql(""" SELECT * FROM stks_prices WHERE Ticker IN ('^IXIC', '^NSEI', '^GSPC')
AND Open IS NOT NULL AND High IS NOT NULL
AND Low IS NOT NULL AND Close IS NOT NULL
AND Volume IS NOT NULL ORDER BY Date;
""", engine)

df

,Date,Ticker,Open,High,Low,Close,Volume
0,2020-01-01,^NSEI,12202.150391,12222.200195,12165.299805,12182.500000,3.041000e+05
1,2020-01-02,^NSEI,12198.549805,12289.900391,12195.250000,12282.200195,4.077000e+05
2,2020-01-02,^GSPC,3244.669922,3258.139893,3235.530029,3257.850098,3.459930e+09
3,2020-01-02,^IXIC,9039.459961,9093.429688,9010.889648,9092.190430,2.862700e+09
4,2020-01-03,^IXIC,8976.429688,9065.759766,8976.429688,9020.769531,2.586520e+09
...,...,...,...,...,...,...,...
4600,2026-02-19,^GSPC,6861.339844,6879.120117,6833.060059,6861.890137,5.151690e+09
4601,2026-02-19,^NSEI,25873.349609,25885.300781,25388.750000,25454.349609,2.982000e+05
4602,2026-02-20,^NSEI,25406.550781,25663.550781,25379.750000,25571.250000,2.966000e+05
4603,2026-02-20,^GSPC,6843.259766,6915.859863,6836.330078,6909.509766,5.432480e+09
4604,2026-02-20,^IXIC,22542.279297,22948.869141,22539.050781,22886.070312,8.063070e+09

In [ ]:
# 2. Find the highest closing price for NASDAQ (^IXIC)

df = pd.read_sql ("SELECT MAX(close) AS highest_closing_price FROM stks_prices WHERE ticker = '^IXIC';", engine)

df

   highest_closing_price
0           23958.470703

In [ ]:
# 3. List top 5 days with highest price difference (high - low) for S&P 500 (^GSPC)

df = pd.read_sql ("""SELECT date, high - low AS price_difference FROM stks_prices
WHERE ticker = '^GSPC' ORDER BY price_difference DESC LIMIT 5
;""", engine)

df

         date  price_difference
0  2025-04-09        532.909668
1  2025-04-07        411.529785
2  2025-04-08        357.050293
3  2025-04-10        237.879883
4  2025-11-20        236.300293

In [ ]:
# 4. Get monthly average closing price for each ticker

df = pd.read_sql("""
SELECT Ticker,
       DATE_FORMAT(Date, '%Y-%m') AS month,
       AVG(Close) AS avg_closing_price
FROM stks_prices
WHERE Close IS NOT NULL AND Date IS NOT NULL
GROUP BY Ticker, month ORDER BY Ticker, month;
""", engine)

df

    Ticker    month  avg_closing_price
0    ^GSPC  2020-01        3278.202858
1    ^GSPC  2020-02        3277.314183
2    ^GSPC  2020-03        2652.393632
3    ^GSPC  2020-04        2761.975226
4    ^GSPC  2020-05        2919.608484
..     ...      ...                ...
217  ^NSEI  2025-10       25494.083519
218  ^NSEI  2025-11       25894.834396
219  ^NSEI  2025-12       25997.738725
220  ^NSEI  2026-01       25652.962695
221  ^NSEI  2026-02       25681.076693

[222 rows x 3 columns]

### **Joint Querries**

In [ ]:
# 1. Compare Bitcoin vs Oil average price in 2025.

df = pd.read_sql("""
SELECT
    DATE(c.date) AS date,
    c.price AS btc_close,
    o.price AS oil_close
FROM top_coins c
LEFT JOIN oil_prices o
    ON DATE(c.date) = DATE(o.date)
WHERE c.coin_id = 'bitcoin'
AND c.price IS NOT NULL
AND o.price IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_close  oil_close
0    2025-05-27  9.314437e+06      61.61
1    2025-05-28  9.310175e+06      62.54
2    2025-05-29  9.208281e+06      61.66
3    2025-05-30  9.026593e+06      61.46
4    2025-06-02  9.040802e+06      63.27
..          ...           ...        ...
180  2026-02-17  6.255750e+06      62.53
181  2026-02-18  6.116330e+06      65.33
182  2026-02-19  6.033802e+06      66.66
183  2026-02-20  6.092367e+06      66.69
184  2026-02-23  6.132044e+06      66.36

[185 rows x 3 columns]

In [ ]:
# 2. Check if Bitcoin moves with S&P 500 (correlation idea).

df = pd.read_sql("""
SELECT
    DATE(t.date) AS date,
    t.price AS btc_close,
    s.Close AS stks_close
FROM top_coins t
LEFT JOIN stks_prices s
    ON DATE(t.date) = DATE(s.Date)
   AND s.Ticker = '^GSPC'
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_close   stks_close
0    2025-05-27  9.314437e+06  5921.540039
1    2025-05-28  9.310175e+06  5888.549805
2    2025-05-29  9.208281e+06  5912.169922
3    2025-05-30  9.026593e+06  5911.689941
4    2025-06-02  9.040802e+06  5935.939941
..          ...           ...          ...
181  2026-02-13  5.993963e+06  6836.169922
182  2026-02-17  6.255750e+06  6843.220215
183  2026-02-18  6.116330e+06  6881.310059
184  2026-02-19  6.033802e+06  6861.890137
185  2026-02-20  6.092367e+06  6909.509766

[186 rows x 3 columns]

In [ ]:
# 3. Compare Ethereum and NASDAQ daily prices for 2025.

df = pd.read_sql("""
SELECT
    DATE(t.date) AS date,
    t.price AS eth_close,
    s.Close AS nasdaq_close
FROM top_coins t
JOIN stks_prices s
    ON DATE(t.date) = DATE(s.Date)
WHERE t.coin_id = 'ethereum'
AND s.Ticker = '^IXIC'
AND YEAR(t.date) = 2025
AND t.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date;
""", engine)


df

           date      eth_close  nasdaq_close
0    2025-05-27  218190.675235  19199.160156
1    2025-05-28  227238.584850  19100.939453
2    2025-05-29  228525.939096  19175.869141
3    2025-05-30  224768.844035  19113.769531
4    2025-06-02  217089.574074  19242.609375
..          ...            ...           ...
147  2025-12-24  265308.330577  23613.310547
148  2025-12-26  261698.838882  23593.099609
149  2025-12-29  264760.550466  23474.349609
150  2025-12-30  263786.422730  23419.080078
151  2025-12-31  266620.867155  23241.990234

[152 rows x 3 columns]

In [ ]:
# 4. Find days when oil price spiked and compare with Bitcoin price change.

df = pd.read_sql ("""SELECT date(o.Date) AS date,
    o.Price AS oil_price,
    t.price AS btc_price
FROM oil_prices o
JOIN top_coins t
    ON date(o.Date) = date(t.Date)
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND o.price IS NOT NULL
ORDER BY date;
""", engine)

df

           date  oil_price     btc_price
0    2025-05-27      61.61  9.314437e+06
1    2025-05-28      62.54  9.310175e+06
2    2025-05-29      61.66  9.208281e+06
3    2025-05-30      61.46  9.026593e+06
4    2025-06-02      63.27  9.040802e+06
..          ...        ...           ...
180  2026-02-17      62.53  6.255750e+06
181  2026-02-18      65.33  6.116330e+06
182  2026-02-19      66.66  6.033802e+06
183  2026-02-20      66.69  6.092367e+06
184  2026-02-23      66.36  6.132044e+06

[185 rows x 3 columns]

In [ ]:
# 5. Compare top 3 coins daily price trend vs Nifty (^NSEI).

df = pd.read_sql ("""
SELECT
    date(c.Date) AS date,
    c.coin_id AS coins,
    c.price AS coin_prices,
    s.Close AS nifty_close
FROM top_coins c
JOIN stks_prices s
    ON date(c.Date) = date(s.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
  AND s.Ticker = '^NSEI'
  AND c.price IS NOT NULL
  AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

           date     coins   coin_prices   nifty_close
0    2025-05-26  ethereum  2.169709e+05  25001.150391
1    2025-05-26   bitcoin  9.274976e+06  25001.150391
2    2025-05-27  ethereum  2.181907e+05  24826.199219
3    2025-05-27   bitcoin  9.314437e+06  24826.199219
4    2025-05-28   bitcoin  9.310175e+06  24752.449219
..          ...       ...           ...           ...
369  2026-02-18  ethereum  1.805283e+05  25819.349609
370  2026-02-19   bitcoin  6.033802e+06  25454.349609
371  2026-02-19  ethereum  1.774785e+05  25454.349609
372  2026-02-20   bitcoin  6.092367e+06  25571.250000
373  2026-02-20  ethereum  1.772492e+05  25571.250000

[374 rows x 4 columns]

In [ ]:
# 6. Compare stock prices (^GSPC) with crude oil prices on the same dates


df = pd.read_sql("""
SELECT
    date(s.Date) AS date,
    s.Close AS nifty_close,
    o.Price AS oil_price
FROM stks_prices s
JOIN oil_prices o
    ON date(s.Date) = date(o.Date)
WHERE s.Ticker = '^GSPC'
AND s.Close IS NOT NULL
AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

            date  nifty_close  oil_price
0     2020-01-02  3257.850098      61.17
1     2020-01-03  3234.850098      63.00
2     2020-01-06  3246.280029      63.27
3     2020-01-07  3237.179932      62.70
4     2020-01-08  3253.050049      59.65
...          ...          ...        ...
1529  2026-02-13  6836.169922      63.05
1530  2026-02-17  6843.220215      62.53
1531  2026-02-18  6881.310059      65.33
1532  2026-02-19  6861.890137      66.66
1533  2026-02-20  6909.509766      66.69

[1534 rows x 3 columns]

In [ ]:
# 7. Correlate Bitcoin closing price with crude oil closing price (same date)

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    o.Price AS oil_price
FROM top_coins t
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
AND t.price IS NOT NULL
AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_price  oil_price
0    2025-05-27  9.314437e+06      61.61
1    2025-05-28  9.310175e+06      62.54
2    2025-05-29  9.208281e+06      61.66
3    2025-05-30  9.026593e+06      61.46
4    2025-06-02  9.040802e+06      63.27
..          ...           ...        ...
180  2026-02-17  6.255750e+06      62.53
181  2026-02-18  6.116330e+06      65.33
182  2026-02-19  6.033802e+06      66.66
183  2026-02-20  6.092367e+06      66.69
184  2026-02-23  6.132044e+06      66.36

[185 rows x 3 columns]

In [ ]:
# 8. Compare NASDAQ (^IXIC) with Ethereum price trends

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS eth_price,
    s.Close AS ixic_close
FROM top_coins t
JOIN stks_prices s
    ON date(t.Date) = date(s.Date)
WHERE t.coin_id = 'ethereum'
  AND s.Ticker = '^IXIC'
  AND t.price IS NOT NULL
  AND s.Close IS NOT NULL
ORDER BY date;
""", engine)

df

           date      eth_price    ixic_close
0    2025-05-27  218190.675235  19199.160156
1    2025-05-28  227238.584850  19100.939453
2    2025-05-29  228525.939096  19175.869141
3    2025-05-30  224768.844035  19113.769531
4    2025-06-02  217089.574074  19242.609375
..          ...            ...           ...
181  2026-02-13  176214.238345  22546.669922
182  2026-02-17  181624.154700  22578.380859
183  2026-02-18  180528.328343  22753.630859
184  2026-02-19  177478.459914  22682.730469
185  2026-02-20  177249.247482  22886.070312

[186 rows x 3 columns]

In [ ]:
# 9. Join top 3 crypto coins with stock indices for 2025
df = pd.read_sql("""
SELECT
    DATE(c.Date) AS date,
    c.coin_id AS crypto_coin,
    c.price AS crypto_price,
    s.Ticker AS stock_index,
    s.Close AS stock_close
FROM top_coins c
JOIN stks_prices s
    ON DATE(c.Date) = DATE(s.Date)
WHERE c.coin_id IN ('bitcoin', 'ethereum', 'binancecoin')
AND s.Ticker IN ('^GSPC', '^IXIC', '^NSEI')
AND YEAR(c.Date) = 2025
AND c.price IS NOT NULL
AND s.Close IS NOT NULL
ORDER BY date, crypto_coin;
""", engine)

df

           date crypto_coin  crypto_price stock_index   stock_close
0    2025-05-26     bitcoin  9.274976e+06       ^NSEI  25001.150391
1    2025-05-26    ethereum  2.169709e+05       ^NSEI  25001.150391
2    2025-05-27     bitcoin  9.314437e+06       ^GSPC   5921.540039
3    2025-05-27     bitcoin  9.314437e+06       ^IXIC  19199.160156
4    2025-05-27     bitcoin  9.314437e+06       ^NSEI  24826.199219
..          ...         ...           ...         ...           ...
907  2025-12-31     bitcoin  7.936951e+06       ^IXIC  23241.990234
908  2025-12-31     bitcoin  7.936951e+06       ^NSEI  26129.599609
909  2025-12-31    ethereum  2.666209e+05       ^GSPC   6845.500000
910  2025-12-31    ethereum  2.666209e+05       ^IXIC  23241.990234
911  2025-12-31    ethereum  2.666209e+05       ^NSEI  26129.599609

[912 rows x 5 columns]

In [ ]:
# 10. Multi-join: stock prices, oil prices, and Bitcoin prices for daily comparison

df = pd.read_sql("""
SELECT
    date(t.Date) AS date,
    t.price AS btc_price,
    s.Close AS stk_close,
    o.Price AS oil_price
FROM top_coins t
JOIN stks_prices s
    ON date(t.Date) = date(s.Date)
JOIN oil_prices o
    ON date(t.Date) = date(o.Date)
WHERE t.coin_id = 'bitcoin'
  AND s.Ticker = '^GSPC'
  AND t.price IS NOT NULL
  AND s.Close IS NOT NULL
  AND o.Price IS NOT NULL
ORDER BY date;
""", engine)

df

           date     btc_price    stk_close  oil_price
0    2025-05-27  9.314437e+06  5921.540039      61.61
1    2025-05-28  9.310175e+06  5888.549805      62.54
2    2025-05-29  9.208281e+06  5912.169922      61.66
3    2025-05-30  9.026593e+06  5911.689941      61.46
4    2025-06-02  9.040802e+06  5935.939941      63.27
..          ...           ...          ...        ...
179  2026-02-13  5.993963e+06  6836.169922      63.05
180  2026-02-17  6.255750e+06  6843.220215      62.53
181  2026-02-18  6.116330e+06  6881.310059      65.33
182  2026-02-19  6.033802e+06  6861.890137      66.66
183  2026-02-20  6.092367e+06  6909.509766      66.69

[184 rows x 4 columns]